### ISSUE TITLE
Run "conda env create -f environment.yml" Ubuntu18.04

### ISSUE THREAD

**Issue by Finedl** [flow-project/flow#1019]
Building wheel for setproctitle (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/hadoop/anaconda3/envs/flow/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6fkkzj5e/setproctitle/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6fkkzj5e/setproctitle/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-_nniympy
       cwd: /tmp/pip-install-6fkkzj5e/setproctitle/
  Complete output (10 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'setproctitle' extension
  creating build
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/src
  gcc -pthread -B /home/hadoop/anaconda3/envs/flow/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DSPT_VERSION=1.1.10 -DHAVE_SYS_PRCTL_H=1 -I/home/hadoop/anaconda3/envs/flow/include/python3.6m -c src/setproctitle.c -o build/temp.linux-x86_64-3.6/src/setproctitle.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for setproctitle
  Running setup.py clean for setproctitle
  Building wheel for psutil (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/hadoop/anaconda3/envs/flow/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6fkkzj5e/psutil/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6fkkzj5e/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-4qr_frut
       cwd: /tmp/pip-install-6fkkzj5e/psutil/
  Complete output (44 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/psutil
  copying psutil/_common.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_psposix.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_psosx.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_psaix.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/__init__.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_compat.py -> build/lib.linux-x86_64-3.6/psutil
  creating build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/runner.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_testutils.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_memleaks.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.6/psutil/tests
  running build_ext
  building 'psutil._psutil_linux' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/psutil
  gcc -pthread -B /home/hadoop/anaconda3/envs/flow/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=573 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/home/hadoop/anaconda3/envs/flow/include/python3.6m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.6/psutil/_psutil_common.o
  unable to execute 'gcc': No such file or directory
  C compiler or Python headers are not installed on this system. Try to run:
  sudo apt-get install gcc python3-dev
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for psutil
  Running setup.py clean for psutil
  Building wheel for pyyaml (setup.py) ... done
  Created wheel for pyyaml: filename=PyYAML-5.3.1-cp36-cp36m-linux_x86_64.whl size=44619 sha256=d3be7b525425a2e9dd4f30867e9f12681d161d1fd9915007bf5cda60db2665f0
  Stored in directory: /home/hadoop/.cache/pip/wheels/e9/85/f1/b2c605800c9b4a69e8b371d2f3e71b165e3fe40ebad4b9507c
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491059 sha256=2a04a1ee1beef0bf17e8276c01bf5d71b21c08a706a66cd0436b23cdf4022aed
  Stored in directory: /home/hadoop/.cache/pip/wheels/e6/81/ce/83c74da5bcad2d6f360aed212c246d97a274b9681654a8389d
Successfully built gym nose2 dill pyyaml future
Failed to build setproctitle psutil
Installing collected packages: future, pyglet, gym, pyprind, coverage, nose2, cached-property, joblib, pyparsing, kiwisolver, cycler, matplotlib, dill, lz4, pyyaml, click, packaging, toml, py, attrs, iniconfig, pluggy, pytest, redis, filelock, funcsigs, colorama, ray, setproctitle, psutil, opencv-python, jmespath, docutils, botocore, s3transfer, boto3
    Running setup.py install for setproctitle ... error
    ERROR: Command errored out with exit status 1:
     command: /home/hadoop/anaconda3/envs/flow/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6fkkzj5e/setproctitle/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6fkkzj5e/setproctitle/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6pz4yfkv/install-record.txt --single-version-externally-managed --compile --install-headers /home/hadoop/anaconda3/envs/flow/include/python3.6m/setproctitle
         cwd: /tmp/pip-install-6fkkzj5e/setproctitle/
    Complete output (10 lines):
    running install
    running build
    running build_ext
    building 'setproctitle' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    gcc -pthread -B /home/hadoop/anaconda3/envs/flow/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DSPT_VERSION=1.1.10 -DHAVE_SYS_PRCTL_H=1 -I/home/hadoop/anaconda3/envs/flow/include/python3.6m -c src/setproctitle.c -o build/temp.linux-x86_64-3.6/src/setproctitle.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/hadoop/anaconda3/envs/flow/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6fkkzj5e/setproctitle/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6fkkzj5e/setproctitle/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6pz4yfkv/install-record.txt --single-version-externally-managed --compile --install-headers /home/hadoop/anaconda3/envs/flow/include/python3.6m/setproctitle Check the logs for full command output.

**Comment by Finedl** [comment]
sudo apt-get install gcc python3-dev

error:
 gcc : 依赖: gcc-7 (>= 7.3.0-12~) 但是它将不会被安装
 python3-dev : 依赖: python3 (= 3.6.5-3) 但是 3.6.7-1~18.04 正要被安装
               依赖: libpython3-dev (= 3.6.5-3) 但是它将不会被安装
               依赖: python3.6-dev (>= 3.6.5-2~) 但是它将不会被安装
E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。

Translate above
gcc: Dependency: gcc-7 (>= 7.3.0-12~) but it will not be installed
  python3-dev: Dependency: python3 (= 3.6.5-3) but 3.6.7-1~18.04 are about to be installed
                Dependency: libpython3-dev (= 3.6.5-3) but it will not be installed
                Dependency: python3.6-dev (>= 3.6.5-2~) but it will not be installed
E: Errors cannot be corrected, because you require certain software packages to maintain the status quo, that is, they break the dependencies between the software packages.

**Comment by jainmilan** [comment]
I tried
`sudo apt update` 
&&
`sudo apt install build-essential`

in my Ubuntu machine and it worked by automatically installing the gcc. If it doesn't work, you add it through `sudo apt-get install manpages-dev` and validate the gcc installation using `gcc --version`. I hope it helps!

**Comment by Finedl** [comment]
Thank you. This problem bothered me for two days. I solved it by reinstalling ubuntu18.04 and reconfiguring the environment.


thank you





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Milan Jain"<notifications@github.com&gt;; 
发送时间: 2020年10月27日(星期二) 中午1:39
收件人: "flow-project/flow"<flow@noreply.github.com&gt;; 
抄送: "陈栋梁"<936418030@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [flow-project/flow] Run &quot;conda env create -f environment.yml&quot; Ubuntu18.04 (#1019)





 
I tried
 sudo apt update
 &amp;&amp;
 sudo apt install build-essential
 
in my Ubuntu machine and it worked by automatically installing the gcc. If it doesn't work, you add it through sudo apt-get install manpages-dev and validate the gcc installation using gcc --version. I hope it helps!

**Comment by Finedl** [comment]
Thank you. This problem bothered me for two days. I solved it by reinstalling ubuntu18.04 and reconfiguring the environment.

thank you
