### ISSUE TITLE
Error during start: [Errno 2] No such file or directory: 'd:\\flow\\flow\\core\\kernel\\network/debug/cfg/ring_example_20201130-1543421606722222.2469628.net.xml'

### ISSUE THREAD

**Issue by zhilee2019** [flow-project/flow#1025]
## Bug Description

Hi when I ran tutorials, I got the following error.  

## Bug Reproduce

Ran Tutorial 01: Running Sumo Simulations

## Output Log

Full error output log:

TypeError                                 Traceback (most recent call last)
<ipython-input-16-cb0e796bc536> in <module>()
     14 # number of time steps
     15 flow_params['env'].horizon = 3000
---> 16 exp = Experiment(flow_params)
     17 
     18 # run the sumo simulation

d:\flow\flow\core\experiment.py in __init__(self, flow_params, custom_callables)
     77 
     78         # Create the environment.
---> 79         self.env = create_env()
     80 
     81         logging.info(" Starting experiment {} at {}".format(

d:\flow\flow\utils\registry.py in create_env(*_)
    128             })
    129 
--> 130         return gym.envs.make(env_name)
    131 
    132     return create_env, env_name

D:\MiniConda\envs\flow\lib\site-packages\gym-0.14.0-py3.7.egg\gym\envs\registration.py in make(id, **kwargs)
    154 
    155 def make(id, **kwargs):
--> 156     return registry.make(id, **kwargs)
    157 
    158 def spec(id):

D:\MiniConda\envs\flow\lib\site-packages\gym-0.14.0-py3.7.egg\gym\envs\registration.py in make(self, path, **kwargs)
     99             logger.info('Making new env: %s', path)
    100         spec = self.spec(path)
--> 101         env = spec.make(**kwargs)
    102         # We used to have people override _reset/_step rather than
    103         # reset/step. Set _gym_disable_underscore_compat = True on

D:\MiniConda\envs\flow\lib\site-packages\gym-0.14.0-py3.7.egg\gym\envs\registration.py in make(self, **kwargs)
     71         else:
     72             cls = load(self.entry_point)
---> 73             env = cls(**_kwargs)
     74 
     75         # Make the enviroment aware of which spec it came from.

d:\flow\flow\envs\ring\accel.py in __init__(self, env_params, sim_params, network, simulator)
     78         self.absolute_position = dict()
     79 
---> 80         super().__init__(env_params, sim_params, network, simulator)
     81 
     82     @property

d:\flow\flow\envs\base.py in __init__(self, env_params, sim_params, network, simulator, scenario)
    162         # use the network class's network parameters to generate the necessary
    163         # network components within the network kernel
--> 164         self.k.network.generate_network(self.network)
    165 
    166         # initial the vehicles kernel using the VehicleParams object

d:\flow\flow\core\kernel\network\traci.py in generate_network(self, network)
    144                 self.network.edges,
    145                 self.network.types,
--> 146                 connections
    147             )
    148 

d:\flow\flow\core\kernel\network\traci.py in generate_net(self, net_params, traffic_lights, nodes, edges, types, connections)
    529                 print('Retrying in {} seconds...'.format(WAIT_ON_ERROR))
    530                 time.sleep(WAIT_ON_ERROR)
--> 531         raise error
    532 
    533     def generate_net_from_osm(self, net_params):

TypeError: exceptions must derive from BaseException

## Screenshots

Screenshots:

![picture name](https://link/to/screenshot)

## Versions

- OS: ? (For example, RedHat, macOS Mojave, ...]
- Flow version: ? (run `python -c "import flow; print(flow.__version__)"`)
- Flow commit number: ? (run `git log` and copy the commit number)

**Comment by zhilee2019** [comment]
I have found the problem. It is beacuse of subprocess call didn't create the xml file via netconvert.  It's ok now! Thanks

**Comment by bumbleshet** [comment]
Hi, could you please document the solution? I am having the same problem.

**Comment by zhangfengyo** [comment]
> I have found the problem. It is beacuse of subprocess call didn't create the xml file via netconvert. It's ok now! Thanks

So how can i solve this problem????

**Comment by Yicen-y** [comment]
> > I have found the problem. It is beacuse of subprocess call didn't create the xml file via netconvert. It's ok now! Thanks
> 
> So how can i solve this problem????

Hi. I've found this problem, too. 
Cause: 'netconver -c' was not successfully executed in the middle of subprocess.call() in the flow/core/kernel/network/traci .py. The main reason is a ''' problem in the path. 
I'm running under Windows .
My method: the path front of the 'r' blocks escape

**Comment by marwaelharoun** [comment]
please



> > > I have found the problem. It is beacuse of subprocess call didn't create the xml file via netconvert. It's ok now! Thanks
> > 
> > 
> > So how can i solve this problem????
> 
> Hi. I've found this problem, too. Cause: 'netconver -c' was not successfully executed in the middle of subprocess.call() in the flow/core/kernel/network/traci .py. The main reason is a ''' problem in the path. I'm running under Windows . My method: the path front of the 'r' blocks escape

please, could you send me traci.py file after your modification because I have the same problem
my e-mail: marwa.elharoun@mans.edu.eg

**Comment by Yicen-y** [comment]
> please
> 
> > > > I have found the problem. It is beacuse of subprocess call didn't create the xml file via netconvert. It's ok now! Thanks
> > > 
> > > 
> > > So how can i solve this problem????
> > 
> > 
> > Hi. I've found this problem, too. Cause: 'netconver -c' was not successfully executed in the middle of subprocess.call() in the flow/core/kernel/network/traci .py. The main reason is a ''' problem in the path. I'm running under Windows . My method: the path front of the 'r' blocks escape
> 
> please, could you send me traci.py file after your modification because I have the same problem my e-mail: [marwa.elharoun@mans.edu.eg](mailto:marwa.elharoun@mans.edu.eg)

The email has been sent, please check it.

**Comment by UnionPan** [comment]
> > please
> > > > > I have found the problem. It is beacuse of subprocess call didn't create the xml file via netconvert. It's ok now! Thanks
> > > > 
> > > > 
> > > > So how can i solve this problem????
> > > 
> > > 
> > > Hi. I've found this problem, too. Cause: 'netconver -c' was not successfully executed in the middle of subprocess.call() in the flow/core/kernel/network/traci .py. The main reason is a ''' problem in the path. I'm running under Windows . My method: the path front of the 'r' blocks escape
> > 
> > 
> > please, could you send me traci.py file after your modification because I have the same problem my e-mail: [marwa.elharoun@mans.edu.eg](mailto:marwa.elharoun@mans.edu.eg)
> 
> The email has been sent, please check it.

I would appreciate that if you can send a traci.py file to yp1170@nyu.edu as well! And may I ask if there's any following issues?

**Comment by jaylijiawei** [comment]
@Yicen-y please, could you send me traci.py file after your modification because I have the same problem my e-mail: [1143764699@qq.com]

**Comment by Yicen-y** [comment]
> @Yicen-y please, could you send me traci.py file after your modification because I have the same problem my e-mail: [[1143764699@qq.com](mailto:1143764699@qq.com)]

The email has been sent, please check it.

**Comment by Yicen-y** [comment]
> 
The email has been sent, please check it.

**Comment by Yicen-y** [comment]
> > > please
> > > > > > I have found the problem. It is beacuse of subprocess call didn't create the xml file via netconvert. It's ok now! Thanks
> > > > > 
> > > > > 
> > > > > So how can i solve this problem????
> > > > 
> > > > 
> > > > Hi. I've found this problem, too. Cause: 'netconver -c' was not successfully executed in the middle of subprocess.call() in the flow/core/kernel/network/traci .py. The main reason is a ''' problem in the path. I'm running under Windows . My method: the path front of the 'r' blocks escape
> > > 
> > > 
> > > please, could you send me traci.py file after your modification because I have the same problem my e-mail: [marwa.elharoun@mans.edu.eg](mailto:marwa.elharoun@mans.edu.eg)
> > 
> > 
> > The email has been sent, please check it.
> 
> I would appreciate that if you can send a traci.py file to [yp1170@nyu.edu](mailto:yp1170@nyu.edu) as well! And may I ask if there's any following issues?

The email has been sent, please check it.

**Comment by weihan123456** [comment]
@Yicen-y Hi, I have the same problem, could you send me traci.py file? I do appreciate your kindness.
my email: f110151119@nkust.edu.tw

**Comment by tianzongkai** [comment]
@Yicen-y Hi Yicen, could you please copy and paste the updated part of traci.py in the comment so others could see it? Thanks!

**Comment by hamedinho** [comment]
Hi, I have the same problem. Could you please send me traci.py file? I do appreciate your kindness. My email: hamed.naseri.civ@gmail.com.
