### ISSUE TITLE
use "conda env create -f environment.yml", but failed?

### ISSUE THREAD

**Issue by Dukering** [flow-project/flow#1030]
The conflict is caused by:
    The user requested redis~=2.10.6
    ray 0.8.0 depends on redis>=3.3.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

Pip subprocess error:
ERROR: Cannot install -r /Users/dulei/Documents/Flow/flow/condaenv.k_4i73t0.requirements.txt (line 18) and redis~=2.10.6 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

failed

CondaEnvException: Pip failed

**Comment by obisargoni** [comment]
I also had this issue installing flow on a linux windows subsystem

**Comment by philippwulff** [comment]
same issue on Linux Mint 20

How did you fix it? Is there something wrong with the environment.yml file? Or does this work for other people?

**Comment by philippwulff** [comment]
Same issue in Linux Mint 19.3 on a different system

**Comment by amanpatel123** [comment]
@Dukering How did you fix it?

**Comment by arashtavakoli** [comment]
Is this issue fixed? I tried this package on both windows and Linux and in both ways I get dependency issues like the above. Not sure for what OS this package was designed originally really.

**Comment by Dukering** [comment]
I modify the redis~=2.10.6 to redis in environment.yml and requirements.txt ,and it works!

**Comment by NovemberChopin** [comment]
I repleace the "redis~=2.10.6" by "redis", it works

**Comment by HappyDay-design** [comment]
Hello all

 I installed Flow with repleacing the "redis~=2.10.6" by "redis".

But when I ran tutorial 3 and 4, it had error. 

AttributeError: 'numpy.ndarray' object has no attribute 'keys'

And empty .csv file 
so I think the installation is not really right

**Comment by PatrickAllenCooper** [comment]
I also had to specify "cloudpickle~=1.2.0" after setting "redis~=2.10.6" to "redis".

This allowed me to install flow successfully.

Environment: Colab

**Comment by HappyDay-design** [comment]
> I also had to specify "cloudpickle~=1.2.0" after setting "redis~=2.10.6" to "redis".
> 
> This allowed me to install flow successfully.
> 
> Environment: Colab

I am very happy with your news
Did you try to take all tutorials from 01 to 14? 
In the past, I could install Sumo but I can not run all tutorials

**Comment by HappyDay-design** [comment]
> 



> I also had to specify "cloudpickle~=1.2.0" after setting "redis~=2.10.6" to "redis".
> 
> This allowed me to install flow successfully.
> 
> Environment: Colab

I can not install Flow with your instructions

![image](https://user-images.githubusercontent.com/82990411/194981531-cfded74a-d7d2-4424-bd3b-cf8051dd7009.png)

**Comment by PatrickAllenCooper** [comment]
> > 
> 
> > I also had to specify "cloudpickle~=1.2.0" after setting "redis~=2.10.6" to "redis".
> > This allowed me to install flow successfully.
> > Environment: Colab
> 
> I can not install Flow with your instructions
> 
> ![image](https://user-images.githubusercontent.com/82990411/194981531-cfded74a-d7d2-4424-bd3b-cf8051dd7009.png)

You are using a very different environment than me so there are no guarantees, but let's check some things.

Did you include cloudpickle and regis in both the requirements.txt and environment.yml?
