### ISSUE TITLE
[installation] wording of setup instructions

### ISSUE THREAD

**Issue by cathywu** [flow-project/flow#106]
Can we improve the wording of the two installation options on our readthedocs? (see Screenshot below)

- Remove the numbers for the setup instructions?
- What is a "testing purpose" that one would want to use the docker installation for?

<img width="672" alt="image" src="https://user-images.githubusercontent.com/329117/45126255-6b7d1300-b127-11e8-8f83-8f8d1aca52cd.png">

**Comment by AboudyKreidieh** [comment]
I think we can remove the comment within parentheses, people who use Docker will be familiar, and the local installation instructions are in the process of becoming simpler

**Comment by cathywu** [comment]
++

**Comment by cathywu** [comment]
It's also not clear to me what "simple utilization" means. A new user to the readthedocs may always opt to install the docker because it's easier. I don't suppose that is desirable at this point?

**Comment by kjang96** [comment]
This seems resolved @cathywu can you confirm?
