### ISSUE TITLE
[installation] "Custom configuration" section is unclear

### ISSUE THREAD

**Issue by cathywu** [flow-project/flow#107]
It's not clear what "user-specific config parameters" means. @kanaadp could you take a stab at this since I believe includes pycharm parameters?

Link for convenience: https://flow.readthedocs.io/en/latest/flow_setup.html#h-custom-configuration

**Comment by AboudyKreidieh** [comment]
we can ignore/remove these. i've personally never changed them, and they have no serious effect on anything)

**Comment by AboudyKreidieh** [comment]
this has been removed by a previous PR
