### ISSUE TITLE
[installation] Streamline instructions

### ISSUE THREAD

**Issue by cathywu** [flow-project/flow#113]
All of the following refers to the setup instructions on readthedocs: https://flow.readthedocs.io/en/latest/flow_setup.html#b-testing-the-installation.

1. Can we move the "optional" / experimental parts of the setup down below 
```
f. Getting started (rllab-multiagent)
g. Getting started (Ray/RLlib)
```

2. Can we rename "Getting started" to "Testing your installation (rllab)" (or similar)?

3. Can we put the RLlib "Testing your installation" before the rllab one?

4. We should change "Ray/RLlib" to "Ray RLlib"

5. We should capitalize SUMO throughout

6. I think it's a bit misleading to say that RLlib / rllab are optional. One of them is needed for the advertised purpose of running deep RL methods. Can we use a different word?

7. Wrap "FXApp:openDisplay: unable to open display :0.0" in backticks (`).

Screenshot here for reference.

<img width="714" alt="image" src="https://user-images.githubusercontent.com/329117/45141354-80c76100-b16a-11e8-9c20-bcea576de22f.png">

**Comment by kjang96** [comment]
In progress
