### ISSUE TITLE
Bug in multi lane headways utility function in flow/core/vehicles.py

### ISSUE THREAD

**Issue by J93T** [flow-project/flow#116]
When computing the leaders on a multi lane, sometimes vehicles are left out.  If there is just one vehicle in front of the rl_vehicle on another lane, the index would be zero and therefore the condition in line 1159 is not satisfied, although a leader was found. 
I suggest removing the -1 in this line and check below, if there is at least one vehicle behind the rl_vehicle when checking the rl_vehicles lane.

**Comment by eugenevinitsky** [comment]
Thanks for catching this! We're looking into this ASAP and have assigned someone to check it out.

**Comment by AboudyKreidieh** [comment]
actually, turns out the solution needs to take into account if you are in the same lane as the current vehicle as well (since `bisect_left` collects the index of >= and not >). The PR is up on #150 for those who are interested to see it

**Comment by eugenevinitsky** [comment]
PR for this @J93T is up; let us know if it resolved your issue so we can close this! Hope it helped.

**Comment by J93T** [comment]
Yes, everything is working fine now. Thanks a lot!
