### ISSUE TITLE
Error while running sumo/sugiyama.py

### ISSUE THREAD

**Issue by lucfisc** [flow-project/flow#131]
Hi, 
I don't know what happend but I am having trouble with flow right now. What use to work doesn't anymore.
I 'm going to try to find out about that error but if anyone knows.
```
Warning: Cannot find local schema '/Users/username/flow/bin/data/xsd/types_file.xsd', will try website lookup.```

**Comment by cathywu** [comment]
Could this be a result of the new SUMO quick install? @Aboudy Kreidieh
<aboudy@berkeley.edu>

**Comment by lucfisc** [comment]
@cathywu I don't really know, the installation process worked yesterday. We are trying to inquire the issue with @kjang96

**Comment by lucfisc** [comment]
My error seems to be link with sumo installation : '
~/flow
Installing sumo tools
sumotools-0.1.0-py3-none-any.whl is not a supported wheel on this platform.'

Actually it is the last line of the binary that doesn't work which is weird. Pip installing from the terminal seems to do the trick

**Comment by AboudyKreidieh** [comment]
hmm, maybe the file is failing right before it hits the final line. @lucfisc can you share the last part of the log from when u run `scripts/setup_sum_osx.sh`?

**Comment by lucfisc** [comment]
Connexion à akreidieh.s3.amazonaws.com (akreidieh.s3.amazonaws.com)|52.219.28.6|:443… connecté.
requête HTTP transmise, waiting for response… 200 OK
Size : 5636384 (5,4M) [application/x-xz]
Sauvegarde en : « binaries-mac.tar.xz »

binaries-mac.tar.xz 100%[===================>]   5,38M  15,2MB/s    ds 0,4s    

2018-09-07 17:56:50 (15,2 MB/s) — « binaries-mac.tar.xz » sauvegardé [5636384/5636384]

~/flow
Installing sumo tools
sumotools-0.1.0-py3-none-any.whl is not a supported wheel on this platform.

**Comment by AboudyKreidieh** [comment]
okay, looking into this now. one solution may be to add the sumotools wheel to the setup instructions, which i'm a bit reluctant to do as long as the original sumo setup instructions are still around. 

One quick question, are u running `source activate ~/.bash_profile` before u try the sugiyama experiment? I added it to the sh file, but apparently that doesn't do anything. (apologies if it seems like a stupid question, i just want to exhaust all options)

**Comment by AboudyKreidieh** [comment]
@lucfisc can u pull master and try again now? If this doesn't work, we'll move to 2)

**Comment by lucfisc** [comment]
@AboudyKreidieh 
Still doing the same thing

Trying 2 tonight

**Comment by lucfisc** [comment]
@AboudyKreidieh  Just did it and lead to the same thing

**Comment by AboudyKreidieh** [comment]
as in u tried adding the sumotools wheel to `setup.py` and it didn't work?

**Comment by lucfisc** [comment]
@eugenevinitsky , yes I have no idea about how  to move the sumotools wheel to setup.py.

**Comment by lucfisc** [comment]
@AboudyKreidieh do you have some time to try this ?

**Comment by AboudyKreidieh** [comment]
@lucfisc PR #149 might resolve this. can you give it a go and let me know what happens?

**Comment by lucfisc** [comment]
It does !
