### ISSUE TITLE
Regression tests for benchmarks

### ISSUE THREAD

**Issue by eugenevinitsky** [flow-project/flow#140]
We need to know that our benchmarks are not being broken by upgrades; the only way to do so is to test them regularly to see they hit maximum value and are not generating degenerate solutions (like traffic only flowing in one direction on grid). 

- [ ] cron job to run selected benchmarks on AWS
- [ ] visualization of results

**Comment by kjang96** [comment]
TODO assign ethan

**Comment by kjang96** [comment]
Due 9/22

**Comment by eugenevinitsky** [comment]
This is actually done.
