### ISSUE TITLE
Build script for sumo wheels

### ISSUE THREAD

**Issue by eugenevinitsky** [flow-project/flow#144]
We currently have SUMO wheels that are fixed to specific versions that were installed with brew. If the version that brew install changes, things likely break. We need to be able to
- autobuild the wheels and update the version sitting on s3
- be able to do this every day or every week

**Comment by eugenevinitsky** [comment]
One way out of this might be just trying to put all the "brew install" commands into the environment.yml file!

**Comment by mtgibson2014** [comment]
I'm currently asking SUMO developers to create wheels for SUMO.
