### ISSUE TITLE
Run Flow in CNN mode

### ISSUE THREAD

**Issue by eugenevinitsky** [flow-project/flow#155]
We should have a standard way to run a given environment in pixel mode so that we can try to apply CNN like algorithms to any flow problem. By this I mean
- Either a way to directly get the pixels out of the GUI or
- A method that converts the state to 0' and 1's indicating the presence of a car

**Comment by eugenevinitsky** [comment]
#156 is relevant here

**Comment by fywu85** [comment]
Resolved at #261
