### ISSUE TITLE
Clarify tensorboard setup

### ISSUE THREAD

**Issue by kev-chien** [flow-project/flow#158]
On the [setup page](https://flow.readthedocs.io/en/latest/flow_setup.html#c-testing-your-installation-ray-rllib) for testing ray/rllib, tensorboard is mentioned as a command to use without mentioning that it has to be installed or how to install it.

![tensorboard](https://user-images.githubusercontent.com/20323625/45774392-a429eb80-bc01-11e8-94b3-9b568cd81191.png)

Possible solution is to add a line after that says "If tensorboard is not installed, run `pip install tensorboard`"

**Comment by eugenevinitsky** [comment]
Thanks for catching this! We'll add it to the environment file.

**Comment by eugenevinitsky** [comment]
Or....you could submit your first Pr fixing this!
