### ISSUE TITLE
Clarify boost setup for Ray for Mac

### ISSUE THREAD

**Issue by kev-chien** [flow-project/flow#159]
When installing Ray from Eugene's repo in Mac, I ran into the issue of needing to install boost before I could run `python setup.py develop` (I got the `fatal error: 'boost/algorithm/string/predicate.hpp' file not found`).

Boost is not mentioned in Eugene's repo [Ray installation deps ](https://github.com/eugenevinitsky/ray/blob/master/doc/source/installation.rst) or in the official [Ray installation deps](https://ray.readthedocs.io/en/latest/installation.html)

`brew install boost` did not work as brew does not have a formula for Boost 1.6.5, and any other version led to some missing files.

For me to install Boost I had to download Boost 1.6.5, unzip it, and manually place the "boost" folder into my `/usr/local/include/` folder. I got the version number from [this setup script for boost in the ray repo](https://github.com/ray-project/ray/blob/master/thirdparty/scripts/build_boost.sh)

So perhaps we could clarify the above steps, and write a script to automate the process? Also when I tried to run the above setup script for boost it didn't install boost correctly for me, and I'm not sure how it's actually used and for what.

**Comment by AboudyKreidieh** [comment]
this should no longer be an issue since we install ray from pip
