### ISSUE TITLE
Upgrade to SUMO 1.0.1

### ISSUE THREAD

**Issue by eugenevinitsky** [flow-project/flow#163]
- [x] Change TRACI commands to adapt to new SUMO @AboudyKreidieh 
- [x] Upgrade the RLlib image to use new SUMO @eugenevinitsky
- [x] Build new wheels @AboudyKreidieh  
- [ ] Upgrade the docker image to use new sumo @lucfisc 
- [ ] Confirm that experiments do not crash under new SUMO @eugenevinitsky 
- [ ] Get benchmark results for new SUMO

**Comment by AboudyKreidieh** [comment]
This is redundant, so removing.
