### ISSUE TITLE
brew: command not found

### ISSUE THREAD

**Issue by binderwang** [flow-project/flow#17]
When install flow in Ubuntu, 
./scripts/setup_sumo_osx.sh <DESIRED_PATH_TO_SUMO> # installs sumo
./setup_sumo_osx.sh: line 4: brew: command not found

**Comment by dimikout3** [comment]
You dont have "brew" command installed. "Brew" is mainly used on OSX (it can also be used in Ubuntu, bit i don't recommend it), I suggest using the classic "sudo apt-get install " command for installing the needed libraries (which are : Caskroom/cask/xquartz autoconf automake pkg-config libtool gdal proj xerces-c fox )

**Comment by eugenevinitsky** [comment]
Closing this issue. Thanks @dimikout3 and if this isn't resolved @binderwang please let us know.
