### ISSUE TITLE
Close google groups -- add instructions for asking questions on github issues/add a question label

### ISSUE THREAD

**Issue by eugenevinitsky** [flow-project/flow#174]

**Comment by mtgibson2014** [comment]
Hey,

For this issue, I wanted to create an auto reply to people who post to the group. Here's the message that I'd create:

_Thank you for sending your message to flow-dev. For any issues, questions, or concerns about Flow, we ask that you please submit your issues to our Github repo here: https://github.com/flow-project/flow/issues

Have a great day,
Flow Team_

However, only administrators can make automatic responses. Also, the questions label here is created.
