### ISSUE TITLE
Setup commands in ray_autoscale.yaml

### ISSUE THREAD

**Issue by kjang96** [flow-project/flow#178]
Line 80 of scripts/ray_autoscale.yaml is `- cd ray && git fetch eugene_upstream && git checkout master && git pull`. At this moment, git pull pulls the original repo: ray-project/ray, which (correct me if I'm wrong) is not the desired effect . We should either specify `git pull eugene_upstream master` or set the upstream to be eugene_upstream master.

@eugenevinitsky

**Comment by AboudyKreidieh** [comment]
just checked on this and it is outdated/resolved, so closing
