### ISSUE TITLE
Make a Flow Logo

### ISSUE THREAD

**Issue by kjang96** [flow-project/flow#19]
- clover
- ask jerome

**Comment by berkeleyflow** [comment]
Some proposed options: 
<img width="538" alt="capture d ecran 2018-08-24 a 18 16 37" src="https://user-images.githubusercontent.com/38776306/44690759-e0a66500-aa10-11e8-9357-d611ba8023bc.png">
<img width="541" alt="capture d ecran 2018-08-24 a 18 16 26" src="https://user-images.githubusercontent.com/38776306/44690760-e0a66500-aa10-11e8-8a90-816cc8677254.png">
<img width="541" alt="capture d ecran 2018-08-24 a 18 16 19" src="https://user-images.githubusercontent.com/38776306/44690761-e13efb80-aa10-11e8-96b5-876e3659a08b.png">
<img width="541" alt="capture d ecran 2018-08-24 a 18 16 12" src="https://user-images.githubusercontent.com/38776306/44690762-e13efb80-aa10-11e8-832e-50537796ca26.png">
<img width="544" alt="capture d ecran 2018-08-24 a 18 16 04" src="https://user-images.githubusercontent.com/38776306/44690763-e13efb80-aa10-11e8-9e9f-84de8a2f7d95.png">
<img width="544" alt="capture d ecran 2018-08-24 a 18 15 58" src="https://user-images.githubusercontent.com/38776306/44690765-e13efb80-aa10-11e8-976a-8a8b7f1f9ea1.png">
<img width="537" alt="capture d ecran 2018-08-24 a 18 15 41" src="https://user-images.githubusercontent.com/38776306/44690767-e13efb80-aa10-11e8-9647-60933b1bc41a.png">

**Comment by eugenevinitsky** [comment]
![image](https://user-images.githubusercontent.com/7660397/45339255-b0c79780-b5a2-11e8-831f-46b1e42847ab.png)

**Comment by cathywu** [comment]
Flower network:

![image](https://user-images.githubusercontent.com/329117/45340168-5e5a8c80-b54a-11e8-9106-5d262b0341ba.png)

[Source](https://www.gettyimages.com/detail/photo/aerial-image-of-the-cloverleaf-interchange-high-res-stock-photography/82258564)

**Comment by fywu85** [comment]
![flowgo](https://user-images.githubusercontent.com/8881002/45342910-27897400-b554-11e8-80f9-88d7d777e471.png)

Less is more!

**Comment by eugenevinitsky** [comment]
@fywu85 just to get an idea of the underlying design, this is trying to construct Flow into the shape of a car?

**Comment by eugenevinitsky** [comment]
![image](https://user-images.githubusercontent.com/7660397/45343839-16bc1b00-b5b3-11e8-82f4-636cc23a7ba3.png)

**Comment by cathywu** [comment]
I love it!
-- 
Best wishes,
Cathy

**Comment by fywu85** [comment]
@eugenevinitsky Yes! Basically, 
![car](https://user-images.githubusercontent.com/8881002/45373220-b376bc80-b5a3-11e8-879f-7e95a590e610.jpg)

**Comment by cathywu** [comment]
@Eugene Vinitsky <vinitsky.eugene@gmail.com> This is one possibility!

[image: flow-cloverleaf.png]

**Comment by harryprince** [comment]
I think flow sketch can look like this:
<img width="709" alt="screen shot 2019-02-03 at 8 33 41 am" src="https://user-images.githubusercontent.com/5362577/52170942-c4141300-278e-11e9-8bf4-095beabe386d.png">
