### ISSUE TITLE
get_follower and get_leader occasionally returns wrong value

### ISSUE THREAD

**Issue by kjang96** [flow-project/flow#194]
Discovered this bug in the roundabout_inflows branch of my fork, where rl_0's follower was set as 'rl_3.0' when it clearly was not the follower. I think this was an error with traci. Will flesh out more details later

**Comment by eugenevinitsky** [comment]
Can you point to a file where the error is thrown or add a test for it? (the latter is post the 17th obviously)

**Comment by eugenevinitsky** [comment]
@kjang96 bump, if this is a significant bug we need to know where it is happening.

**Comment by eugenevinitsky** [comment]
@kjang96 bump. Can you point to where this happens?

**Comment by AboudyKreidieh** [comment]
This is stale, closing unless someone is experiencing it now.

**Comment by eugenevinitsky** [comment]
I'd like to reopen this, if this is a bug we need to track it. The minute @kjang96 gets back we can close it if it's actually stale.
