### ISSUE TITLE
specify_routes with a netfile

### ISSUE THREAD

**Issue by CaioFerreiraB** [flow-project/flow#197]
Hello, I'm trying to use the NetFileScenario class, and I discovered that the specify_routes function of the netfile generator is not implemented yet on the version that I have installed. Have you implemented it already? If not, do you have any prevision on when will you implement it?

By the way, thank you for the framework, it was exactly what I was looking for!

**Comment by eugenevinitsky** [comment]
Hi CaioFerreiraB,
Glad you like the framework! Unfortunately, the route specification is something that is scenario specific, so we can't tell what qualifies as a route without knowing the scenario. If you have your net.xml file, we can try and help you write that function for your scenario. For an example, take a look at the BayBridgeTollGenerator class or any of the other generator classes! They all have an implementation of specify_routes in them.

**Comment by CaioFerreiraB** [comment]
Hi eugenevinitsky,
Thank you for the fast response! I implemented the route specification and the specify_edge_start function, the simulation starts, but I', having troubles on the departure positions of the vehicles, I think that I didn't fully understand how the position o the specify_edge_start works because is based on a referential.

**Comment by eugenevinitsky** [comment]
Hi CiaoFerreiraB,

So, the edge starts is sort of a holdover from older things we used to do, if you just return the names of the edges and some random numbers it should be sufficient. The idea was to construct a notion of absolute position, but this doesn't really make sense for most road networks.

**Comment by CaioFerreiraB** [comment]
Hi eugenevinitsky,

Ok, so now I'm a little confused about the implementation. I'm the following problem: the departure position of some of the vehicles are in positions outside of the lane, so I'm not being able to put all the vehicles inside the lane and the simulation ends up with an error. I was thinking that it was due to the specify edges, but apparently not. Any thoughts about what can be the problem?

**Comment by AboudyKreidieh** [comment]
Hi CiaoFerreiraB,

Can you share your `specify_edge_starts` and `specify_specify_routes` methods, as well as anything else you may thing may be leading to the bug? That'd help us work through the problem with you. If you are not comfortable sharing your code, can you at least share the error log? Thank you!

**Comment by eugenevinitsky** [comment]
Hi Ciao,

Looking into it now.

**Comment by eugenevinitsky** [comment]
Hi Ciao,

The generated routes.txt file you sent us doesn't quite match the run script I'm seeing in your github repo but, from what I'm seeing, it looks like you're trying to put 22 vehicles into the system? However, the edges are only of length 40 and so you can't fit all 22 vehicles into that system even if you were to squeeze them as tightly as possible.
Is it possible that you want an inflow of vehicles into the system? If so, you might want to look at https://github.com/flow-project/flow/blob/master/tutorials/tutorial09_inflows.ipynb for a tutorial on how to use inflows. We're also happy to help debug further if that doesn't clear things up.

**Comment by CaioFerreiraB** [comment]
Hi eugenevinitsky

Sorry, I didn't mention, the file that I'm using for my tests is test_netfile.py, so I'm not using the run method on screenshot_test.py (this is the run script that you was talking about, right?). Yes, I was trying to put 22 vehicles into the system, it was a mistake. But even with just 2 vehicles, I'm having this warning on sumo:

Warning: Invalid departPos 54.63 given for vehicle 'idm_1'. Inserting at lane end instead.
Warning: Invalid departPos 32.80 given for vehicle 'idm_1'. Inserting at lane end instead.

After the warning and sumo put the vehicle on the end of the lane, the simulation is initiated, but when the first vehicle passes through the junction and get the next lane of the route,  flow sent me the following error on terminal:

Loading configuration... done.
Traceback (most recent call last):
  File "test_netfile.py", line 48, in <module>
    exp.run(1, 1500)
  File "/home/Caio/flow/flow/core/experiment.py", line 112, in run
    state, reward, done, _ = self.env.step(rl_actions(state))
  File "/home/Caio/flow/flow/envs/base_env.py", line 437, in step
    self.vehicles.update(vehicle_obs, id_lists, self)
  File "/home/Caio/flow/flow/core/vehicles.py", line 345, in update
    change = env.scenario.get_x(this_edge, this_pos) - prev_pos
  File "/home/Caio/flow/flow/scenarios/base_scenario.py", line 246, in get_x
    return self.total_edgestarts_dict[edge] + position
KeyError: 'L0'

I tried to add the start of the edge L0 on the specify_edge_starts, but then it creates a routeL0, which is not specified. Should I specifie it in other way? Again, I'm sending you the GitHub link and the files containing the rou.xml and add.xml file that flow generated.

https://github.com/CaioFerreiraB/TrafficBayesianDDQN

About the inflow, not sure if it's what I'm looking for. I just want the vehicles to be able to cross the junction. The inflows should be used when we want to merge lanes, right?

Thank you again for all the help.
[generated_addxml_file.txt](https://github.com/flow-project/flow/files/2495511/generated_addxml_file.txt)
[generated_rouxml_file.txt](https://github.com/flow-project/flow/files/2495512/generated_rouxml_file.txt)

**Comment by CaioFerreiraB** [comment]
Hello again, 

After looking at the flow's code, I solved my problem. I was having some issues with controllers and how flow works. 

Really thank you for all the help and congratulations on a great job with the framework!

**Comment by eugenevinitsky** [comment]
Great! Glad to hear it. Just for point of reference, an inflow would let you stochastically send vehicles on the start of each edge, so that you could keep a steady flow of vehicles going towards the junctions. That way you don't have to put all the vehicles on to start and will have more vehicles coming in at a stochastic rate.

I'm going to close the issue, but if you have any other questions or issues occur again please open another one!
