### ISSUE TITLE
Rllib example fails due to worker failure on cluster

### ISSUE THREAD

**Issue by liyan2015** [flow-project/flow#233]
---
name: rllib example `stabilizing_the_ring.py` have worker failures on cluster
about: SUMO socket error

---

**Choose an option**
This is a: 
- [ ] Question

**Describe the issue**
SUMO subprocess receives socket error randomly, which causes several workers to fail.

**To Reproduce**
1. Start a Ray cluster with 3 nodes. Each node has 28 workers. Let each worker have 1 CPU.
2. Configure the `num_workers` in `stabilizing_the_ring.py` to be 3*28. 
3. Run the experiment on the cluster. Worker failures usually happen at between 30th and 100th iterations. For example:

```
The worker with ID 593b7a4f35a1983edabbdd41585949b94cbfd7e5 died or was killed while executing the task with ID 7a7bf13e5b23edf3a70025ddce28c75b1043fb9a
The worker with ID c48514021f95b8d2917381c085c55f3cd8e756cf died or was killed while executing the task with ID c82618cbc7eff856b9f071383b0f0b30602390b5
Remote function train failed with:

Traceback (most recent call last):
  File "/af1/ly4ss/anaconda2/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/af1/ly4ss/anaconda2/envs/flow/lib/python3.5/site-packages/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/af1/ly4ss/anaconda2/envs/flow/lib/python3.5/site-packages/ray/rllib/agents/agent.py", line 235, in train
    return Trainable.train(self)
  File "/af1/ly4ss/anaconda2/envs/flow/lib/python3.5/site-packages/ray/tune/trainable.py", line 143, in train
    result = self._train()
  File "/af1/ly4ss/anaconda2/envs/flow/lib/python3.5/site-packages/ray/rllib/agents/ppo/ppo.py", line 123, in _train
    fetches = self.optimizer.step()
  File "/af1/ly4ss/anaconda2/envs/flow/lib/python3.5/site-packages/ray/rllib/optimizers/multi_gpu_optimizer.py", line 102, in step
    self.train_batch_size)
  File "/af1/ly4ss/anaconda2/envs/flow/lib/python3.5/site-packages/ray/rllib/agents/ppo/rollout.py", line 31, in collect_samples
    next_sample = ray.get(fut_sample)
  File "/af1/ly4ss/anaconda2/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 2522, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(7b7bf13e5b23edf3a70025ddce28c75b1043fb9a). It was created by remote function <unknown> which failed with:

Remote function <unknown> failed with:

Invalid return value: likely worker died or was killed while executing the task.

Error processing event.
Traceback (most recent call last):
  File "/af1/ly4ss/anaconda2/envs/flow/lib/python3.5/site-packages/ray/tune/trial_runner.py", line 239, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/af1/ly4ss/anaconda2/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 200, in fetch_result
    result = ray.get(trial_future[0])
  File "/af1/ly4ss/anaconda2/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 2522, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(6e557221b804e4a50d70ea4ef999854fdf40b323). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/af1/ly4ss/anaconda2/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 945, in _process_task
    *arguments)
  File "/af1/ly4ss/anaconda2/envs/flow/lib/python3.5/site-packages/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/af1/ly4ss/anaconda2/envs/flow/lib/python3.5/site-packages/ray/rllib/agents/agent.py", line 235, in train
    return Trainable.train(self)
  File "/af1/ly4ss/anaconda2/envs/flow/lib/python3.5/site-packages/ray/tune/trainable.py", line 143, in train
    result = self._train()
  File "/af1/ly4ss/anaconda2/envs/flow/lib/python3.5/site-packages/ray/rllib/agents/ppo/ppo.py", line 123, in _train
    fetches = self.optimizer.step()
  File "/af1/ly4ss/anaconda2/envs/flow/lib/python3.5/site-packages/ray/rllib/optimizers/multi_gpu_optimizer.py", line 102, in step
    self.train_batch_size)
  File "/af1/ly4ss/anaconda2/envs/flow/lib/python3.5/site-packages/ray/rllib/agents/ppo/rollout.py", line 31, in collect_samples
    next_sample = ray.get(fut_sample)
  File "/af1/ly4ss/anaconda2/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 2522, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(7b7bf13e5b23edf3a70025ddce28c75b1043fb9a). It was created by remote function <unknown> which failed with:

Remote function <unknown> failed with:

Invalid return value: likely worker died or was killed while executing the task.
```

4. Ray's local scheduler log shows whenever some SUMO socket errors happened, the worker fails. 
**Scheduler log shows some SUMO socket errors happened at 23:29**
![2018-11-11_002913](https://user-images.githubusercontent.com/10633479/48309700-89169080-e54d-11e8-98f9-e61c7cd467a6.png)
**Ray generated error logs at 23:29**
![2018-11-11_003242](https://user-images.githubusercontent.com/10633479/48309703-a186ab00-e54d-11e8-9853-6f8c4aaa975d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 14.04.5 LTS
 - Commit number of flow 5449dd3cdbe15295cc45262583360ac88b92d8a9
 - Version 0.2.0

**Additional context**
It seems that the port set in `base_env.py` (i.e., `port = sumolib.miscutils.getFreeSocketPort()`) is not always available, which might be the problem source when there are multiple worker processes competing for the same port accidentally. But I cannot find a better way for port validation. Is there something like "port lock"? Any hint is appreciated!

**Comment by eugenevinitsky** [comment]
Hi @liyan2015 , I'm surprised that this is happening. I'll try and validate it ASAP; each worker is assigned a unique port number so if it doesn't fail immediately it shouldn't fail at any point. 
There are two recommendations/requests that I have while we try and debug this:
(1) Ray actually assigns one worker per CPU so I'm surprised your script ran; the number of workers should be the number of possible CPUs - 1. If you're trying to get multiple envs running per workers, you may want to set config['num_envs_per_worker'] > 1 but I have not played with this and am unsure. Can you set the `num_workers=NUM_CPUS - 1` and see if the same error still occurs?
(2) Ray actually outputs giant error logs that have the true error further up, can you attach the full error log?
(3) Those SUMO socket errors are actually normally printed by SUMO when you close the socket so I'm suspicious that socket errors are actually not what's happening here.

In the meantime, can you attach your exact run script? I'm running it with the instructions you suggested but I want to make sure I reproduce your error exactly.

Hope we can figure this out quickly!

Eugene

**Comment by liyan2015** [comment]
Thank you for your quick recommendations!

(1) I use `ray start --head --redis-port=6379` to start the head on the first node, and then `ray start --redis-address=<head ip>` to start the slave nodes. By `NUM_CPUS`, I guess you mean the total number of CPUs on the cluster? I once tried to use `NUM_CPUS=3*28-1=83` CPUs as workers and left 1 CPU as the scheduler, but no difference. I also tried to decrease this value to be lower than the total number of actual available CPUs on the cluster (e.g., the cluster has totally 3*28=84 CPUs, but I only used 8 CPUs from each node as workers), but the error still happens. I am not using multiple envs right now. Since the original `stabilizing_the_ring.py` example only uses 2 workers, I changed some configuration settings. Please see the attached code.

(2) Please see attached.
[liyan2015.zip](https://github.com/flow-project/flow/files/2569701/liyan2015.zip)


I have checked the `ulimit -n 65536` and `OMP_NUM_THREADS=1` for each node, so it is not caused by OS open file limit. From the logs I have, it seems to be SUMO that causes some worker to die.

**Comment by eugenevinitsky** [comment]
@liyan2015 oh my goodness, I don't know why I didn't get notified about your response. I'm looking into this ASAP. So sorry!

**Comment by eugenevinitsky** [comment]
So, the logs are slightly deceptive; for stabilizing_the_ring we change the size of the ring every instance. To do this, we have to close and open a traci connection. When you close a traci connection on sumo 0.31.0 it outputs the error that you're seeing. 
Could you post the full log? It's really hard to debug rllib errors without the log and I don't have access to a multi-node cluster at the moment.

**Comment by eugenevinitsky** [comment]
So, the logs are slightly deceptive; for stabilizing_the_ring we change the size of the ring every instance. To do this, we have to close and open a traci connection. When you close a traci connection on sumo 0.31.0 it outputs the error that you're seeing. 
Could you post the full log from the terminal? It's really hard to debug rllib errors without the terminal log and I don't have access to a multi-node cluster at the moment to reproduce the error (though I will try to set one up now and test this)

**Comment by eugenevinitsky** [comment]
Hi @liyan2015 I am testing it out now on a cluster, should have a response for you soon.

**Comment by eugenevinitsky** [comment]
Hm, it is working for me on the cluster. 
Are you sure that your ray.init(redis_address="") winds up printing out the correct address on the cluster? Which version of ray are you running?

**Comment by eugenevinitsky** [comment]
If you want to send me your public key, I can add you to the cluster so you can mess around on it and see what might be going wrong.

**Comment by eugenevinitsky** [comment]
One more question, does this script work for you locally on one node?

**Comment by AboudyKreidieh** [comment]
this PR is stale, closing
