### ISSUE TITLE
Upgrade Sumo

### ISSUE THREAD

**Issue by eugenevinitsky** [flow-project/flow#236]
- [x] Write a run script to run all the benchmarks, pull and visualize them @kanaadp 
- [ ] Pick out the correct parameters for new SUMO
- [ ] Pick out inflow values for bottleneck with Krauss
- [ ] Confirm wave on merge even with Krauss
- [ ] Write script to check that the results are within expectation on traffic metrics

**Comment by AboudyKreidieh** [comment]
this has been moved to a different tracking document, so closing here
