### ISSUE TITLE
Calculation of v_max in stabilizing ring environments outputs negative results

### ISSUE THREAD

**Issue by eugenevinitsky** [flow-project/flow#237]
In the stabilizing ring experiments, if you fix the ring radius to be 230, the output max speed is -1.7. This doesn't seem correct?

**Comment by CYBruce** [comment]
@eugenevinitsky May I ask why to set the ring radius between 210 and 270 in the `stabilizing_the_ring.py` instead of a fixed value? And usually how long does it takes to run the code to terminate in a PC? Because I have ran it for 4 hrs but it hasn't ended.
