### ISSUE TITLE
visualizer_rllib opens multiple windows

### ISSUE THREAD

**Issue by eugenevinitsky** [flow-project/flow#240]
If you look at the calls made from running visuallizer_rllib (ignoring the num_clients thing) you see the following: 

eugenevinitsky   44840   0.0  0.1  4399572  16864   ??  Ss    7:21PM   0:00.06 sumo -c /Users/eugenevinitsky/Desktop/Research/Bayen/Code/flow/flow/scenarios/debug/cfg/to_visualize_20181113-1921531542165713.870879.sumo.cfg --remote-port 62314 --num-clients 1 --step-length 0.1 --no-step-log --time-to-teleport -1
eugenevinitsky   44837   0.0  0.1  4364356  11384   ??  Ss    7:21PM   0:00.03 sumo -c /Users/eugenevinitsky/Desktop/Research/Bayen/Code/flow/flow/scenarios/debug/cfg/to_visualize_20181113-1921481542165708.217882.sumo.cfg --remote-port 62312 --num-clients 2 --step-length 0.1 --no-step-log --emission-output ./test_time_rollout/to_visualize_20181113-1921481542165708.217882-emission.xml --time-to-teleport -1
eugenevinitsky   44826   0.0  0.1  4384212  16644   ??  Ss    7:21PM   0:00.07 sumo -c /Users/eugenevinitsky/Desktop/Research/Bayen/Code/flow/flow/scenarios/debug/cfg/to_visualize_20181113-1921431542165703.222323.sumo.cfg --remote-port 62301 --num-clients 1 --step-length 0.1 --no-step-log --time-to-teleport -1
eugenevinitsky   44780   0.0  2.1 114223720 355164 s005  S+    7:21PM   0:14.74 python visualizer_rllib.py /Users/eugenevinitsky/ray_results/to_visualize/PPO_AccelEnv-v0_0_2018-11-13_15-57-288zh31ejh 1 --num_rollouts 10 --sumo_web3d --no_render

Why is it opening three windows like this?!

**Comment by AboudyKreidieh** [comment]
this was recently resolved by #788
