### ISSUE TITLE
Functional dockerized version of Flow w/ frozen version of ray and instructions for use

### ISSUE THREAD

**Issue by eugenevinitsky** [flow-project/flow#243]
We should have a dockerized version of Ray that can be used for the Flow tutorial

**Comment by AboudyKreidieh** [comment]
@fywu85 did you meet with @ashkan-software and update the setup instructions in the website?

**Comment by fywu85** [comment]
Not yet. Sorry, I was not aware of this. Will check this with Ashkan right now.

**Comment by AboudyKreidieh** [comment]
@fywu85 checking on this again. Can we close?

**Comment by fywu85** [comment]
Sorry about the slow reply. Still working on it. Will close this ASAP.

**Comment by fywu85** [comment]
Closure pending #560.
