### ISSUE TITLE
Failed to run examples/sumo/sugiyama.py

### ISSUE THREAD

**Issue by dimikout3** [flow-project/flow#290]
I followed the steps for the installation procedure (https://berkeleyflow.readthedocs.io/en/latest/flow_setup.html). However, when i tried to run the example 
 ( in the "Testing the Installation" section) I get the following error:

Traceback (most recent call last):
  File "examples/sumo/sugiyama.py", line 11, in <module>
    from flow.envs.loop.loop_accel import AccelEnv, ADDITIONAL_ENV_PARAMS
  File "/home/dkoutras/flow/flow/envs/__init__.py", line 4, in <module>
    from flow.envs.multiagent_env import MultiEnv
  File "/home/dkoutras/flow/flow/envs/multiagent_env.py", line 10, in <module>
    from ray.rllib.env import MultiAgentEnv
ModuleNotFoundError: No module named 'ray'

I have not installed the ray library, but as mentioned in the corresponding section I sould not need it anyway. Any ideas ?

**Comment by eugenevinitsky** [comment]
Thank you for catching and reporting this! This is a dependency we did not intend to introduce. I will push a fix to this this afternoon and let you know when it is up but if you want to quickly resolve it you can run:
Pip install ray==0.5.3 and then
Pip install opencv-python.
That should resolve the dependencies issue.

**Comment by eugenevinitsky** [comment]
PR #291 is out in response to this @dimikout3 . Hope this resolves your problem!

**Comment by dimikout3** [comment]
Thanks !!! your quick fix did work. The gui starts normally, however, when i hit the run traci fails with the following error:
Error: tcpip::Storage::readIsSafe: want to read 8 bytes from Storage, but only 4 remaining
Quitting (on error).

I have faced the same issue in older sumo releases. Could you possible know what is going on ?

**Comment by eugenevinitsky** [comment]
Ah; yes. We are currently operating on an old version of SUMO and are working (this week and next) to upgrade to SUMO 1.0.1. In our scripts folder you can find the setup scripts that will install a compatible version of SUMO for you if you want it.

**Comment by dimikout3** [comment]
Thanks again for the help. I tried the scripts as you proposed and I have two comments:

1. I believe there is a typo in your "setup_sumo_ubuntu1604.sh".  The last two lines are 
echo 'export PATH=$PATH:$HOME/sumo_binaries/bin' >> ~/.bashrc
echo 'export SUMO_HOME=$HOME/sumo_binaries/bin' >> ~/.bashrc
I think you wanted to use something like:
echo 'export PATH="$PATH:$HOME/sumo_binaries/bin" ' >> ~/.bashrc
echo 'export SUMO_HOME="$HOME/sumo_binaries/bin" ' >> ~/.bashrc
2. Same think still happens. Sumo-gui is starting normally and when i start the simulation by hitting the run button, traci fails to connect.

**Comment by dimikout3** [comment]
Sumo-gui logs the following message:

Error: tcpip::Storage::readIsSafe: want to read 8 bytes from Storage, but only 4 remaining
Quitting (on error).

**Comment by eugenevinitsky** [comment]
Yeah; it looks like your Traci isn't updated yet. We're writing a PR to simplify the process but in the meantime, did you follow the instruction to run `python setup.py develop` in the main flow directory?

**Comment by dimikout3** [comment]
I deleted the  first conda enviroment and created a knew one (after using the scripts for installing sumo-binaries). I still get the same error.

**Comment by eugenevinitsky** [comment]
If you run `python -c "python import traci; print(traci.__path__)` what do you get? We will figure this out soon!

**Comment by dimikout3** [comment]
python -c "python import traci; print(traci.__path__)"
  File "<string>", line 1
    python import traci; print(traci.__path__)
                ^
SyntaxError: invalid syntax

**Comment by eugenevinitsky** [comment]
err; just try running `python` and then once you're in the python command line 
`import traci
print(traci.__path__)
`
Just trying to figure out which traci you actually wind up pointing at. My guess is that the newer version of Traci is still getting imported.

**Comment by dimikout3** [comment]
['/home/dimikout3/sumo/tools/traci']

**Comment by eugenevinitsky** [comment]
Have you reset it? i.e. `source ~/.bashrc`
You can also just do this by closing the terminal window.

**Comment by dimikout3** [comment]
I did not (omg!!). After reseting importing traci fails. In other words, if i open a python command line an type "imoprt traci" i get: 
Traceback (most recent call last):
  File "examples/sumo/sugiyama.py", line 10, in <module>
    from flow.core.vehicles import Vehicles
  File "/home/dimikout3/flow/flow/core/vehicles.py", line 12, in <module>
    import traci.constants as tc
ImportError: No module named 'traci'

If i echo $SUMO_HOME now i get /home/dimikout3/sumo_binaries/bin

**Comment by eugenevinitsky** [comment]
So here we install traci via pip so it should just be in your env; so I would get into your conda env and run `python setup.py develop` one more time and see if that fixes things?

**Comment by dimikout3** [comment]
I did run run python setup.py develop. In my python command line I can see that traci is importred from 
['/home/dimikout3/anaconda3/envs/flow/lib/python3.5/site-packages/traci']. However, when i run the example i still get the traci error ...

**Comment by dimikout3** [comment]
I have finally located the problem !!! I was wrongly exporting the sumo/bin ... instead of 
echo 'export PATH="$HOME/sumo/bin:$PATH"' >> ~/.bashrc    in my ~/.bashrc I had 
echo 'export PATH=$HOME/sumo/bin:$PATH' >> ~/.bashrc
After correcting this I just needed to install the pip install ray==0.5.3 and the pip install opencv-python. Now everything seems to perform correctly. I also believe that the wrong path was creating the error in the sumo-binaries implementation (though I can not be completely sure). 
Thanks for your help !!! Keep up the good work !!

**Comment by eugenevinitsky** [comment]
Glad to hear it! I'm going to close this issue but let us know if you have any more questions!

**Comment by KidTrunks** [comment]
Hi, unfortunately I am also having problems running "python examples/sumo/sugiyama.py"

The error I encounter is:

Couldn't import TensorFlow - disabling TensorBoard logging.
Traceback (most recent call last):
  File "examples/sumo/sugiyama.py", line 11, in <module>
    from flow.envs.loop.loop_accel import AccelEnv, ADDITIONAL_ENV_PARAMS
  File "/home/python/flow/flow/envs/__init__.py", line 13, in <module>
    from flow.envs.loop.loop_accel import AccelEnv
  File "/home/python/flow/flow/envs/loop/loop_accel.py", line 5, in <module>
    from flow.envs.multiagent_env import MultiEnv
  File "/home/python/flow/flow/envs/multiagent_env.py", line 10, in <module>
    from ray.rllib.env import MultiAgentEnv
  File "/home/python/anaconda3/lib/python3.7/site-packages/ray/rllib/__init__.py", line 11, in <module>
    from ray.rllib.evaluation.policy_graph import PolicyGraph
  File "/home/python/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/__init__.py", line 2, in <module>
    from ray.rllib.evaluation.policy_evaluator import PolicyEvaluator
  File "/home/python/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 8, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

Any help solving this issue will be greatly appreciated!

**Comment by dimikout3** [comment]
Did you try:
pip install ray==0.5.3 and then
pip install opencv-python .

I think I had the same error when i did not use the aforementioned commands. Also, do not forget to activate the conda flow environment you have created (It is possible to encounter the same error if you do not activate your environment).

**Comment by KidTrunks** [comment]
Yes I had the same issue No Module named 'ray' before this, and applied your fix which solved the problem. But this error No module named 'tensorflow' occured right after.

**Comment by dimikout3** [comment]
And I am assuming you tried " source ~/.bashrc " or closing and reopening the terminal, for enabling the changes. I remember the error you are mentioning, but in my case the 2 pip installations fixed the problem. Just to make sure, you performed the installations while the conda flow environment was activated ?

**Comment by eugenevinitsky** [comment]
Hi @dimikout3 thank you for helping!

@KidTrunks sorry for the delay; did you create a flow environment and ran `source activate flow` before running anything? You're missing tensorflow and tensorboard which should have been installed in the conda install.

**Comment by KidTrunks** [comment]
YESSS it worked!!! Thank you @dimikout3  @eugenevinitsky , very silly mistake by me.

**Comment by eugenevinitsky** [comment]
No worries! Glad we could help you.

**Comment by cathywu** [comment]
I think this may still be an issue? Without ray install, I see the following error on `master`:
```
$ python examples/sumo/sugiyama.py
Traceback (most recent call last):
  File "examples/sumo/sugiyama.py", line 11, in <module>
    from flow.envs.loop.loop_accel import AccelEnv, ADDITIONAL_ENV_PARAMS
  File "flow/envs/__init__.py", line 13, in <module>
    from flow.envs.loop.loop_accel import AccelEnv
  File "flow/envs/loop/loop_accel.py", line 5, in <module>
    from flow.envs.multiagent_env import MultiEnv
  File "flow/envs/multiagent_env.py", line 10, in <module>
    from ray.rllib.env import MultiAgentEnv
ImportError: No module named 'ray'
```

**Comment by eugenevinitsky** [comment]
I think it might be worthwhile just to add ray to the environment.yml. It slows the setup down by seconds. There isn't actually a reason right now for people to use our custom version of Ray except internally.

**Comment by AboudyKreidieh** [comment]
The dependency is somewhat resolved and another issue is up for adding ray to the environment.yml file

**Comment by xiaoToby** [comment]
Hi:
I also met that similar problem.
source /Users/xiaohongzhi/anaconda3/bin/activate
(base) wlan-napt-002:aimsun xiaohongzhi$ source /Users/xiaohongzhi/anaconda3/bin/activate
conda activate aimsun_flow
(base) wlan-napt-002:aimsun xiaohongzhi$ conda activate aimsun_flow
(aimsun_flow) wlan-napt-002:aimsun xiaohongzhi$ python sugiyama.py 
Traceback (most recent call last):
  File "sugiyama.py", line 6, in <module>
    from flow.controllers import IDMController
ImportError: No module named flow.controllers

How to fix that?
Hurry....

**Comment by Yasharzf** [comment]
HI Xiao, You need to activate flow (not aimsun_flow).

**Comment by xiaoToby** [comment]
Hi Yasharzf 
I follow your advice.
the result is the same.

**Comment by xiaoToby** [comment]
Hi Yasharzf
I follow your advice.
the result is the same.


I am using macOS and visual studio code.
Except that:
 also followed the official tutorial to exercise.
On the tutorial_1 I met problems again, the error log is below:








*Traceback (most recent call last):  File "tutorial_1.py", line 9, in
<module>    from flow.envs.loop.loop_accel import AccelEnv  File
"/Users/xiaohongzhi/flow/flow/envs/__init__.py", line 2, in <module>
from flow.envs.base_env import Env  File
"/Users/xiaohongzhi/flow/flow/envs/base_env.py", line 39    class
Env(*classdef):              ^SyntaxError: invalid syntax*

Best regards
Yashar Zeinali Farid <notifications@github.com> 于2019年6月25日周二 下午2:20写道：

**Comment by xiaoToby** [comment]
I tried your method on the terminal.
It looks ok, and the aimsun is automatically opened, but i didn't see any
special on the aimsun.
[image: 屏幕快照 2019-06-25 下午3.44.32.png]
There is something wrong?

肖鸿治 <xiaohongzhi0603@gmail.com> 于2019年6月25日周二 下午3:14写道：

**Comment by Yasharzf** [comment]
Ah, unfortunately Aimsun is now broken. It will be fixed this ASAP. Please follow issue #551

**Comment by xiaoToby** [comment]
By the way.
I tried to reinstall all the software(Flow, SUMO, Rlib, Aimsun) by following the instructions on the websites(https://flow.readthedocs.io/en/latest/flow_setup.html#)

When I tried to install sumo, there is an error:
failed to open 'binaries-mac.tar.xz'

I check the official website of SUMO, about Download part, now we can download it except Windows.
So, there are any other ways to go on to use FLOW.

**Comment by sanakdag** [comment]
Hi I'm having a similar issue initializing a tutorial.
Seems to think that opencv is in python2?
any thoughts on why this is happening?

Traceback (most recent call last):
  File "examples/sumo/sugiyama.py", line 11, in <module>
    from flow.envs.ring.accel import AccelEnv, ADDITIONAL_ENV_PARAMS
  File "/home/airlab/Desktop/RL-Traffic-Lights/flow/flow/envs/__init__.py", line 2, in <module>
    from flow.envs.base import Env
  File "/home/airlab/Desktop/RL-Traffic-Lights/flow/flow/envs/base.py", line 10, in <module>
    from flow.renderer.pyglet_renderer import PygletRenderer as Renderer
  File "/home/airlab/Desktop/RL-Traffic-Lights/flow/flow/renderer/__init__.py", line 3, in <module>
    from flow.renderer.pyglet_renderer import PygletRenderer
  File "/home/airlab/Desktop/RL-Traffic-Lights/flow/flow/renderer/pyglet_renderer.py", line 7, in <module>
    import cv2
ImportError: /opt/ros/kinetic/lib/python2.7/dist-packages/cv2.so: undefined symbol: PyCObject_Type
