### ISSUE TITLE
Name conflict for bottleneck

### ISSUE THREAD

**Issue by yunerzxy** [flow-project/flow#296]
**Choose an option**
This is a: 
- [ ] Question
- [ ] Feature request
- [x] Bug report

**Describe the issue**
There's a bottleneck package in pandas, and conflicts with our bottleneck class.

**To Reproduce**
Leave empty if not applicable.
Try to run any example files

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/13002156/49321450-67f5ef80-f4bc-11e8-810a-1df0ee725858.png)

**Desktop (please complete the following information):**
 - OS: macos
 - Commit number of flow [run git log and copy the commit number]
 - Version [run python -c "import flow; print(flow.__version__)"]: 0.3.0
 Leave empty if not applicable.

**Additional context**

**Comment by AboudyKreidieh** [comment]
resolved
