### ISSUE TITLE
Clip tuples in base_env

### ISSUE THREAD

**Issue by eugenevinitsky** [flow-project/flow#302]
We clip the actions passed from the RL agent but only clip if the action_space is a box. If the action space is a tuple we should still be clipping.

**Comment by fywu85** [comment]
@eugenevinitsky This is the default design in gym (see [here](https://github.com/openai/gym/blob/master/gym/spaces/tuple_space.py)). When you were referring to _clipping a tuple_, what type of behavior do you want to impose? If you could provide a spec detailing the exact inputs and outputs, I am happy to implement it!

**Comment by fywu85** [comment]
Closure pending #685
