### ISSUE TITLE
There are always errors in OSX following Installing procedure

### ISSUE THREAD

**Issue by CYBruce** [flow-project/flow#304]
**Choose an option**
This is a: 
- [x] Question

**Describe the issue**
When coming to the Installing Flow and SUMO, after downloading SUMO’s github directory, something goes wrong and I cannot figure it out.

I input the code into terminal
`export CPPFLAGS=-I/opt/X11/include`
`export LDFLAGS=-L/opt/X11/lib`
`./configure CXX=clang++ CXXFLAGS="-stdlib=libc++ -std=gnu++11" --with-xerces=/usr/local --with-proj-gdal=/usr/local`
`make -j$nproc`
But I got
`MacBook-Pro-3:sumo mac$ make -j$nproc`
`make: *** No targets specified and no makefile found.  Stop.`
I have tried many times and dont know why

**Comment by eugenevinitsky** [comment]
@CYBruce sorry to hear about this! I'm guessing something went wrong in the ./configure line; could you post the output for this?
Additionally, we've added some instructions to make the installation process way easier! 
You can take a look at: https://flow.readthedocs.io/en/latest/flow_setup.html#e-easy-install-sumo-optional
for a hopefully much simpler process.

**Comment by CYBruce** [comment]
I tried this easier method, but still have errors. I cannot make SUMO work. 
[terminal_rec.txt](https://github.com/flow-project/flow/files/2660336/terminal_rec.txt)

**Comment by CYBruce** [comment]
By the way, I tried the (e). Easy Install SUMO, and I got this.
`Installing sumo binaries`
`~/sumo_binaries/bin ~/flow`
`scripts/setup_sumo_osx.sh: line 11: wget: command not found`
`tar: Error opening archive: Failed to open 'binaries-mac.tar.xz'`
`rm: binaries-mac.tar.xz: No such file or directory`
`chmod: *: No such file or directory`

**Comment by eugenevinitsky** [comment]
Of course; happy to help. The issue here is that you don't have wget. 
Can you try first installing homebrew from this link: https://brew.sh/
Then run `brew install wget` and then repeat the easy setup procedure? I think this will resolve your problems.

**Comment by CYBruce** [comment]
@eugenevinitsky Thank you for your kindly help! I fixed the problem and installed sumo_binary. However, when I tried to install sumo (I install all the needed libraries)
`export CPPFLAGS=-I/opt/X11/include`
`export LDFLAGS=-L/opt/X11/lib`
`./configure CXX=clang++ CXXFLAGS="-stdlib=libc++ -std=gnu++11" --with-xerces=/usr/local --with-proj-gdal=/usr/local`  They work correctly.
Unfortunately, `make -j$nproc` gives an error

> clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [marouter] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

**Comment by eugenevinitsky** [comment]
Hi @CYBruce if you install the binaries, you can skip the sumo install step! You already have the binaries so everything should work as is. Highly recommended that you do this.

However, if you do want to go forward and actually do the compilation, happy to help with that as well. Unfortunately, to debug this I need the full output of make -j$nproc as the actual error is much further up in the output.

**Comment by CYBruce** [comment]
Wow, that's cool! Thank you for your help!

**Comment by eugenevinitsky** [comment]
Great! Are you able to get any of the examples to work?

**Comment by CYBruce** [comment]
when i input `sumo-gui`
it returns`FXApp::openDisplay: unable to open display /private/tmp/com.apple.launchd.uA1b5HgRU2/org.macosforge.xquartz:0`

and i input `python: can't open file 'examples/rllib/stabilizing_the_ring.py': [Errno 2] No such file or directory`
Now i'm trying to find answer online

**Comment by eugenevinitsky** [comment]
Okay; so as to the former make sure you've closed and opened XQuartz; that's probably all that is.

As for the latter, what directory are you running it from? I'm guessing you're running it from a directory where the path to sugiyama.py is not `examples/sumo/sugiyama.py`

**Comment by CYBruce** [comment]
I solved the latter one, but the former problem.......
I am still trying, it seems closing and opening dont work

**Comment by eugenevinitsky** [comment]
You may have to restart your computer if you've installed XQuartz for the first time.

**Comment by CYBruce** [comment]
Finally!!!
I will do some experiments in the next stage!

**Comment by eugenevinitsky** [comment]
So glad to hear it! I'm closing this issue for now then but let us know if anything else comes up. Excited to see what you build with Flow!

**Comment by xiaoToby** [comment]
> Of course; happy to help. The issue here is that you don't have wget.
> Can you try first installing homebrew from this link: https://brew.sh/
> Then run `brew install wget` and then repeat the easy setup procedure? I think this will resolve your problems.

Now I installed the wget.
But I still get that question.
Why? Please help
