### ISSUE TITLE
ImportError: No module named traci

### ISSUE THREAD

**Issue by CYBruce** [flow-project/flow#305]
Sorry for the problem again, I solved the problem yesterday and made __*sugiyama.py*__ run correctly.
However, when I rerun the __*sugiyama.py*__  today, I got another problem saying "No module named traci". I'm sure I activate the source flow. Also I find the 'traci' direptory locally.
<img width="560" alt="2018-12-11 2 24 58" src="https://user-images.githubusercontent.com/34786389/49782296-c474cc80-fd50-11e8-93ec-c44305103f51.png">

**Comment by CYBruce** [comment]
I solved this problem successfully by appending this path into `sys.path`, you can close this problem.

**Comment by eugenevinitsky** [comment]
Glad you solved it!
Just to check, did you install via conda and the setup instructions? Traci should automatically have been added to your conda environment.

**Comment by CYBruce** [comment]
@eugenevinitsky I followed the instructions and succeed. But today when I learning tutorial2, I met an error in the last step (the previous steps work well). Do you have some advice?
<img width="893" alt="2018-12-12 9 19 57" src="https://user-images.githubusercontent.com/34786389/49840613-1e2bd400-fdef-11e8-82d8-bd8d3902ca42.png">

**Comment by eugenevinitsky** [comment]
Oh yeah; so, I'm still not sure if you're successfully creating a conda env. However, this can be resolved by `pip install gym==0.10.5`

**Comment by eugenevinitsky** [comment]
Any error like this can be solved by running pip install <object>=<version> where you should take version from the environment.yml file.

**Comment by CYBruce** [comment]
I got it!

**Comment by CYBruce** [comment]
@eugenevinitsky As you said, I run python` setup.py` develop with flow env activated. But I got `sumotools-0.1.0-py3-none-any.whl is not a supported wheel on this platform.` And I think this is the key reason for `No module named traci`

**Comment by eugenevinitsky** [comment]
Yeah; we use that wheel to install traci. Very odd. @AboudyKreidieh any thoughts why this error might be occurring?

**Comment by CYBruce** [comment]
@AboudyKreidieh PTAL🙌🙌😁

**Comment by AboudyKreidieh** [comment]
@CYBruce sorry I missed this! Are you using python2 when you try to install this? It'll only work on python3 unfortunately (as will the rest of our code as well). Let me know if that's the issue and I'll be sure to respond ASAP! :)

**Comment by CYBruce** [comment]
Thank you so much!!!
It's my mistake using python2 and I have fixed this.

**Comment by AboudyKreidieh** [comment]
Awesome, glad it worked out. Let me know if you run into any other bugs.
