### ISSUE TITLE
Setting up an Environment: lz4 not avaialble

### ISSUE THREAD

**Issue by KidTrunks** [flow-project/flow#306]
Ran into issue while trying to setup the environment using : 
from flow.envs.loop.loop_accel import AccelEnv

the issue: "Warning: lz4 not available, disabling sample compression. This will significantly impact RLlib performance. To install lz4, run 'pip install lz4'"

After running pip install lz4, the same warning message persists.

Currently using Ubuntu 18.04 and Python 3.7.0

Any help would be greatly appreciated,

Thanks.

**Comment by eugenevinitsky** [comment]
Hi @KidTrunks we are working to resolve this now; however, this is a warning rather than an error. The system will still run and I don't believe the speed is particularly affected.

**Comment by KidTrunks** [comment]
@eugenevinitsky Ahhh yes you are right, seems like performance is unaffected. Thought I might be missing something vital. Thanks!

**Comment by KidTrunks** [comment]
@eugenevinitsky Yes it's all good! Thanks!

**Comment by AboudyKreidieh** [comment]
resolved by #300
