### ISSUE TITLE
Tensorflow version requirement

### ISSUE THREAD

**Issue by cathywu** [flow-project/flow#335]
Do we know what tensorflow version is absolutely required at present?

A few notes:
- `tensorflow=1.10.0` (which is the version in the `environment.yml`) is not backwards compatible on OSX 10.11.6 (El Capitan)
- `tensorflow=1.8.0` is missing the `AUTO_REUSE` flag, i.e. `AttributeError: module 'tensorflow' has no attribute 'AUTO_REUSE'`, which is used by PPO in RLlib.
- `tensorflow=1.9.0` is successfully able to run `examples/rllib/stabilizing_the_ring.py` on OSX 10.11.6 (El Capitan)

Any thoughts on what features that are required from `1.10.0`?

@eugenevinitsky @fywu85

**Comment by eugenevinitsky** [comment]
Hm, unclear. Downgrading to 1.9.0 may be fine; we can just put that into the environment and test that it passes on Travis.

**Comment by cathywu** [comment]
Cool, that's a great idea, thanks for the suggestion. I'll do this next
week unless someone gets to it first.

**Comment by AboudyKreidieh** [comment]
resolved by #352
