### ISSUE TITLE
[documentation] move ray cluster usage instructions out of 'local installation' section

### ISSUE THREAD

**Issue by cathywu** [flow-project/flow#336]
Currently the ray cluster usage instructions are hidden in the local install section of our docs. Perhaps move this to the tutorials section. What do you think? @nskh 

![screen shot 2018-12-24 at 4 47 27 pm](https://user-images.githubusercontent.com/329117/50408223-a91baf80-079b-11e9-85b5-243985231da0.png)

**Comment by nathanlct** [comment]
Fixed in #552.
