### ISSUE TITLE
Profile performance

### ISSUE THREAD

**Issue by cathywu** [flow-project/flow#337]
There appears to be a performance hit for very easy examples (like the sugiyama example, where RLlib/tensorflow, etc. are not needed), which takes SUMO a while to load. Any ideas where the slowdown might be? This shouldn't be much slower than running the sumo binary directly. It would be good to profile the performance and see if we are loading extra libraries when they aren't needed.

**Note**: This issue may be confounded with #334.

**Comment by AboudyKreidieh** [comment]
@cathywu the slow-down is because we import ray in `flow/envs/multiagent_env.py`. It's something we need to figure out at some point.
