### ISSUE TITLE
tutorial for running rllab experiments on AWS

### ISSUE THREAD

**Issue by AboudyKreidieh** [flow-project/flow#34]
We have something basic in the docs/ folder, and I think @nskh setup something on berkeleyflow. One thing he pointed out, that I sort of agree on, is that it may be better to have it on readthedocs instead of the tutorials folder, since there isn't really any code to run. Anything to include @nskh (or anyone else)?

**Comment by nskh** [comment]
Yeah - there's a PR out: https://github.com/berkeleyflow/flow/pull/70. I think readthedocs is the right place for this stuff, just cause there's no point in making this harder to access by putting it in a notebook. Let me know (probably in that PR? not sure what our dev workflow is for the new repo) if there's stuff to change.

**Comment by eugenevinitsky** [comment]
Hmmm, I think that makes sense. Our dev workflow is the same, we just need to transfer all the remaining PRs over.

**Comment by AboudyKreidieh** [comment]
the PR has been merged. this is resolved
