### ISSUE TITLE
ES runner script fails to terminate

### ISSUE THREAD

**Issue by fywu85** [flow-project/flow#342]
**Choose an option**
This is a: 
- [ ] Question
- [ ] Feature request
- [x] Bug report

**Describe the issue**
A clear and concise description of what the bug/question/feature request is.
The ES runner script under flow/benchmarks/rllib fails to terminate. @eugenevinitsky 

**To Reproduce**
Leave empty if not applicable.
1. File in which error occurred. 
`flow/benchmarks/rllib/es_runner.py`
2. Exact command that was run that caused the error to occur. 
`git checkout es-debug`
`python flow/benchmarks/rllib/es_runner.py --benchmark_name figureeight0`
3. Please attach the full error output log. 
**Runner script will HANG without printing errors.**

**Expected behavior**
Leave empty if not applicable.

**Screenshots**
Leave empty if not applicable.

**Desktop (please complete the following information):**
 - OS: `ubuntu-18.04`; `ray 0.5.3` and above
 - Commit number of flow [run git log and copy the commit number]
 - Version [run python -c "import flow; print(flow.__version__)"]: 
 Leave empty if not applicable.

**Additional context**
To contrast, this `python ppo_runner.py --benchmark_name figureeight0` will terminate after 80s, as expected.

**Comment by eugenevinitsky** [comment]
Sorry, this is presuming you've set the number of iterations to 1?

**Comment by eugenevinitsky** [comment]
Could you add some more information @fywu85, I can't reproduce this error.

**Comment by fywu85** [comment]
Hey Eugene, thanks for looking into this. Did you checkout the branch `es-debug`? Are you running on `ubuntu` with `ray 0.5.3`?
