### ISSUE TITLE
Supporting pyglet renderer in Aimsun

### ISSUE THREAD

**Issue by AboudyKreidieh** [flow-project/flow#346]
required changes:
- [ ] replace traci calls with generic kernel calls in the renderer
- [ ] add required vehicle methods (e.g. `get_timedetla`, etc...)

**Comment by fywu85** [comment]
@AboudyKreidieh The renderer does not invoke kernel in any way. In fact, all it requires are several lists and params. If you can specify how to add required vehicle methods, I can help with this one.

**Comment by AboudyKreidieh** [comment]
we need to abstract any calls to `traci_connection` to kernel calls, so that similar methods can be implemented with aimsun. Then we will have to implement them in aimsun and see if it works

**Comment by AboudyKreidieh** [comment]
Might be overreaching. Closing this until we actually want it.
