### ISSUE TITLE
Move benchmarks folder outside of flow

### ISSUE THREAD

**Issue by eugenevinitsky** [flow-project/flow#37]
It's sort of confusing that examples is outside the flow folder but benchmarks is inside? Maybe we move both inside or both outside? @AboudyKreidieh

**Comment by eugenevinitsky** [comment]
Mmmm, I see. I'm not sure; it's just a matter of making sure the benchmarks are very visible.

**Comment by cathywu** [comment]
Perhaps we can reference the OpenAI gym structure for this.

**Comment by AboudyKreidieh** [comment]
I just checked. OpenAI gym places there examples in a folder outside of gym, and their environments are located in gym/envs. If we wanted to follow their structure, I don't think we would have to change anything.

**Comment by cathywu** [comment]
Thanks for checking, Aboudy! Eugene, what do you think? One perspective:
Only "devs" will want to change the benchmarks, and they will know to look
inside the flow directory. Other users who are just using the benchmarks
will likely benefit from the intuitive "flow.benchmarks" import statement.

**Comment by AboudyKreidieh** [comment]
@eugenevinitsky what are your thoughts on this? Personally, I'm happy sticking with our current setup

**Comment by AboudyKreidieh** [comment]
This issue is stale, so closing. I think we're happy with things as is for now. If anyone disagrees, they can reopen it.
