### ISSUE TITLE
Logfile to analyze the behavior of an agent

### ISSUE THREAD

**Issue by MouvementMondial** [flow-project/flow#374]
I'd like to better understand why a trained agent acts the way he does. My idea is to use a log file (similar to SUMO's emission-xml). In addition to the SUMO file, this file should contain the following data:

- desired action (acceleration and lane change) of each trained agent for each time step
- action actually performed
- observations etc

I think my trained agent is taking advantage of the fail-safe functions and does not learn his taks properly..

Has anyone already written such an output function? If I wrote one, the environment (base_env or a special one) is probably the best place, isn't it?

**Comment by eugenevinitsky** [comment]
Hi @MouvementMondial, we don't exactly have such a function but we have something very close. If you are using rllib the file is flow/visualize/visuallizer_rllib.py and if you are using rllab it is  flow/visualize/visuallizer_rllab.py. You pass it a checkpoint (if rllib) and can use it to replay the agent. It doesn't currently record all the actions and write them to file but you can extend it to do so. There's a tutorial on these files in the tutorial folder.
Alternately, you may want to log the actions while the training process is preceeding. In that case, yeah, you'd have to log it in base_env though writing a logging class that interacts with base_env is probably the cleanest solution. If you'd like to contribute this, it'd be appreciated!
Can't wait to see what you're using Flow for.

**Comment by MouvementMondial** [comment]
Hey, thanks for the quick answer! I already looked at the visuallizer_rllib.py file, but missed the crucial loop. I think I can solve it quickly with this approach. Thank you very much!

I think I don't need the evaluation for the training. Most of the time I use C++, i.e. a clean logging class would be difficult for me ;)

As a first attempt I tried to build the _[DeepTraffic](https://selfdrivingcars.mit.edu/deeptraffic/)_ task with FLOW. 

If you're interested, _[this](https://youtu.be/KLoYcOM3OWg
)_ is one of the first results.

In the meantime I have adapted the LaneChange model and the fail-safes. 

I changed the lane-change-mode from 512 (no_lat_collide) to 768.  As described in the sumo-docs, this should prevent automatic speed adaption. I have set bit9 and bit8 to 11: 

- 11 = respect the speed / brake gaps of others when changing lanes, no speed adaption
instead of
- 10 = respect the speed / brake gaps of others when changing lanes, adapt speed to fulfill request

Thank you very much for your offer of help!

**Comment by eugenevinitsky** [comment]
Oh, this is so great! We were just talking amongst the team about the DeepTraffic task but didn't realize that it could be so cleanly implemented in Flow. 
So, a few points to check that may be causing issues here:
1. Are you sure the training has converged? It's possibly not done after 120 iterations. It's worth looking at your reward curve to see if it has flattened out.
2. What speed mode does the AV have on?
3. It's possible that setting it to 768 may cause the nearby vehicles to not act as co-operatively as they might, i.e. they don't adapt their speed to fulfill the request. I'm not 100% sure about this behavior though, do you know @AboudyKreidieh ?

**Comment by MouvementMondial** [comment]
1) 120 iterations of 20 episodes each. I think this is rather too much

![reward](https://user-images.githubusercontent.com/26592985/50841690-8b3a7700-1365-11e9-9473-0657c1604904.png)

2) no_collide

3) That's exactly the behavior I was trying to achieve.

Have you ever tried to turn off all the safety functions and train them?

**Comment by eugenevinitsky** [comment]
Oh yeah, that looks converged. So yes, we have turned off all the safety checks and trained it before! You may very well want to do this; the training will take a bit longer but you'll probably get a good deal closer to the results you want. Given how fast it is converging anyways (20 iterations!) it shouldn't be too bad.

**Comment by AboudyKreidieh** [comment]
hi @MouvementMondial I'm marking this as resolved, but if you have any more concerns with regards to this please feel free to reopen to create a new issue
