### ISSUE TITLE
Using pedestrians along with vehicles

### ISSUE THREAD

**Issue by ndeshp2s** [flow-project/flow#383]
Hello,

I have started using SUMO and FLOW for RL. I have a scenario consisting of pedestrians and vehicles.
SO I wanted to know if its possible to create a new scenario with pedestrians as well in FLOW.

Thank you.

**Comment by AboudyKreidieh** [comment]
Hi @ndeshp2s we do not currently have functionality for adding pedestrians, and do not specifically plan on incorporating it some time in the near future. However, if you are interesting in contributing the codebase we would definitely be open to collaborating with you on this! Adding pedestrians will likely be something that needs to be added via the scenario class, similar to inflows and the nodes/edges of the graph. If you are open to looking into this I'd be happy to work through what needs to be done with you.

**Comment by rohanchandra30** [comment]
I have a related question: Suppose we have defined the dynamics for a new agent, say a motorbike, how can we add the visual graphics for its icon in the GUI? TO put bluntly, how can one get a picture of motorbikes (or any other different agent) in the simulator GUI ? 

Would appreciate any help :)

Thanks

**Comment by AboudyKreidieh** [comment]
hi @rohanchandra30 sumo let's you update the path to the image file used by the vehicles, which is not a feature that we currently support but is an easy addition if you are interested in us adding. As far as something more quick and dirty, you can set the colors of individual vehicles, as we do in many of the environments to distinguish between automated, visible to the agent, and unseen by the agent. You can do this from an environment by using the command `self.k.vehicle.set_color` (see [here](https://github.com/flow-project/flow/blob/master/flow/core/kernel/vehicle/traci.py) for the implementation)
