### ISSUE TITLE
Visualizer not working due to argparse

### ISSUE THREAD

**Issue by kjang96** [flow-project/flow#394]
**Choose an option**
This is a: 
- [ ] Question
- [ ] Feature request
- [x] Bug report

**Describe the issue**
I'm guessing this is an issue with argparse. The default value for args.render_mode is 'sumo-gui', yet the code doesn't hit the conditional case that sets `sim_params.render = True`. From the ipdb debugger, when you run `p(args.render_mode)`, (all this is is a print function) it prints 'sumo-gui,' as expected. When you run `args.render_mode`, it gives you a Namespace object. It seems like this is why the condition `args.render_mode == 'sumo_gui'` isn't registering as True.

**To Reproduce**
Leave empty if not applicable.
1. visualizer_rllib.py
2. python visualizer_rllib.py [arbitrary figure eight experiment ran for this specific purpose]

**Expected behavior**
Running args.render_mode should return 'sumo-gui', or some valid string, rather than a Namespace object.

**Screenshots**
Leave empty if not applicable.

**Desktop (please complete the following information):**
 - OS: OSX 
 - Commit number of flow [run git log and copy the commit number]: b4eafc2986d0da3581cfff1be5fc2ecf402f6136
 - Version [run python -c "import flow; print(flow.__version__)"]: 0.3.0
 Leave empty if not applicable.

**Additional context**

**Comment by MouvementMondial** [comment]
Argparse works. The argument has been overwritten. I have created a pull-request.
