### ISSUE TITLE
Error with commandline when running examples/sumo/sugiyama.py

### ISSUE THREAD

**Issue by KidTrunks** [flow-project/flow#395]
Versions:
Ubuntu 16.04
Python 3.5

Problem: 
The following error codes occur after running examples/sumo/sugiyama.py

Loading configuration... done.
Success.
Error: On processing option '--num-clients':
 No option with the name 'num-clients' exists.
Error: The parameter '1' is not allowed in this context.
 Switch or parameter name expected.
Error: On processing option '--collision.check-junctions':
 No option with the name 'collision.check-junctions' exists.
Error: The parameter 'true' is not allowed in this context.
 Switch or parameter name expected.
Error: Could not parse commandline options.
Quitting (on error).
Could not connect to TraCI server at localhost:51587 [Errno 111] Connection refused
 Retrying in 1 seconds
Could not connect to TraCI server at localhost:51587 [Errno 111] Connection refused

The sumo gui pops up with the above error codes. Flow had already been activated with 'source activate flow.' Any help would be appreciated.

Thanks!

**Comment by JeanUCD** [comment]
Hi, I met the same problem, have you figured it out?

**Comment by KidTrunks** [comment]
Hi @JeanUCD,

Not yet unfortunately. Please let me know if you figure anything out.

Thanks.

**Comment by AboudyKreidieh** [comment]
Hi all, thank you for bringing this up. I will look into it and get back to you ASAP.

**Comment by AboudyKreidieh** [comment]
Doing some quick research, one issue might be that the sumo version is too out-of-date: 

```

**Comment by KidTrunks** [comment]
Thanks for your help. Here is my sumo version:

SUMO Version 0.25.0
 Copyright (C) 2001-2015 DLR and contributors; http://sumo.dlr.de
 License GPLv3+: GNU GPL Version 3 or later <http://gnu.org/licenses/gpl.html>
 Use --help to get the list of options.

**Comment by AboudyKreidieh** [comment]
Hey, yes that seems to be the issue. Certain options we are calling are only available for sumo version from 0.31.0 and above. I would recommend following our setup instructions to get the current sumo version on your local machine.

Link to setup instructions: https://flow.readthedocs.io/en/latest/flow_setup.html

**Comment by AboudyKreidieh** [comment]
glad to hear it! let us know if you run into any other issues

**Comment by xiaoToby** [comment]
Now 
I ran that program.
I get an error: want to read 4 bytes from Storage, but only 3 remainning.
How to fix it?
BTW, my sumo version is 0.32.0

**Comment by jingyanping** [comment]
i meet the same problem, so i want to know how to update the sumo.
BTW:i use ubuntu 14.4
        python 3.7(it is possible to use python3.7?)
        sumo 0.19.0
THANKS!

**Comment by jingyanping** [comment]
Error: tcpip::Storage::readIsSafe: want to read 8 bytes from Storage, but only 4 remaining
The TraCI protocal changed in version 1.0.0. 
Please make sure that TraCI client version and SUMO version match. @xiaoToby 


i met the same problem，
I ran that program.
I get an error: want to read 4 bytes from Storage, but only 3 remainning.
How to fix it? i don't know how to change TRACI version
BTW, my sumo version is 0.32.0
