### ISSUE TITLE
Add Bicycle and Parking Area Support

### ISSUE THREAD

**Issue by harryprince** [flow-project/flow#399]
Wish flow enable bike sharing simulation.

* http://sumo.dlr.de/wiki/Simulation/Bicycles
* https://github.com/lcodeca/PyPML

**Comment by AboudyKreidieh** [comment]
hi @harryprince sorry I missed this! I've been looking through the github repository you shared, and it seems that this could probably be coupled with the kernel abstractions in Flow to support the relevant features, although it would not be trivial as there is some overlap between our API and the one presented here. If you are interested in discussing how this could be done, I can share my thoughts with you. Let me know!

**Comment by harryprince** [comment]
Thanks, I found Lara's job, which builds some citywide vehicle parking scenarios.

*  https://github.com/lcodeca/MoSTScenario
* https://github.com/lcodeca/LuSTScenario

**Comment by AboudyKreidieh** [comment]
hi @harryprince, interestingly enough we had been working on these (at least LuST) in the past. To my recollection, the integration was very close to complete. I will talk to some people and see what the progress was on this. More very soon!
