### ISSUE TITLE
sumo-1.1.0 traci changes

### ISSUE THREAD

**Issue by zihao0821** [flow-project/flow#421]
[ Bug report ]
The latest sumo-1.1.0 have modified traci-server, which results in errors when running flow. 

The code "flow/core/kernel/vehicle/traci.py".
In line 98: vehicle_obs = self.kernel_api.vehicle.getSubscriptionResults()
When running demos, it will report "TypeError xxx" and quit.
When I change line 98 into "vehicle_obs = self.kernel_api.vehicle.getAllSubscriptionResults()", then it's fine.
Same problem in "flow/core/kernel/traffic_light/traci.py".

Is that a bug, or flow has not been updated for sumo-1.1.0?

**Comment by AboudyKreidieh** [comment]
hi @zihao0821 the master branch does not currently support sumo 1.1.0; however, there is a PR in the works to remedy this (see the branch `new_sumo_pr`). Feel free to use this in the meantime, as we are actively trying to resolve this PR and will have it merge hopefully within the next week or two
