### ISSUE TITLE
Incorrect traffic_light initialization in green_wave_env.py

### ISSUE THREAD

**Issue by FarshadKoohifar** [flow-project/flow#422]
**Choose an option**
This is a: 
- [ ] Question
- [ ] Feature request
- [x] Bug report

**Describe the issue**
In [green_wave_env.py](https://github.com/flow-project/flow/blob/master/flow/envs/green_wave_env.py), line 101:
```
            for i in range(self.rows * self.cols):
                self.k.traffic_light.set_state(
                    node_id='center' + str(i), state="GGGrrrGGGrrr")
``` 
This assumes three traffic lights per edge, which is not correct. Running this results in three green lights in on three edges and one red light which is clearly not intended. Should be changed to 'grgr'.

**Comment by AboudyKreidieh** [comment]
hi @FarshadKoohifar thanks for the catch! I'll create a PR about this now
