### ISSUE TITLE
Unidentified warnings when using bottleneck. Feature request for description

### ISSUE THREAD

**Issue by pnp91** [flow-project/flow#433]
After training the Bottle neck scenario, I have few doubts in understanding and analyzing. If someone could help me understand, it would be highly appreciated. I encountered some warnings and it took so much time to start the training. During this time, it was giving warnings as follows:
--------------------------------------------------------------------------
Warning: Vehicle 'flow_0.111' ends teleporting on edge '4', time 274.00.
Loading configuration... done.
Success.
Loading configuration... done.
Warning: Invalid departPos 296.00 given for vehicle 'rl_4'. Inserting at lane end instead.
Warning: Teleporting vehicle 'rl_0'; collision with vehicle 'flow_0.27', lane=':4_0_2', gap=-1.00, time=114.00 stage=move.
Warning: Vehicle 'rl_0' ends teleporting on edge '4', time 114.00.
Loading configuration... done.
Success.
Loading configuration... done.
Warning: Invalid departPos 296.00 given for vehicle 'rl_4'. Inserting at lane end instead.
Warning: Teleporting vehicle 'flow_0.141'; collision with vehicle 'flow_0.144', lane=':4_0_1', gap=-1.00, time=357.80 stage=move.
Warning: Vehicle 'flow_0.141' ends teleporting on edge '5', time 357.80.
Loading configuration... done.
Success.
Loading configuration... done.
Warning: Invalid departPos 296.00 given for vehicle 'rl_4'. Inserting at lane end instead.
Warning: Teleporting vehicle 'flow_0.91'; collision with vehicle 'flow_0.82', lane=':4_0_3', gap=-1.00, time=230.20 stage=move.
----------------------------------------------------------------------------------------
Could some one please explain how are the collisions happening and how can I avoid these collisions? Also, second question, in bottle neck, there are no 'rl' vehicles added. Then how is there warning telling "Invalid departPos for 'rl_4' ". From where is this warning coming and how can I verify it.

Also, I would appreciate if some documentation help would be there. Given descriptions are not enough for understanding. Especially regarding parameters and features.

Finally, Where are the rewards being calculated( I have seen compute_rewards function but didn't find it's implementation/calling usage in examples) and how can I give my own rewards?

Any help regarding these 4 questions is sincerely thanked.

**Comment by AboudyKreidieh** [comment]
hi @pnp91 I'll create an issue about adding some more documentation to the bottleneck environment and see if we can resolve it in the next few days. As for the first issue, @eugenevinitsky do you know how to prevent collisions in this network?

**Comment by AboudyKreidieh** [comment]
as an update, I started documented and testing some of the features in this environment in PR #437, but unfortunately do not know too much about this environment. Will try to assign this to someone soon
