### ISSUE TITLE
Env cannot signal the end of a run.

### ISSUE THREAD

**Issue by FarshadKoohifar** [flow-project/flow#442]
**Choose an option**
This is a: 
- [ ] Question
- [x] Feature request
- [ ] Bug report

**Describe the issue**
Environments that inherit from Env, should be able to indicate that they have reached the end of their simulation time line. 
For instance, consider a situation in which I am simulating the peak hour. After that period is over, I do not want to continue simulation, and intend to raise "done" in the return parameters of gym environment's step.
As it stands, Env has decided not to let me do it, and return done as true only in the case of a crash.

**Comment by eugenevinitsky** [comment]
Hi @FarshadKoohifar, would it just be sufficient to set the horizon to be the length that you want?

**Comment by FarshadKoohifar** [comment]
Hi @eugenevinitsky,
Which horizon? I am referring to [Env](https://github.com/flow-project/flow/blob/master/flow/envs/base_env.py) that does not have any clean way to return done as True. 
I had to override the whole step() and add this at the end:
```done = crash or self.steps < self.time_counter```
Are you referring to the same Env?

**Comment by AboudyKreidieh** [comment]
hi @FarshadKoohifar I created a PR to resolve this. see #457

**Comment by FarshadKoohifar** [comment]
Thanks.
