### ISSUE TITLE
Only one route is allowed from any given starting edge

### ISSUE THREAD

**Issue by FarshadKoohifar** [flow-project/flow#443]
In the [base_scenario.py](https://github.com/flow-project/flow/blob/master/flow/scenarios/base_scenario.py), it is mentioned:

> Currently, only one route is allowed from any given starting edge.

I need to have vehicles that start from the same edge, be able to turn either way when they come to an intersection. I assume this is a popular feature, so please let me know what is the reason for this prohibition and how I can contribute to solve it.

**Comment by AboudyKreidieh** [comment]
hi @FarshadKoohifar you can specify different routes from the same starting edge by using a routing class, see: https://github.com/flow-project/flow/blob/master/flow/controllers/routing_controllers.py

One example of multiple routes originating from the same edge can be seen in `BayBridgeRouter`, where the route from lanes 2 on edge "183343422" is supposed to be different from the default.

**Comment by FarshadKoohifar** [comment]
Thanks a lot!
