### ISSUE TITLE
Do you have another docker image available in China?

### ISSUE THREAD

**Issue by happybyr** [flow-project/flow#446]
Well , I want to use flow to do some research. I try to pull the docker image as you write in your doc. But it often stop and no longer pull in the middle of the process. I try many times but still fail. I try to install in my own computer but it invoke so many problem that I can't sovle. So did you have another docker image available in China? Or a virtual machine file that already installed all the  tool?

**Comment by fywu85** [comment]
Hi @happybyr, for now, you may try to build the docker image using [this](https://github.com/flow-project/flow/blob/docker_0.3.0/Dockerfile), which is a part of #450.

**Comment by happybyr** [comment]
Thank you so much. I have install the Flow successful. Another question ,I run the tutorial_03,  I modify the source code to call the "sumo-gui",  but it often stop run in 50.1s and must be restarted,  I want to see the further behavior or the car.Fow example, extends the simulation time to 300s.  So which parameter should I modify? I just can't find it. I have tryed the 'horizon' and some other parms but didn't work.
