### ISSUE TITLE
Relax dependencies in requirements.txt

### ISSUE THREAD

**Issue by fywu85** [flow-project/flow#448]
**Choose an option**
This is a: 
- [ ] Question
- [x] Feature request
- [ ] Bug report

**Describe the issue**
A clear and concise description of what the bug/question/feature request is.
Should we relax dependencies in requirements.txt from `==` to `>=`?

**To Reproduce**
Leave empty if not applicable.
1. File in which error occurred. 
2. Exact command that was run that caused the error to occur. 
3. Please attach the full error output log. 

**Expected behavior**
Leave empty if not applicable.

**Screenshots**
Leave empty if not applicable.

**Desktop (please complete the following information):**
 - Commit number of flow [run git log and copy the commit number]
 - Version [run python -c "import flow; print(flow.__version__)"]: 
 Leave empty if not applicable.

**Additional context**

**Comment by AboudyKreidieh** [comment]
We talked about this offline. My thought is as long as it is not affecting anything negatively, we stick to our current setup.
