### ISSUE TITLE
Load sumo.cfg file

### ISSUE THREAD

**Issue by Exorcismus** [flow-project/flow#462]
is it possible to load a network using a sumo.cfg file ?
as my network has route files (route.rou.xml) and additional files (addFile.add.xml)

**Comment by AboudyKreidieh** [comment]
hi @Exorcismus in regards to your comment, Flow does allow you to import custom .net.xml files, but we have not previously implemented methods to add sumo.cfg files as well. Are the route and additional files used similar to the ones we generate? If so, there may be a quick fix for this. Feel free to share your files (or snippets of them) if you'd like to me check!

**Comment by Exorcismus** [comment]
Hi @AboudyKreidieh , thanks for your answer, here is a snippet of my additional files

`<additional>

<tlLogic id="Bank-Albert" type="static" programID="AM Peak" offset="55">
        <phase duration="21"  state="rrrGGGG"/>
        <phase duration="5"   state="rrryyyy"/>
        <phase duration="29"  state="GGGrrrr"/>
        <phase duration="5"   state="yyyrrrr"/>
    </tlLogic>
	
	
	<tlLogic id="Bank-Albert" type="static" programID="Off Peak" offset="40">
        <phase duration="23" state="rrrGGGG"/>
        <phase duration="5"  state="rrryyyy"/>
        <phase duration="22" state="GGGrrrr"/>
        <phase duration="5"  state="yyyrrrr"/>
    </tlLogic>

<tlLogic id="Bank-Albert" type="static" programID="PM Peak" offset="8">
        <phase duration="20" state="rrrGGGG"/>
        <phase duration="5"  state="rrryyyy"/>
        <phase duration="25" state="GGGrrrr"/>
        <phase duration="5"  state="yyyrrrr"/>
    </tlLogic>
	
	<tlLogic id="Bank-Albert" type="static" programID="Night" offset="26">
        <phase duration="23" state="rrrGGGG"/>
        <phase duration="5"  state="rrryyyy"/>
        <phase duration="22" state="GGGrrrr"/>
        <phase duration="5"  state="yyyrrrr"/>
    </tlLogic>
	
	<tlLogic id="Bank-Albert" type="static" programID="Weekend" offset="40">
        <phase duration="23" state="rrrGGGG"/>
        <phase duration="5"  state="rrryyyy"/>
        <phase duration="22" state="GGGrrrr"/>
        <phase duration="5"  state="yyyrrrr"/>
    </tlLogic>

  <WAUT startProg="0" refTime="0" id="Bank-Albert">
    <wautSwitch to="Night"  	time="900"></wautSwitch>
    <wautSwitch to="AM Peak" 	time="21600"></wautSwitch>
	<wautSwitch to="Off Peak"  	time="34200"></wautSwitch>
	<wautSwitch to="PM Peak" 	time="54000"></wautSwitch>
	<wautSwitch to="Off Peak" 	time="64800"></wautSwitch>
	<wautSwitch to="Night"  	time="81000"></wautSwitch>

  </WAUT>
  
  <wautJunction junctionID="Bank-Albert" wautID="Bank-Albert"></wautJunction>

</additional>
`

**Comment by AboudyKreidieh** [comment]
hi @Exorcismus sorry for the late reply! We've been off here for the past week. From what I'm seeing these files have to do with the traffic light properties. In that case, I would recommend exporting this information from the xml files using something like `lxml` and then passing this data to `TrafficLightParams`. For more on this, see PR #492, where we did this for vehicles

**Comment by AboudyKreidieh** [comment]
Closing this for now. Feel free to reopen if needed!
