### ISSUE TITLE
Error running the Oakland-San Francisco Bay Bridge on Windows

### ISSUE THREAD

**Issue by Exorcismus** [flow-project/flow#463]
can flow run on windows ?
Traci.py throws error in functions `self.sumo_proc = subprocess.Popen(
                    sumo_call, preexec_fn=os.setsid)`
`AttributeError: module 'os' has no attribute 'setsid'`
and so in `killpg`

**Comment by AboudyKreidieh** [comment]
We do not actively support installing our software on windows machines; however, people have installed it using Windows 10's Ubuntu console feature. I would warn though that it tends to be slow, so if you don't want to replace Windows with Ubuntu or duel boot, I'd recommend [creating a virtual machine](https://itsfoss.com/install-linux-in-virtualbox/) and running Flow from there.

**Comment by fywu85** [comment]
@Exorcismus I was able to successfully run `examples/sumo/bay_bridge.py` on my Windows Linux Subsystem (WLS). The command you see is explained [here](https://stackoverflow.com/questions/38083168/attributeerror-module-os-has-no-attribute-setsid). Perhaps you are running this with native Windows python environment? Why not try doing it with WLS if you do not want to duel boot/virtual machine?

**Comment by AboudyKreidieh** [comment]
closing this since it is stale. @fywu85 's comment stands for Windows users
