### ISSUE TITLE
How to implement route.rou.xml in flow

### ISSUE THREAD

**Issue by Exorcismus** [flow-project/flow#464]
how can I simulate/introduce/convert the below line into flow code

```
    <vehicle id="0_0" depart="25200.00">
        <route edges="Kent-Nepean-Gloucester Kent-Gloucester-Laurier Kent-Laurier-Slater Kent-Slater-Albert Kent-Albert-Queen Kent-Queen-Wellington Wellington-Kent-Bank Wellington-Bank-Oconnor Wellington-Oconnor-Metcalfe Wellington-Metcalfe-Elgin Wellington-Elgin-East"/>
    </vehicle>
```

**Comment by AboudyKreidieh** [comment]
hi @Exorcismus this goes back to your previous comment. there is a PR in the works to do something similar. Essentially, in this case we create a route called "route0_0" in the scenario's `specify_routes` method and assign it the aformentioned edges, then use traci's `addFull` method in the environment to add the vehicle with that route at that depart time. If this is a bit unclear, I will try to get the PR that shows this ready in the next few days.

**Comment by Exorcismus** [comment]
in the example, how can I specify the `depart` param, as seen below in the tutorial snippet, I can only assign the edges

`class myScenario(myScenario):  # update my scenario class

    def specify_routes(self, net_params):
        rts = {"edge0": ["edge0", "edge1", "edge2", "edge3"],
               "edge1": ["edge1", "edge2", "edge3", "edge0"],
               "edge2": ["edge2", "edge3", "edge0", "edge1"],
               "edge3": ["edge3", "edge0", "edge1", "edge2"]}

        return rts`

**Comment by AboudyKreidieh** [comment]
hi @Exorcismus, as of PR #492 you can do this by simply specifying the route file under the `template` attribute in `NetParams`. Let me know if you need help with this.

**Comment by AboudyKreidieh** [comment]
the mentioned PR has been merged, so closing. If you are still having issues with this please feel free to reopen this or start a new issue!
