### ISSUE TITLE
specify_routes with an osm file

### ISSUE THREAD

**Issue by DMarcelAM** [flow-project/flow#470]
Hello, 
I'm trying to collect scenario data from an OpenStreetMap file, but I don't know how to get the rts for the specify_routes function from the osm file. How can I do this?

Thank you for your time and the framework, it's great.

**Comment by AboudyKreidieh** [comment]
hi @DMarcelAM sorry for the late reply! The edges can be collecting from the SUMO simulation or from the osm file. I have created a new tutorial on using osm files, and made some modifications to allow it to be simpler to use from scratch. See the new tutorial (tutorial07_osm) in the branch associated with PR #486 for more. This will be merged soon too. Hope it helps!

**Comment by DMarcelAM** [comment]
Hi @AboudyKreidieh, thanks to your tutorial I have my network. The networks comes with some traffic lights but I want to delete some of these and add others. I want to add the traffic lights via TrafficLightParams but I don't know the nodes ID. Could you give some help please?

**Comment by AboudyKreidieh** [comment]
Hi @DMarcelAM I am not sure if you can do it from Flow as of yet, but you can modify the xml file using sumo's `netconvert` method and then run the subsequent xml file in flow (see the tutorial on template files in PR #492)

**Comment by DMarcelAM** [comment]
Thanks for the great idea @AboudyKreidieh . I used sumo's netedit tool based on netconvert method to adjust my network with GUI. Now that I have all the traffic lights I needed, I want to control some of these traffic lights via RL. Should I create a custom enviroment similiar to green_wave_env.py to train some of the traffic lights of my network? Because I want to have both static and RL controlled traffic lights in my network.

**Comment by AboudyKreidieh** [comment]
yes, you will likely need to create a modified version of the green_wave_env.py environment. You may need to change the states and actions to make the names of the traffic lights you are interested in.
