### ISSUE TITLE
RLlib post-training print full command to visualize checkpoint

### ISSUE THREAD

**Issue by kev-chien** [flow-project/flow#471]
**Choose an option**
This is a: 
- [ ] Question
- [x] Feature request
- [ ] Bug report

**Describe the issue**
After training using RLLib, it would be nice to have a command to visualize the results trained outputted/ pretty-printed right after. For instance, "run `python flow/..../visualizer_rllib.py <path in ray_results> 1` to visualize agent training", where the path to ray_results is the correct path to the results just trained. This may help users if they can just directly copy/paste the command to visualize.

**Additional context**
Not sure if internal flow architecture can allow for this change. This also seems like a good first issue / open coding project.

**Comment by fywu85** [comment]
This should not be impossible. I will look into this.

**Comment by CYBruce** [comment]
Visualize the learning curve might be a good option.

**Comment by fywu85** [comment]
@CYBruce Do you know that you can visualize the learning curves using `tensorboard --logdir ~/ray_results`?
