### ISSUE TITLE
Allowing lane change can cause collision in bottleneck environment

### ISSUE THREAD

**Issue by CYBruce** [flow-project/flow#473]
This is a: 
- [x] Question
- [ ] Feature request
- [ ] Bug report

**Describe the issue**
I want to allow cars to change lanes in the bottleneck scenario. 
I have adjusted the lane change mode several times (1621, 256 and others). However, if the inflow outnumbers 1700veh/h, there will have collisions in the experiment. I wonder if there exists a collision avoidance method for lane changing?

**Comment by fywu85** [comment]
Which SUMO version are you at? Newer ones tend to have better collision avoidance implementation. LMK if the following helps:
```
# SUMO dependencies
apt-get install -y \
    cmake \
    build-essential \
    swig \
    libgdal-dev \
    libxerces-c-dev \
    libproj-dev \
    libfox-1.6-dev \
    libxml2-dev \
    libxslt1-dev \
    openjdk-8-jdk

# SUMO
cd ~ && \
    git clone --recursive https://github.com/eclipse/sumo.git && \
    cd sumo && \
    git checkout cbe5b73 && \ 
    mkdir build/cmake-build && \
    cd build/cmake-build && \
    cmake ../.. && \
    make
```
And use lane change mode of `0b011001010101` and speed mode of `0b11111`.

**Comment by CYBruce** [comment]
@fywu85 Thank you for your help. My Sumo version is v0_31_0-812-g1d4338a. I will try the above method and I will let you know if it works. By the way, would you please have a look at another question at issue #454?

**Comment by CYBruce** [comment]
@fywu85  I followed the shell code you given above. In the last sentence 'make', error happens.
'user@user--Super-Server:~/sumo/build/cmake-build$ make
[  3%] Built target utils_gui_windows
[  3%] Built target foreign_phemlight
[  3%] Built target foreign_tcpip
[  3%] Built target generate-version-h
[  3%] Building CXX object src/gui/CMakeFiles/gui.dir/GUIViewTraffic.cpp.o
In file included from /home/user/sumo/src/gui/GUIViewTraffic.cpp:29:0:
/home/user/sumo/src/utils/gui/div/GUIVideoEncoder.h: In constructor ‘GUIVideoEncoder::GUIVideoEncoder(const char*, int, int, double)’:
/home/user/sumo/src/utils/gui/div/GUIVideoEncoder.h:131:36: error: ‘AV_CODEC_ID_HEVC’ was not declared in this scope
         if (pCodecCtx->codec_id == AV_CODEC_ID_HEVC) {
                                    ^
/home/user/sumo/src/utils/gui/div/GUIVideoEncoder.h:148:34: error: ‘av_frame_alloc’ was not declared in this scope
         myFrame = av_frame_alloc();
                                  ^
/home/user/sumo/src/utils/gui/div/GUIVideoEncoder.h: In destructor ‘GUIVideoEncoder::~GUIVideoEncoder()’:
/home/user/sumo/src/utils/gui/div/GUIVideoEncoder.h:169:17: error: ‘AV_CODEC_CAP_DELAY’ was not declared in this scope
                 AV_CODEC_CAP_DELAY)) {
                 ^
/home/user/sumo/src/utils/gui/div/GUIVideoEncoder.h:178:31: error: ‘av_frame_free’ was not declared in this scope
             av_frame_free(NULL);
                               ^
/home/user/sumo/src/utils/gui/div/GUIVideoEncoder.h:198:39: error: ‘av_frame_free’ was not declared in this scope
                 av_frame_free(&myFrame);
                                       ^
In file included from /home/user/sumo/src/libsumo/Helper.h:27:0,
                 from /home/user/sumo/src/microsim/MSLane.h:45,
                 from /home/user/sumo/src/guisim/GUILane.h:31,
                 from /home/user/sumo/src/gui/GUIViewTraffic.cpp:38:
/home/user/sumo/src/libsumo/Subscription.h: At global scope:
/home/user/sumo/src/libsumo/Subscription.h:120:22: warning: unused parameter ‘refID’ [-Wunused-parameter]
         virtual void setContext(const std::string& refID) {}
                      ^
make[2]: *** [src/gui/CMakeFiles/gui.dir/GUIViewTraffic.cpp.o] error 1
make[1]: *** [src/gui/CMakeFiles/gui.dir/all] error 2
make: *** [all] error 2

'

**Comment by eugenevinitsky** [comment]
Hi @CYBruce, with lane changing mode 1621, you do get lane changes but they should be extremely infrequent and the experiment should not crash as a result of the crashes. Are you getting that the experiment is crashing?

**Comment by CYBruce** [comment]
@eugenevinitsky Yes, I notice that when the inflow rate is more than 1700veh/h, there will be a crash. Could there be other reasons?

**Comment by eugenevinitsky** [comment]
Could you log the error? That shouldn't happen.

**Comment by CYBruce** [comment]
Sure. Thank you for the help. I changed some places in the example bottlenecks.py.
The sumo report
'''
Loading configuration... done.
***Starting server on port 40756 ***
Loading net-file from '/home/user/flow/flow/core/kernel/scenario/debug/cfg/bay_bridge_toll_20190323-1338041553319484.7853382.net.xml'... done (1ms).
Loading additional-files from '/home/user/flow/flow/core/kernel/scenario/debug/cfg/bay_bridge_toll_20190323-1338041553319484.7853382.add.xml'... done (7ms).
Loading done.
Simulation started with time: 0.00
Warning: Teleporting vehicle 'flow_0.183'; collision with vehicle 'flow_0.186', lane=':4_0_2', gap=-1.00, time=431.00 stage=move.
Simulation ended at time: 432.00
'''

the terminal report
'''
/home/user/flow/flow/utils/flow_warnings.py:20: UserWarning: The attribute vehsPerHour in InFlows is deprecated, use vehs_per_hour instead.
  dep_from, obj.__class__.__name__, dep_to))
Loading configuration... done.
Success.
Loading configuration... done.
**********************************************************
**********************************************************
**********************************************************
WARNING: Inflows will cause computational performance to
significantly decrease after large number of rollouts. In 
order to avoid this, set SumoParams(restart_instance=True).
**********************************************************
**********************************************************
**********************************************************
Round 0, return: 267.48000000000485
Average, std return: 267.48000000000485, 0.0
Average, std speed: 5.041437005618326, 0.0
Closing connection to TraCI and stopping simulation.
Note, this may print an error message when it closes.
Closing connection to TraCI and stopping simulation.
Note, this may print an error message when it closes.
Skip automatic termination. Connection is probably already closed.
(flow) user@user--Super-Server:~$ python flow/examples/sumo/bottlenecks.py
/home/user/flow/flow/utils/flow_warnings.py:20: UserWarning: The attribute vehsPerHour in InFlows is deprecated, use vehs_per_hour instead.
  dep_from, obj.__class__.__name__, dep_to))
Loading configuration... done.
Success.
Loading configuration... done.
**********************************************************
**********************************************************
**********************************************************
WARNING: Inflows will cause computational performance to
significantly decrease after large number of rollouts. In 
order to avoid this, set SumoParams(restart_instance=True).
**********************************************************
**********************************************************
**********************************************************
Round 0, return: 480.9600000000055
Average, std return: 480.9600000000055, 0.0
Average, std speed: 8.17887041504013, 0.0
Closing connection to TraCI and stopping simulation.
Note, this may print an error message when it closes.
Closing connection to TraCI and stopping simulation.
Note, this may print an error message when it closes.
Skip automatic termination. Connection is probably already closed.
'''

**Comment by fywu85** [comment]
@CYBruce To address the build error, can you `conda install ffmpeg` and retry?

**Comment by CYBruce** [comment]
@fywu85 Still gives the same error.

**Comment by CYBruce** [comment]
Below is the bottlenecks.py. I changed the inflow_rate, lane changing mode and speed mode.
```
"""File demonstrating formation of congestion in bottleneck."""

from flow.core.params import SumoParams, EnvParams, NetParams, InitialConfig, \
    InFlows, SumoLaneChangeParams, SumoCarFollowingParams
from flow.core.params import VehicleParams
from flow.core.params import TrafficLightParams

from flow.scenarios.bottleneck import BottleneckScenario
from flow.controllers import SimLaneChangeController, ContinuousRouter
from flow.envs.bottleneck_env import BottleneckEnv
from flow.core.experiment import Experiment

import logging

import numpy as np
SCALING = 1
DISABLE_TB = True
# If set to False, ALINEA will control the ramp meter
DISABLE_RAMP_METER = True
INFLOW = 1700
# congestion happens when inflow over 1700

class BottleneckDensityExperiment(Experiment):

    def __init__(self, env):
        super().__init__(env)

    def run(self, num_runs, num_steps, rl_actions=None, convert_to_csv=False):
        info_dict = {}
        if rl_actions is None:

            def rl_actions(*_):
                return None

        rets = []
        mean_rets = []
        ret_lists = []
        vels = []
        mean_vels = []
        std_vels = []
        mean_densities = []
        mean_outflows = []
        for i in range(num_runs):
            vel = np.zeros(num_steps)
            logging.info('Iter #' + str(i))
            ret = 0
            ret_list = []
            step_outflows = []
            step_densities = []
            state = self.env.reset()
            for j in range(num_steps):
                state, reward, done, _ = self.env.step(rl_actions(state))
                vel[j] = np.mean(self.env.k.vehicle.get_speed(
                    self.env.k.vehicle.get_ids()))
                ret += reward
                ret_list.append(reward)

                env = self.env
                step_outflow = env.k.vehicle.get_outflow_rate(20)
                density = self.env.get_bottleneck_density()

                step_outflows.append(step_outflow)
                step_densities.append(density)
                if done:
                    break
            rets.append(ret)
            vels.append(vel)
            mean_densities.append(sum(step_densities[100:]) /
                                  (num_steps - 100))
            env = self.env
            outflow = env.k.vehicle.get_outflow_rate(10000)
            mean_outflows.append(outflow)
            mean_rets.append(np.mean(ret_list))
            ret_lists.append(ret_list)
            mean_vels.append(np.mean(vel))
            std_vels.append(np.std(vel))
            print('Round {0}, return: {1}'.format(i, ret))

        info_dict['returns'] = rets
        info_dict['velocities'] = vels
        info_dict['mean_returns'] = mean_rets
        info_dict['per_step_returns'] = ret_lists
        info_dict['average_outflow'] = np.mean(mean_outflows)
        info_dict['per_rollout_outflows'] = mean_outflows

        info_dict['average_rollout_density_outflow'] = np.mean(mean_densities)

        print('Average, std return: {}, {}'.format(
            np.mean(rets), np.std(rets)))
        print('Average, std speed: {}, {}'.format(
            np.mean(mean_vels), np.std(std_vels)))
        self.env.terminate()

        return info_dict


def bottleneck_example(flow_rate, horizon, restart_instance=False,
                       render=None):
    """
    Perform a simulation of vehicles on a bottleneck.

    Parameters
    ----------
    flow_rate : float
        total inflow rate of vehicles into the bottleneck
    horizon : int
        time horizon
    restart_instance: bool, optional
        whether to restart the instance upon reset
    render: bool, optional
        specifies whether to use the gui during execution

    Returns
    -------
    exp: flow.core.experiment.Experiment
        A non-rl experiment demonstrating the performance of human-driven
        vehicles on a bottleneck.
    """
    if render is None:
        render = False

    sim_params = SumoParams(
        sim_step=0.5,
        render=render,
        overtake_right=False,
        restart_instance=restart_instance)

    vehicles = VehicleParams()

    vehicles.add(
        veh_id="human",
    	lane_change_controller=(SimLaneChangeController, {}),
    	routing_controller=(ContinuousRouter, {}),
    	car_following_params=SumoCarFollowingParams(
        	speed_mode=31,
    	),
    	lane_change_params=SumoLaneChangeParams(
        	lane_change_mode=1621,
        ),
        num_vehicles=1)

    additional_env_params = {
        "target_velocity": 40,
        "max_accel": 2,
        "max_decel": 2,
        "lane_change_duration": 5,
        "add_rl_if_exit": False,
        "disable_tb": DISABLE_TB,
        "disable_ramp_metering": DISABLE_RAMP_METER
    }
    env_params = EnvParams(
        horizon=horizon, additional_params=additional_env_params)

    inflow = InFlows()
    inflow.add(
        veh_type="human",
        edge="1",
        vehsPerHour=flow_rate,
        departLane="random",
        departSpeed=10)

    traffic_lights = TrafficLightParams()
    if not DISABLE_TB:
        traffic_lights.add(node_id="2")
    if not DISABLE_RAMP_METER:
        traffic_lights.add(node_id="3")

    additional_net_params = {"scaling": SCALING, "speed_limit": 23}
    net_params = NetParams(
        inflows=inflow,
        no_internal_links=False,
        additional_params=additional_net_params)

    initial_config = InitialConfig(
        spacing="random",
        min_gap=5,
        lanes_distribution=float("inf"),
        edges_distribution=["2", "3", "4", "5"])

    scenario = BottleneckScenario(
        name="bay_bridge_toll",
        vehicles=vehicles,
        net_params=net_params,
        initial_config=initial_config,
        traffic_lights=traffic_lights)

    env = BottleneckEnv(env_params, sim_params, scenario)

    return BottleneckDensityExperiment(env)


if __name__ == '__main__':
    # import the experiment variable
    # inflow, number of steps, binary
    exp = bottleneck_example(INFLOW, 1500, render=True)
    exp.run(1, 1500)

```

**Comment by CYBruce** [comment]
Hi, @eugenevinitsky . Is this issue a bug or did I do something wrong?
