### ISSUE TITLE
what's the meaning of each variable in one state

### ISSUE THREAD

**Issue by nancyhwr** [flow-project/flow#474]
I have a simple question. I checked the initial state under the loop scenario, take one as an instance: 
      `'rl_0': ('rl', 'top', 0, 55.71428571428572, 0)`

I wonder what each variable represents here?  Where can I find the state explanation under each scenario? My reward function is defined based on the states and actions so that knowing their meanings would help. Thank you!

**Comment by AboudyKreidieh** [comment]
hi @nancyhwr the values are, in order:
- vehicle type: 'rl'
- starting edge: 'top'
- starting lane (0 if rightmost): 0
- starting position on edge (in meters): 55.71428571428572
- starting speed (in m/s): 0

**Comment by nancyhwr** [comment]
Thank you @AboudyKreidieh !
