### ISSUE TITLE
document all attributes in classes

### ISSUE THREAD

**Issue by AboudyKreidieh** [flow-project/flow#475]

**Comment by ashkan-software** [comment]
We need to add attributed to the following files. Could everyone who wrote them add attributes to these files?

/GitHub/flow/flow/envs/bay_bridge/base.py
/GitHub/flow/flow/envs/loop/lane_changing.py
/GitHub/flow/flow/envs/loop/loop_accel.py
/GitHub/flow/flow/envs/loop/wave_attenuation.py
/GitHub/flow/flow/envs/bottleneck_env.py
/GitHub/flow/flow/envs/green_wave_env.py
/GitHub/flow/flow/envs/merge.py
/GitHub/flow/flow/renderer/pyglet_renderer.py
/GitHub/flow/controllers/routing_controllers.py
/GitHub/flow/core/kernel/scenario/aimsun.py
/GitHub/flow/core/kernel/simulation/aimsun.py

**Comment by ashkan-software** [comment]
I have created the `document_attribute` for all of the commits for this issue. 

Please commit your changes only to this branch :)

**Comment by kjang96** [comment]
@AboudyKreidieh For subclasses attribute documentation, are we including attributes of the parent class as well, or just attributes unique to the subclass?

**Comment by AboudyKreidieh** [comment]
Let's just document the subclass's attribute. We can add a comment like:

See the parent class for description of other attributes.

**Comment by eugenevinitsky** [comment]
This is done and can be turned into a PR.

**Comment by ashkan-software** [comment]
Nice! Going to make it
