### ISSUE TITLE
ray tune error with multiagent policy graph

### ISSUE THREAD

**Issue by nancyhwr** [flow-project/flow#476]
My error happens in the run_experiments(), specifically 

```
ray.tune.error.TuneError: ('Trials did not complete', [PPO_WaveAttenuationPOEnv-v0_0_lr=1e-05])
Closing connection to TraCI and stopping simulation.
```
My code is based on the mutliagent example "multiagent_stabilizing_the_ring" project. Bascially, I want to try multiple RL CAVs on the same ring road with a shared PPO policy. Please let me know if I understood something wrong. Different with that example, I set 
         
 ```
env_name="WaveAttenuationPOEnv",
          scenario="LoopScenario", 

```
policy graph part was kept the same:

```
def gen_policy():
        return (PPOPolicyGraph, obs_space, act_space, {})

    # Setup PG with an ensemble of `num_policies` different policy graphs
    policy_graphs = {'av': gen_policy()}

    def policy_mapping_fn(_):
        return 'av'

    config.update({
        'multiagent': {
            'policy_graphs': policy_graphs,
            'policy_mapping_fn': tune.function(policy_mapping_fn),
            'policies_to_train': ['av']
        }
    })
```
Additionally, it's still not clear for me that if the shared policy is defined on the single-agent states and actions or joint states and actions. Any help would be truly appreciated!!

**Comment by eugenevinitsky** [comment]
Hi @nancyhwr, unfortunately the actual error is probably further up in the log. Could you attach the entire output? That'd be really helpful for debugging. 
The shared policy is defined on the single-agent states and actions. If you want to make it otherwise, you would need to modify it. Happy to help with that if that's what you want.

**Comment by nancyhwr** [comment]
I was stupid, I wen to the ray results and I saw this:
> ValueError: Have multiple policy graphs {'av': <ray.rllib.agents.ppo.ppo_policy_graph.PPOPolicyGraph object at 0x1c2bf24da0>}, but the env <WaveAttenuationPOEnv<WaveAttenuationPOEnv-v0>> is not a subclass of MultiAgentEnv?

I used "WaveAttenuationPOEnv" under the Multiagent Scenario, that's why the ray execution threw an error. So I changed back to "MultiWaveAttenuationPOEnv" and set the num_ring = 1, I guess this is the only way that I can use single-ring with MAS, right?  
Thank you @eugenevinitsky .  Could I also ask what's the 'av' mean in this 

`policy_graphs = {'av': gen_policy()}`

Does it mean that every RL agent will share the same policy graph, so they share the parameters? Could you give me some advise if I want to define the policy on the joint states and actions? Really appreciate your quick answer, I'm quite lost here.

**Comment by nancyhwr** [comment]
Should I just change the policy graph like 

`policy_graphs = {'shared_ppo': (PPOPolicyGraph, joint_obs_space, joint_act_space)}
`

and I guess I need to overload the get_state and get_action funcs. Please correct me if I'm wrong.

**Comment by eugenevinitsky** [comment]
Hi @nancyhwr , sorry for the delay. 
So, I'm going to answer your questions but just so you're not blocked by me, a really good resource is the RLlib multi-agent docs which have a bunch of examples: https://ray.readthedocs.io/en/latest/rllib-env.html#multi-agent-and-hierarchical

So there are two components to defining a multi-agent environment: defining the policy's (i.e. what are the states and actions) and defining the mapping between agents and policies (i.e. which agent gets which policy). In the current environment, every agent shares the same policy so they necessarily have to have the same action and observation space. The way them all sharing the policy is defined is by using the agent-id to policy mapping function:
 `def policy_mapping_fn(agent_id):
        return 'av'`
This says: for every agent_id, return the policy graph that has the name AV. If you wanted to have more policy graphs, you could define a policy_mapping_fn that returns a different graph for some of the agent ids. 
I'm a bit confused about how it would work that the agents have a joint state and action. In this case, wouldn't this actually be a centralized controller?

**Comment by nancyhwr** [comment]
Thank you so much @eugenevinitsky. I saw the article that you linked on the Bair blog too,  your explanation untangled my mind a lot. And yes, I am trying to make a centralized controller within a small range so that the joint action and space won't be too large.

**Comment by eugenevinitsky** [comment]
Ah, glad that helped. So, for each policy graph you can just construct your desired action space as is currently done in the action_space and observation_space methods in the MultiWaveAttenuationEnv. For example, if you want to control two accelerations at once, you might make the action space Box(low=min_accel, high=max_accel, shape=(2,)) which will tell the policy graph to have two values as the output of the neural network.

**Comment by MouvementMondial** [comment]
I also have a question regarding shared policies, which I could not answer with the ray-docs... If I have two RL-vehicles, both mapped on the same policy. I set "policies_to_train" to the only existing policy.

From which RL-vehicle are the experiences gathered and included in the training? Do I suppose correctly that the batches are collected from the experiences of both vehicles?

**Comment by eugenevinitsky** [comment]
That is correct; batches are collected from both RL vehicles and used for the training.

**Comment by nancyhwr** [comment]
Thank you very much! (sorry for the late answer) @eugenevinitsky
