### ISSUE TITLE
Error when using new_sumo_pr branch

### ISSUE THREAD

**Issue by binderwang** [flow-project/flow#488]
When using the latest new_sumo_pr branch with SUMO version 1.1.0, test with sugiyama.py, I got this error

```
 Traceback (most recent call last):
  File "examples/sumo/sugiyama.py", line 65, in <module>
    exp.run(1, 1500)
  File "/home/w00440981/Simulators/flow/flow/core/experiment.py", line 107, in run
    vehicles = self.env.vehicles
AttributeError: 'AccelEnv' object has no attribute 'vehicles'
```
As I added `self.vehicles = scenario.vehicles` in `flow/envs/base_env.py`, everything is OK.

**Comment by AboudyKreidieh** [comment]
hi @binderwang thank you for this update. I will fix the branch in a bit and get back to you on this

**Comment by AboudyKreidieh** [comment]
@binderwang the branch has been cleaned for some bugs. it should be functional now

**Comment by AboudyKreidieh** [comment]
closing this as it's been resolved. feel free to reopen or start a new issue if you have any questions @binderwang!
