### ISSUE TITLE
How to distribute RL vehicles uniformly? 

### ISSUE THREAD

**Issue by nancyhwr** [flow-project/flow#494]
How to add multiple RL vehicles among human-driven vehicles so that they distributed evenly or uniformly? Currently, I iteratively add several human-driven vehicles with a unique id first and one RL vehicle with an id and so on. 

Is there any smarter approach that I can take? Thank you!

**Comment by AboudyKreidieh** [comment]
hi @nancyhwr your approach is the cleanest way of doing it, and we've used the same approach before, see: https://github.com/flow-project/flow/blob/master/flow/benchmarks/figureeight1.py

**Comment by nancyhwr** [comment]
Oh, gotcha. Thank you @AboudyKreidieh !
