### ISSUE TITLE
How to craft the iteration output

### ISSUE THREAD

**Issue by nancyhwr** [flow-project/flow#497]
I guess I haven't fully understood the FLOW work mechanism, just wondering where can I craft the output after each iteration. I mean this output: (basically I'm trying to output the average velocity of a given traffic flow). Thank you!!!

```
Result for PPO_WaveAttenuationMergePOEnv-v0_0:
  custom_metrics: {}
  date: 2019-04-10_17-24-58
  done: false
  episode_len_mean: 2000.0
  episode_reward_max: 345.2960018600183
  episode_reward_mean: 228.18935778914107
  episode_reward_min: 165.5328456372555
  episodes_this_iter: 20
  episodes_total: 120
  experiment_id: 990fafb349044f50b700aba25e6c5a7f
 
  info:
    default:
      cur_kl_coeff: 0.006250001024454832
      cur_lr: 4.999999873689376e-05
      entropy: 7.050642013549805
      kl: 0.008851418271660805
      policy_loss: -0.005917277652770281
      total_loss: 7.460029602050781
      vf_explained_var: 0.783632218837738
      vf_loss: 7.465890884399414
    grad_time_ms: 10322.338
    load_time_ms: 11.67
    num_steps_sampled: 240000
    num_steps_trained: 240000
    sample_time_ms: 228797.357
    update_time_ms: 112.418
  iterations_since_restore: 6
  node_ip: 128.4.142.24
  num_metric_batches_dropped: 0
  pid: 35390
  policy_reward_mean: {}
  time_since_restore: 1435.6714062690735
  time_this_iter_s: 242.46500706672668
  time_total_s: 1435.6714062690735
  timestamp: 1554931498
  timesteps_since_restore: 240000
  timesteps_this_iter: 40000
  timesteps_total: 240000
  training_iteration: 6

```

**Comment by AboudyKreidieh** [comment]
hi @nancyhwr sorry for the late response! I'm not sure I understand the question. If you would like to see the results that are logged from an experiment, you can check the `ray_results` folder. Moreover, you can visualize results by following this documentation: https://flow.readthedocs.io/en/latest/visualizing.html. Hope this helps! If it doesn't answer your questions, please feel free to clarify.

**Comment by AboudyKreidieh** [comment]
another note: based on the title of your issue, if you'd like to add information to the step logs, that would probably need to be done from the RL algorithm side of things (in your case RLlib).
