### ISSUE TITLE
The green_wave task go wrong when I use DQN 

### ISSUE THREAD

**Issue by hyyh28** [flow-project/flow#499]
When I use DQN algorithm to train the green_wave task, I find in the training log, the episode rewards are all NaN. I have read the issues in the ray project and found that if the config['timesteps_per_iteration'] is not equal to the simulator steps, it will be that, but I have make it equal to the simulator steps which is 200 but I still go wrong, so I want to get your help. Here is the picture
![Screenshot from 2019-04-12 19-29-25](https://user-images.githubusercontent.com/14237409/56035430-bebde080-5d5c-11e9-9341-d1b81d1be3de.png)

**Comment by hyyh28** [comment]
And when I user A3C algorithm, there still have this problem, I think may be some bug in the base_env because I add `print(self.time_counter)`in the step function, I find the reset function dosen't work.

**Comment by hyyh28** [comment]
Sorry I have found that I missed the parameter config['horizon'], and now I have solved the problem

**Comment by zpymyyn** [comment]
> When I use DQN algorithm to train the green_wave task, I find in the training log, the episode rewards are all NaN. I have read the issues in the ray project and found that if the config['timesteps_per_iteration'] is not equal to the simulator steps, it will be that, but I have make it equal to the simulator steps which is 200 but I still go wrong, so I want to get your help. Here is the picture
> ![Screenshot from 2019-04-12 19-29-25](https://user-images.githubusercontent.com/14237409/56035430-bebde080-5d5c-11e9-9341-d1b81d1be3de.png)

Hi there, I'm also interested in testing DQN in flow, do you mind giving me some advice on how to do that? Thank you so much.
