### ISSUE TITLE
compute_reward in TrafficLightGridEnv inconsistent with its documentation

### ISSUE THREAD

**Issue by thanos91** [flow-project/flow#500]
**Choose an option**
This is a: 
- [ ] Question
- [ ] Feature request
- [x] Bug report

**Describe the issue**
In TrafficLightGridEnv the function compute_reward is documented to be the negative per vehicle delay minus a penalty for switching traffic lights, but only the second part is implemented.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by AboudyKreidieh** [comment]
hi @thanos91 thank you for bringing this up! should be resolved as of #503
