### ISSUE TITLE
extra vehicle parameter

### ISSUE THREAD

**Issue by TNelen** [flow-project/flow#510]
Hi,
I'm doing some experiments training an RL agent for the gird0 scenario, using visualizer_rllib, to visualize the results. 

Is it possilbe to visualize kpi's other than the reward, average speed and outflow?
I'm looking for kpi's like, average waiting time and total waiting time. I can't find any parameters like these built in in the scenario.

Where do i need to look for these, or is there any way on how i can define these myself?

Thanks in advance!

**Comment by AboudyKreidieh** [comment]
Hi @omitoz, you have a few options to do this:

* If you would like to compute these parameters during the simulation, you can create a new environment that prints the parameters, for example:

```python
from flow.envs import Env

class EnvWithPrint(Env):
    def step(self, actions):
        print("ADD PARAMETER HERE")
        return super().step(actions)
```

* If you would like to compute the parameters after running the simulations, you can generate an emission path by setting `SumoParams.emission_path` to a valid path and then using the generated emission file (which can be converted to a csv via the experiment class) to compute other vehicle parameters from the stored vehicle states.
