### ISSUE TITLE
FLOW Internal Wiki

### ISSUE THREAD

**Issue by kjang96** [flow-project/flow#511]
Create internal onboarding documentation including, but not limited to: Github workflow, team expectations, community interaction guidelines.

@ashkan-software is on setting up the wiki
@kjang96  is on gathering the onboarding docs

**Comment by ashkan-software** [comment]
This is great. Let's come up with what we need for each of them. Maybe assign @eugenevinitsky to tell us what we need to community interaction guidlines?

**Comment by ashkan-software** [comment]
I created this for now. We can populate it with links, information, etc.
https://github.com/flow-project/flow/wiki/Flow-Internal-On-boarding-Guideline

**Comment by ashkan-software** [comment]
Sorry. Correct link is: 
https://github.com/flow-project/flow/wiki/Flow-Internal-Onboarding-Guideline

**Comment by ashkan-software** [comment]
Internally working on it...
