### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by AaronLiuSy** [flow-project/flow#519]
**Choose an option**
This is a: 
- [ *] Question
- [ ] Feature request
- [ ] Bug report

**Describe the issue**
when I run the tutorial of visualization(rllab/plotting reward),there is a error no such a progress.csv file in my gym_log, and when I check all my training results,I found that I do not have any csv files in my gym_log.
Is there any problem in my training process?

**To Reproduce**
Leave empty if not applicable.
Importing data from ['/Users/aaron/rllab-multiagent/data/local/stabilizing-the-ring/stabilizing-the-ring_2019_05_10_15_20_45_0001']...
Reading /Users/aaron/rllab-multiagent/data/local/stabilizing-the-ring/stabilizing-the-ring_2019_05_10_15_20_45_0001/progress.csv
Reading /Users/aaron/rllab-multiagent/data/local/stabilizing-the-ring/stabilizing-the-ring_2019_05_10_15_20_45_0001/gym_log/progress.csv
[Errno 2] No such file or directory: '/Users/aaron/rllab-multiagent/data/local/stabilizing-the-ring/stabilizing-the-ring_2019_05_10_15_20_45_0001/gym_log/progress.csv'
Done! View http://localhost:5000 in your browser
 * Serving Flask app "frontend" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

**Desktop (please complete the following information):**
 - OS: mac OS
 - Commit number of flow [run git log and copy the commit number]
 - Version: 0.2.1

**Comment by eugenevinitsky** [comment]
Hi @AaronLiuSy, apologies that you're having this issue. We don't use rllab-multiagent very much anymore, but are looking into this to see if we can reproduce it. Did the experiment actually complete? Was there other output before this point?

**Comment by AaronLiuSy** [comment]
I guess the training process has completed, with the attachment, I will show you the package which include the output,   and those files are all result I got from every training.
Another question is how can I get the average velocity of this system after training? Now I'm trying to stabilizing the ring road(single lane), I have gotten a large amount of data and plotted the graph of average velocity, but it seems not as good as I expected.




------------------ 原始邮件 ------------------
发件人: "Eugene Vinitsky"<notifications@github.com>;
发送时间: 2019年5月15日(星期三) 中午11:41
收件人: "flow-project/flow"<flow@noreply.github.com>;
抄送: "."<897784781@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [flow-project/flow] visualization (#519)




Hi @AaronLiuSy, apologies that you're having this issue. We don't use rllab-multiagent very much anymore, but are looking into this to see if we can reproduce it. Did the experiment actually complete? Was there other output before this point?

**Comment by AboudyKreidieh** [comment]
hi @AaronLiuSy you should be able to find the progress.csv file in `rllab-multiagent/data/local/`, and choosing the folder with the experiment that you ran.

In terms of visualizing the average speed, you can run the checkpoints after training is complete using `flow/visualize/visualizer_rllab.py`. If you add the tag `--gen_emission`, it will create a csv file with the state of all vehicles at every time step, which you can then use to plot the speeds of vehicles

**Comment by eugenevinitsky** [comment]
Hi @AaronLiuSy, hope this was able to help! I'm closing the issue but if you still need help please reopen it or post another issue!
