### ISSUE TITLE
Removing Obsolete Reward Function in reward.py

### ISSUE THREAD

**Issue by mtgibson2014** [flow-project/flow#536]
Hi all,

These are the only functions in reward.py that are being used by the environments:

- rewards.desired_velocity
- rewards.rl_forward_progress
- rewards.min_delay_unscaled
- rewards.boolean_action_penalty
- rewards.penalize_headway_variance

I could go ahead and remove the ones that aren't being used, but I wanted to make another suggestions. Do y'all think it'll be better to remove this file and just place the functions where they are being used? It'll make the code easier to follow and reduce the clutter in the repo. If there are multiple envs using a function, then it could go in the base class or something.

Let me know what yal think!

**Comment by AboudyKreidieh** [comment]
@mtgibson2014 thanks for doing this! From my end, the only reward I'd like to keep that is not being used by any environment is:

* rewards.punish_rl_lane_changes

We used this for the multi-lane ring road experiments, which I at some point want to recreate in flow.

**Comment by kjang96** [comment]
I'd like to keep average_velocity, min_delay, penalize_standstill, penalize_near_standstill. These are all used in my experiments, but I haven't merged the code into master yet.

**Comment by AboudyKreidieh** [comment]
great, thanks kathy! that leaves:

* rewards.total_velocity
* rewards.punish_small_rl_headways
* rewards.punish_queues_in_lane
* rewards.reward_rl_opening_headways

unless @eugenevinitsky has any objections, feel free to remove them.

also, @kjang96 can you create an issue about adding your experiments to the repo? We can add it to a later release, and if you're too busy to do it we can probably get someone to help you out with it.

**Comment by kjang96** [comment]
@AboudyKreidieh yes, will add the issue!

**Comment by AboudyKreidieh** [comment]
@mtgibson2014 you can go ahead and delete the 4 reward functions I mentioned.

**Comment by mtgibson2014** [comment]
Cool! It's done and I made a PR for it.
