### ISSUE TITLE
Colliding Vehicles

### ISSUE THREAD

**Issue by cspatharis** [flow-project/flow#538]
**Choose an option**
This is a: 
- [X] Question
- [  ] Feature request
- [  ] Bug report

Hello,
I created a scenario and disabled all checks in order to be possible to have collisions between vehicles. Also, when a collision happens, the two colliding vehicles transport from the scenario and the rest of the cars continue until the end of episode steps. My question is, if there is a way to get the IDs of the colliding vehicles and the total number of collisions that occurred throughout the episode.

**Comment by AboudyKreidieh** [comment]
hi @cspatharis the names of the collided vehicles are acquired during the `update` method in flow/core/kernel/vehicle/traci.py via the `sim_obs[tc.VAR_TELEPORT_STARTING_VEHICLES_IDS]` variable (see line 121).

To get the names of the colliding vehicles, you can store them under a new class variable in this file (say `self.collided_ids`) then call it in the environment via the vehicle kernel, e.g.

```
collide_ids = self.k.vehicle.collided_ids
```

**Comment by cspatharis** [comment]
Thank you for your response.

I've been using SUMO for some time now and developed my project there but I wanted to move my project to Flow. I just realized that Flow does not support the latest version of SUMO that contains some crucial methods for my project. Can you tell me which is the latest supported version of SUMO and if there is a plan to move to the latest versions in the future? 
Thanks in advance!

**Comment by eugenevinitsky** [comment]
Hi @cspatharis, I believe the plan is to upgrade in the next week or so; we've had a few requests to upgrade. Do you happen to know the exact release date @AboudyKreidieh ?

**Comment by cspatharis** [comment]
Glad to hear that.

Basically, what I miss from the newer version is a way to get both the IDs of the colliding vehicles. In the latest version there is a constant called "tc.VAR_COLLIDING_VEHICLES_IDS" that does this job, but I haven't yet figured how to do it in your version of Flow. The previous answer from @AboudyKreidieh was very helpful, but it returns only the first vehicle that caused the collision.

Anyway, I'll wait for the upgrade ;)

**Comment by AboudyKreidieh** [comment]
hi @cspatharis sorry for the late reply. We will be upgrading sumo version `Eclipse SUMO Version v1_1_0+0000-2147d155b1` within the next day. The release will still be in development, so you may experience a few bugs, but for the most part we think everything should work fine. A more final release will come in the next week. I will let you know when both the development and final releases are up. :)

**Comment by AboudyKreidieh** [comment]
hi @cspatharis the most recent version of `master` currently supports sumo-1.1.0

**Comment by cspatharis** [comment]
Thank you very much. I'll give it a try right away ;)
