### ISSUE TITLE
stabilizing_highway:  Error: Answered with error to command 0xc4: The vehicle human_0 to add already exists.

### ISSUE THREAD

**Issue by buechelmartin** [flow-project/flow#547]
After I was eventually successfully running the example "stabilizing_the_ring" I tried with "stabilizing_highway".
Now I keep getting the following messages (errors / warnings), and I wonder if this something I can ignore. Seems like the agent is able to learn something, but the error message makes me believe it might  be nothing useful.
Thanks for any hints!

More specifically, I wonder:
- [x]  if I can ignore the Warning about the Inflows 
- [x] The error to command 0xc4 is something which means that my installation still has issues
- [x]  The warning about the teleporting can be ignored

Messages like this keep coming regularly:

WARNING: Inflows will cause computational performance to
significantly decrease after large number of rollouts. In 
order to avoid this, set SumoParams(restart_instance=True).
**********************************************************
**********************************************************
**********************************************************
Error: Answered with error to command 0xc4: The vehicle human_0 to add already exists.
Error: Answered with error to command 0xc4: The vehicle human_0 to add already exists.
**********************************************************
**********************************************************
**********************************************************
WARNING: Inflows will cause computational performance to
significantly decrease after large number of rollouts. In 
order to avoid this, set SumoParams(restart_instance=True).
**********************************************************
**********************************************************
**********************************************************
**********************************************************
**********************************************************
**********************************************************
WARNING: Inflows will cause computational performance to
significantly decrease after large number of rollouts. In 
order to avoid this, set SumoParams(restart_instance=True).
**********************************************************
**********************************************************
**********************************************************
Error: Answered with error to command 0xc4: The vehicle human_0 to add already exists.
Warning: Teleporting vehicle 'flow_0.18371'; collision with vehicle 'flow_0.18370', lane=':center_1_0', gap=-0.01, time=47546.00 stage=move.
Warning: Vehicle 'flow_0.18371' ends teleporting on edge 'center', time 47546.00.
**********************************************************
**********************************************************
**********************************************************
WARNING: Inflows will cause computational performance to
significantly decrease after large number of rollouts. In 
order to avoid this, set SumoParams(restart_instance=True).
**********************************************************
**********************************************************
**********************************************************
Error: Answered with error to command 0xc4: The vehicle human_0 to add already exists.
**********************************************************
**********************************************************
**********************************************************
WARNING: Inflows will cause computational performance to
significantly decrease after large number of rollouts. In 
order to avoid this, set SumoParams(restart_instance=True)

**Comment by Yasharzf** [comment]
It seems you haven't set the sumo-related parameters properly. You should set SumoParams(restart_instance=True)

**Comment by buechelmartin** [comment]
Thanks this removed the inflow warning as well as the Error command 0xc4.
Collisions occur from time to time.

Please note that I only tried to run the example "stabilizing_highway" as provided, so maybe this can be added to the example code.

Concerning the collisions, I read that the RL controllers action is intended to be restricted to safe, collision free actions. I there still some issue in the provided example?

**Comment by eugenevinitsky** [comment]
Hi @buechelmartin, this env seems to have a bug where on rare occasion, SUMO incorrectly computes the safe velocity and it leads to a collision. We tend to handle this case in our research by just throwing this sample out or penalizing it. 
However, have you tried upgrading to the new version of SUMO that we just released compatibility with recently? It may resolve this issue, we are still investigating.

**Comment by AboudyKreidieh** [comment]
hi @buechelmartin, looking into this some more, the collisions seem to be because the `minGap` car following parameter is being set to 0 for vehicles controlled by us (see lines 283-287 in flow/core/params.py). I will remove this in an upcoming PR, and will update you shortly. For now, you are encouraged to delete these lines.

**Comment by buechelmartin** [comment]
Thanks @AboudyKreidieh , this seems to avoid the collisions!
