### ISSUE TITLE
Adding new vehicles to scenario with custom depart time/edge

### ISSUE THREAD

**Issue by cspatharis** [flow-project/flow#548]
**Choose an option**
This is a: 
- [X] Question
- [ ] Feature request
- [ ] Bug report

Hello again,
so far testing the new version of SUMO with FLOW works like a charm. 
I want to ask a question though about creating scenarios like with NetEdit. Specifically, what I need is to create the scenario beforehand, e.g. the number of vehicles, the edge that the x vehicle will enter the scenario, what route it will choose and the depart time of that vehicle. 
Example: 
```
<vehicle id="5" depart="7.00">
    <route edges="left1_0 left0_0"/>
</vehicle>
```

I've tried using InFlows but it is not exactly what I need for my work. When I use NetEdit I can create randomly these kind of scenarios by using the randomTrips.py method provided by SUMO\tools. So I wanted to know if it is possible:

1) to create scenarios with some approach similar to randomTrips.py (or to create this method manually)

2) to load my own scenarios and provide the net, routes, trips, etc. files that I would have already created with NetEdit.

Thanks in advance.

**Comment by eugenevinitsky** [comment]
Hi, this should be a supported use case; once you have your netfile (which you can get out of netedit) you can use it to instantiate a Flow scenario. @AboudyKreidieh may be able to provide you more details?

**Comment by AboudyKreidieh** [comment]
hi, yes this is supported. Please check out the following tutorial for more: https://github.com/flow-project/flow/blob/master/tutorials/tutorial08_network_templates.ipynb

**Comment by nathanlct** [comment]
@cspatharis, we hope that your questions have been answered.
If you have any further ones, please post them on [StackOverflow](https://stackoverflow.com/questions/tagged/flow-project) using the tag `flow-project`!
