### ISSUE TITLE
Having both RL and actuated traffic lights in a simple grid scenario

### ISSUE THREAD

**Issue by Antonio-Dominguez** [flow-project/flow#553]
[QUESTION]
Hello!
I am trying to create a simple grid scenario containing at the same time actuated traffic lights and a group of RL-based traffic lights. I am modifying the following scripts:

- flow/examples/rllib/green_wave.py (Experiment)
- flow/scenatios/grid.py (Scenario)
- flow/envs/green_wave_env.py (Environment)

According to the ADDITIONAL_ENV_PARAMS variable, either all traffic lights are "controlled" (RL) or either they are all actuated. I've tried to add every TL manually in the grid scenario but it seems that in the end the ADDITIONAL_ENV_PARAMS variable is who determines how traffic lights are managed in the simulation.
Is there a way I could do this? I didn't find any documentation about it.

Thank you very much!

Antonio

**Comment by eugenevinitsky** [comment]
Hi @Antonio-Dominguez, there's absolutely a way to do this. @kjang96 is most familiar with this environment; she should be able to help you! It might also be worthwhile for us just to add an example of this codebase.

**Comment by Antonio-Dominguez** [comment]
Perfect! Thank you very much @eugenevinitsky ! I'd really appreciate your help @kjang96

**Comment by kjang96** [comment]
Hi @Antonio-Dominguez! Thanks for your patience! Taking a look at this now.

**Comment by kjang96** [comment]
@Antonio-Dominguez, `tl_type` is a vestige of old code that missed a refactor. So thanks for bringing it to our attention! I’m working on an update that will make this simpler to code. Unless you want to see the actuated traffic baseline in action, you can set `tl_type` to anything and it won't affect the outcome. In the meantime, to answer your questions and fix your problem: 

- There are two layers to making traffic lights in SUMO. Let’s define node x and say we want this to be a traffic light. First, you need to define this node to be of type `traffic_light` (see: ‘/path/to//flow/scenarios/grid.py’ and the `_build_inner_nodes` function). If no further customization is specified, node x will default to SUMO’s traffic light phases. Second (optional), if you want to specify phases or make the traffic light actuated, you need to specify that traffic light node x is `actuated`. Flow provides a way to do this via the TrafficLightParams object.

- To make an RL-controlled traffic light, only the first step is necessary. 
- For what you’re doing:
    - SimpleGridScenario defaults all of the nodes to be of traffic light type, meaning they are all capable of RL control — this may change in future updates!
    - From `green_wave.py`, the easiest way to achieve a mixture of actuated and RL-controlled traffic lights is to create a TrafficLightParams object and use its `add` function to add actuated traffic lights to the nodes you want them  to exist at. 
    - Following that ^, now ALL of the nodes are technically RL-controllable, but since you want some nodes to be actuated, you need to make sure that there are no RL actions applied to said actuated node in the `_apply_rl_actions` function in the environment you’re using


Please let me know if you have any questions!

**Comment by nathanlct** [comment]
@Antonio-Dominguez, I hope your questions have been answered!

If you have any further ones, please from now on post them on StackOverflow using the tag `flow-project`!

**Comment by zhouhao0605** [comment]
@Antonio-Dominguez Hey buddy, I'm also trying the green_wave.py, just curious have you encountered the issue of sumo termination? I checked the error report, it seems the default horizon is a float variable, so it encounter problems when doing np.zeros( horizon,.) 
I solved the issue by setting HORIZON to 1000. I am wondering did you have the similar experience and how do you solve that? 
@eugenevinitsky @kjang96 The issue might prevent the green_wave.py to be run without any modification, do you guys notice that?

**Comment by Antonio-Dominguez** [comment]
Hello @zhouhao0605 sorry for this late response, I just read this. I have encountered the problem of sumo termination but it was because there were some collisions in my simulation. Have you solved it yet?

**Comment by Antonio-Dominguez** [comment]
Hello again @kjang96 and @eugenevinitsky  , 

After doing what you suggested I finally could declare actuated and controlled traffic lights at the same time in my simulations and it worked. 
The thing is that in the end, I only apply the **RL actions** to the traffic lights I wanna target. My grid contains 25 intersections, being only 5 of them controlled by the Agent. However, there are now a lot of parameters that are useless (`rl_actions` and the observation variables). This is a problem since my agent will take into account a lot of unnecessary information and convergence will take more time. 
Here's a set of variables I changed in `green_wave_env.py` with the goal of changing the size of all these vectors.

- `CONTROLLED_NODES = ["center7", "center11", "center12", "center13", "center17"]`

- `self.num_traffic_lights = len(CONTROLLED_NODES)`, which corresponds to 5 in my case. This modification affects the size of  `self.last_change`, `self.direction` and `self.currently_yellow`. It also implies that the `action_space` size will be now five instead of 25. The same thing will happen for the `traffic_lights` box in the `observation_space` vector.

- In view of the fact that the `action_space` size has changed, it is expected that `rl_actions` size in `_apply_rl_actions` will also be now equal to 5. In every iteration of `_apply_rl_actions` I replaced the code with: 

`                        self.k.traffic_light.set_state(
                            node_id=CONTROLLED_NODES[i],
                            state="GGGGrrrrGGGGrrrr")
`
so that commands should only be sent to my controlled nodes.

- In `PO_TrafficLightGridEnv` the shape of the `tl_box` will also change (which by the way I never understood). 

`        tl_box = Box(
            low=0.,
            high=1,
            shape=(3 * 4 * self.num_observed * self.num_traffic_lights +
                   2 * len(self.k.scenario.get_edge_list()) +
                   3 * self.num_traffic_lights,),
            dtype=np.float32)
`

It does not work. I get an error message saying "TracCI requested termination" and I know I'm missing something but I don't know what. Do you have any ideas?

**Comment by Antonio-Dominguez** [comment]
> @Antonio-Dominguez, I hope your questions have been answered!
> 
> If you have any further ones, please from now on post them on StackOverflow using the tag `flow-project`!

Hello @nathanlct , Can we reopen the issue?

**Comment by eugenevinitsky** [comment]
Hmm, is there a branch up on your fork?

**Comment by Antonio-Dominguez** [comment]
@eugenevinitsky Not yet but I can create one if you want! (You still have access to my repository)

**Comment by Antonio-Dominguez** [comment]
@eugenevinitsky @kjang96 same problem here, I cannot publish my branch, but I'd prefer to share mi code privately with you.

**Comment by Antonio-Dominguez** [comment]
After upgrading ray I could fix this problem!
