### ISSUE TITLE
test_green_wave non deterministic

### ISSUE THREAD

**Issue by nathanlct** [flow-project/flow#558]
This is a: **Bug report**

**Describe the issue**

Travis gives me the following error in two of my PRs:

```======================================================================
ERROR: test_green_wave (tests.fast_tests.test_examples.TestRllibExamples)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/flow-project/flow/tests/fast_tests/test_examples.py", line 166, in test_green_wave
    self.run_exp(alg_run, env_name, config)
  File "/home/travis/build/flow-project/flow/tests/fast_tests/test_examples.py", line 210, in run_exp
    'training_iteration': 1,
  File "/home/travis/miniconda/envs/flow/lib/python3.5/site-packages/ray/tune/tune.py", line 124, in run_experiments
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [PPO_PO_TrafficLightGridEnv-v0_0])
----------------------------------------------------------------------
Ran 200 tests in 745.686s
FAILED (errors=1)
```

This test (`test_examples.py` > `TestRllibExamples` > `test_green_wave`) seems to behave in a non-deterministic way:

In #552, you can see in the commit history that the commit `Merge branch 'master' into tutorials-docs` shows that branch build passed and PR build failed:

![image](https://user-images.githubusercontent.com/33672752/59954146-1b620980-9438-11e9-8621-5d4efccc76da.png)

while in the next commit `test` (in which I just modified a word in a readme file), both builds passed. 

I had the same issue in #554. I add something and the build fails (sometimes PR build fails, sometimes branch build fails), then I add something else unrelevant to why the build failed and suddenly it passes.

**Comment by AboudyKreidieh** [comment]
resolved by #671
