### ISSUE TITLE
Make Flow installation easy

### ISSUE THREAD

**Issue by ashkan-software** [flow-project/flow#563]
Let us make the flow installation, as easy as other famous python packages (e.g. TensorFlow, or PyTorch) with as few commands as possible (e.g. `pip install flow`)

**Comment by guilhermevarela** [comment]
I am using macos 10.14.5 (Mojava) and as of now running scripts/setup_sumo_osx.sh installs SUMO 1.1 which is as far as I can tell is not compatible with flow:
`gsavarela@macbook ~/W/p/flow> vim scripts/setup_sumo_osx.sh
gsavarela@macbook ~/W/p/flow> which sumo
/Users/gsavarela/sumo_binaries/bin/sumo
gsavarela@macbook ~/W/p/flow> rm -rfd /Users/gsavarela/sumo_binaries/
gsavarela@macbook ~/W/p/flow> scripts/setup_sumo_osx.sh
Installing system dependencies for SUMO
Warning: swig 4.0.0 is already installed and up-to-date
To reinstall 4.0.0, run `brew reinstall swig`
Warning: sdl 1.2.15_1 is already installed and up-to-date
To reinstall 1.2.15_1, run `brew reinstall sdl`
Warning: sdl_image 1.2.12_7 is already installed and up-to-date
To reinstall 1.2.12_7, run `brew reinstall sdl_image`
Warning: sdl_mixer 1.2.12_3 is already installed and up-to-date
To reinstall 1.2.12_3, run `brew reinstall sdl_mixer`
Warning: sdl_ttf 2.0.11_1 is already installed and up-to-date
To reinstall 2.0.11_1, run `brew reinstall sdl_ttf`
Warning: portmidi 217_2 is already installed and up-to-date
To reinstall 217_2, run `brew reinstall portmidi`
==> brew cask install Caskroom/cask/xquartz
Warning: Cask 'xquartz' is already installed.

To re-install xquartz, run:
  brew cask reinstall xquartz
Warning: autoconf 2.69 is already installed and up-to-date
To reinstall 2.69, run `brew reinstall autoconf`
Warning: automake 1.16.1_1 is already installed and up-to-date
To reinstall 1.16.1_1, run `brew reinstall automake`
Warning: pkg-config 0.29.2 is already installed and up-to-date
To reinstall 0.29.2, run `brew reinstall pkg-config`
Warning: libtool 2.4.6_1 is already installed and up-to-date
To reinstall 2.4.6_1, run `brew reinstall libtool`
Warning: gdal 2.4.1_1 is already installed and up-to-date
To reinstall 2.4.1_1, run `brew reinstall gdal`
Warning: proj 6.1.0 is already installed and up-to-date
To reinstall 6.1.0, run `brew reinstall proj`
Warning: xerces-c 3.2.2 is already installed and up-to-date
To reinstall 3.2.2, run `brew reinstall xerces-c`
Warning: fox 1.6.56_1 is already installed and up-to-date
To reinstall 1.6.56_1, run `brew reinstall fox`
Installing sumo binaries
~/sumo_binaries/bin ~/Work/py/flow
--2019-07-09 09:11:06--  https://akreidieh.s3.amazonaws.com/sumo/flow-0.3.1/binaries-mac.tar.xz
Resolving akreidieh.s3.amazonaws.com (akreidieh.s3.amazonaws.com)... 52.219.112.50
Connecting to akreidieh.s3.amazonaws.com (akreidieh.s3.amazonaws.com)|52.219.112.50|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6065016 (5.8M) [application/x-xz]
Saving to: ‘binaries-mac.tar.xz’

binaries-mac.tar.xz                                                 100%[===================================================================================================================================================================>]   5.78M  1.66MB/s    in 3.5s

2019-07-09 09:11:11 (1.66 MB/s) - ‘binaries-mac.tar.xz’ saved [6065016/6065016]

~/Work/py/flow
Add the following to your ~/.bashrc:

export SUMO_HOME="$HOME/sumo_binaries/bin"
export PATH="$SUMO_HOME:$PATH"
gsavarela@macbook ~/W/p/flow> which sumo
/Users/gsavarela/sumo_binaries/bin/sumo
gsavarela@macbook ~/W/p/flow> sumo --version
Eclipse SUMO Version 1.1.0
 Build features: x86_64-apple-darwin18.6.0 GDAL GUI Python
 Copyright (C) 2001-2018 German Aerospace Center (DLR) and others; http://sumo.dlr.de

Eclipse SUMO Version 1.1.0 is part of SUMO.
This program and the accompanying materials
are made available under the terms of the Eclipse Public License v2.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v20.html
SPDX-License-Identifier: EPL-2.0
gsavarela@macbook ~/W/p/flow>`

**Comment by AboudyKreidieh** [comment]
this is a duplication of #192, so closing
