### ISSUE TITLE
Make file names better and more 'logical'

### ISSUE THREAD

**Issue by ashkan-software** [flow-project/flow#564]
The name of some of our files are good. But the name for some other files are quite confusing.

Look at this example:

RL version of traffic lights: `examples/rllib/green_wave.py`
non-RL version of traffic lights: `examples/sumo/grid.py`

Environment for RL version of traffic lights: `green_wave_env.py`
Environment for non-RL version of traffic lights: `loop_accel.py`

**Comment by kjang96** [comment]
Alternatives for the grid are "traffic_light_grid.py", "intersection.py"

**Comment by ashkan-software** [comment]
Change some of the parameter names, such as `num_traffic_lights`, which actually represents the number of intersections, not individual traffic lights.

**Comment by AboudyKreidieh** [comment]
The branch associated with this issue has been merged.
