### ISSUE TITLE
Modifing Green Wave

### ISSUE THREAD

**Issue by basit2120** [flow-project/flow#568]
**Choose an option**
This is a: 
- [x] Question
- [ ] Feature request
- [ ] Bug report

How we can implement existing rllib algorithm i.e. ARS algorithm in green wave.

**Comment by omitoz** [comment]
in the green_wave example, in the function setup_exps(): there is a parameter alg_run, default set on PPO, you can change that to ARS. 

Keep in mind that there could be any config parameters that you need to change.

**Comment by eugenevinitsky** [comment]
@TNelen thank you for the answer! That is correct, you just need to change the line that says 'PPO' to 'ARS'. You may also need to remove some of the config parameters that are used in PPO but do not exist in ARS.

**Comment by basit2120** [comment]
Thanks  for the help guys.
