### ISSUE TITLE
Multi Agent traffic light control

### ISSUE THREAD

**Issue by TNelen** [flow-project/flow#570]
This is a: 
- [x] Question
- [ ] Feature request
- [ ] Bug report

Hi, i'm trying to make a multi-agent implementation of the 3x3 grid. 

What i want to achieve is that an agent (traffic light) gets as state the information of only of the cars driving on the edges connected to the intersection on which the traffic light is located.

Is it possible to get the id of the traffic light that the agent is controlling? 
And second, is there any way to determine on with intersection the traffic light is located?

Are the agent assigned to the traffic light in a standard order?
If it is for example top left, to bottom right, i can manually assign the edge id's to a particular agent?

Many thanks in advance!

**Comment by TNelen** [comment]
Are the agent assigned to the traffic light in a standard order?
If it is for example top left, to bottom right, i can manually assign the edge id's to a particular agent?

**Comment by kjang96** [comment]
Hi @TNelen!

- First, the easiest way to select and know the ID of the node you want the traffic light to be at is to set `render=True` in the runner script. See the attached image. In the GUI, click the rainbow circle (in the image, this is right of the dropdown bar that says "custom_2." Then click Junctions and select "Show junction name" That will tell you the name of the node / traffic light. 

![image](https://user-images.githubusercontent.com/10969394/60307579-1ac6e880-98fa-11e9-8de1-6adeb2b9f15b.png)

- Second, intersections and traffic lights are ID'd with the same variable, so the above point should answer that. 
- Third, the default order right now starts at the bottom left node. This is the zero-indexed node. Numbering goes to the right. Then it starts from left to right of the row above it. And so on
- We have a function that will return all edges heading toward a particular intersection. This is used in `PO_TrafficLightGridEnv`. On L493, the call to `self.scenario.get_node_mapping()`returns a dict of nodes to the edges that head toward it. Try setting a breakpoint here to see what this function does.

**Comment by TNelen** [comment]
Thanks you for the answer! I think I got all the information now to make ik work.
