### ISSUE TITLE
RLib Visualization Error - ModelCatalog

### ISSUE THREAD

**Issue by KidTrunks** [flow-project/flow#571]
**This is a:** Question

**OS:** Ubuntu 18.04

**Describe the Issue:**
Hi I am trying to use the Replaying a Trained Policy function under the RLlib Visualization Tutorial.
 I have already looked through this thread and updated visualizer_rllib.py file: 
https://github.com/flow-project/flow/pull/372
However I am still getting the ModelCatalog and get_preprocessor_as_wrapper errors. 

Upon running the changed visualizer_rllib.py file, the following errors occured:
![visualize_sim](https://user-images.githubusercontent.com/45654203/60312665-82833f00-999f-11e9-8583-6cc8080d2471.PNG)

After changing all sim_params to sumo_params in the visualizer_rllib.py file, another error occured:
![visualize_sumo](https://user-images.githubusercontent.com/45654203/60312704-a8104880-999f-11e9-8f7d-8009c82882c3.PNG)

Any help is appreciated, thanks for your time.

**Comment by nathanlct** [comment]
Hello @KidTrunks,

Can you tell us what your ray version is? 

Thanks!

**Comment by KidTrunks** [comment]
Hi @nathanlct I am using ray version-0.6.4

**Comment by KidTrunks** [comment]
Hi @fywu85 has there been a fix for this issue yet?

**Comment by KidTrunks** [comment]
Hi, the issue has been fixed, I made the wrong changes. Sorry about the trouble, you may close it now thanks.
