### ISSUE TITLE
Abstract backend calling

### ISSUE THREAD

**Issue by fywu85** [flow-project/flow#58]
It might be handy to support abstract backend calling in Flow in a way similar to what Keras [backend](https://keras.io/backend/) does.

An hypothetical API could be as follows:
```
(in bash) 
export FLOW_BACKEND = "libsumo" 

(in python)
from flow import backend as K
K.addFull(...)
K.setSpeed(...)
...
K.step()
...
K.getPosition(...)
K.getAcceleration(...)
```

**Comment by eugenevinitsky** [comment]
Hi Fangyu, could you explicate on what the advantages of this are over the current Vehicles class?

**Comment by fywu85** [comment]
Sure! In fact, the proposed abstract backend API is a level lower than the current Vehicle class. We are replacing the `traci` calls inside of the Vehicle class, not the Vehicle class itself. For example, instead of calling `traci.vehicle.setSpeed(...)`, we do something like:
```
import traci as K
K.vehicle.setSpeed(..)
```

This recommendation is assuming that, in the future, we want to replace `traci` with something better, i.e., `libsumo`. In that situation, all we need to modify is the backend variable. For example, an naive implementation could be:
```
import libsumo as K
K.vehicle.setSpeed(..)
```

Going into this direction one step further, if we want to use something other than SUMO, say, Aimsun, all we need to do is to change (kind of) `import libsumo as K` to `import aimsun as K`. This way, it makes comparing different simulation engines much more tractable and efficient.

This same concept could also apply to the DRL interface. Maybe, we want to be able to freely interchange between `rllib`, `rllab`, and perhaps `google/dopamine`. Abstract backend calling can make our life &epsilon; more easier in this regard.

*Note that the way that Keras implements this is a little bit more complex than what I have shown, but the architectural principle holds the same.*

**Comment by AboudyKreidieh** [comment]
Since this is a subset of the aimsun kernel, I’m gonna close it
