### ISSUE TITLE
Specific Get_state() return based on RL agent-id

### ISSUE THREAD

**Issue by TNelen** [flow-project/flow#583]
**Choose an option**
This is a: 
- [x] Question
- [ ] Feature request
- [ ] Bug report

Hi, 

I'm tying to make a multi agent implementation of the 3x3 grid (grid0) for traffic light control
In the get_state function, i want to differ in information that i sent to the RL agent in this function. So agent 1 get only the information of vehicles driving on edges heading towards intersection 1. 

How can i distinguish between agents? Is it possible to do someting like this?
```python
agent_id = get_agent_id()
    if agent_id =0
        #return 'all info of vehicles on edges heading to traffic light1
    if agent_id =1
        ...
```

is there any way or function like this (agent list or something) to distinguish between the different agents in the getstate function?

And second, are the agent_id's the same as the traffic light id's (intersection_id's)?

Thanks in advance!

**Comment by ashkan-software** [comment]
@TNelen  hello! Could you please post your question according to https://github.com/flow-project/flow#technical-questions? I will answer it once you post it immediately :).

**Comment by nathanlct** [comment]
As @ashkan-software said, please post your question [here](https://stackoverflow.com/questions/tagged/flow-project) using the tag `flow-project`!
