### ISSUE TITLE
Warnings for EC2  x Inflows restart_instance

### ISSUE THREAD

**Issue by kjang96** [flow-project/flow#59]
I think @AboudyKreidieh uncovered this bug a while ago, but when running EC2 (or is it all0 experiments with Inflows, the experiments get progressively slower, until an experiment of batch size ~ 40000, itr=300 experiment will take 4 days to run instead of <1/2 day

**Comment by AboudyKreidieh** [comment]
@kjang96 can you clarify what the issue is?

**Comment by eugenevinitsky** [comment]
If a user uses inflows, but forgets to set restart_instance = True, their experiment will take a billion years but they won't know why. We should warn them by default if they try to do this
