### ISSUE TITLE
How can I change different sizes for different vehicles in VehicleParam?

### ISSUE THREAD

**Issue by BingLiHanShuang** [flow-project/flow#590]
It seems that the size of vehicle can't be changed?

**Comment by nathanlct** [comment]
Hello @BingLiHanShuang,

That does not seem to be currently supported, however you can easily change it by adding a `length` parameter to `VehicleParam`'s `add` method, and setting `type_params['length'] = length` in this method. (Also add `'length': length` in the `self.type_parameters[veh_id]` dict if you want to use inflows). 

Hope this answers your question!
