### ISSUE TITLE
stabilizing_the_ring not working for Aimsun x RLlib

### ISSUE THREAD

**Issue by kjang96** [flow-project/flow#596]
**Choose an option**
This is a: 
- [ ] Question
- [ ] Feature request
- [x] Bug report

**Describe the issue**
A clear and concise description of what the bug/question/feature request is.

Running stabilizing_the_ring.py experiments via Aimsun exhibit stop and go waves and RL control (i.e. slow, learning-how-drive behavior) when using rllab, but no traffic forms and the 'rl' vehicle doesn't appear to be RL-controlled (it's driving too smoothly for the actions to be random). Maybe there's a discrepancy between the two simulators subkernel?

**To Reproduce**
Leave empty if not applicable.
1. examples/rllib/stabilizing_the_ring.py
2. python stabilizing_the_ring.py
3. n/a

**Expected behavior**
Stop and go waves should occur, and the RL vehicle should be driving obviously terribly in the initial stages of training

**Screenshots**
Leave empty if not applicable.

**Desktop (please complete the following information):**
 - OS: OSX
 - Commit number of flow [run git log and copy the commit number]: eb44e2760076537bf1422ca024f8642b39cbf597
 - Version [run python -c "import flow; print(flow.__version__)"]: 0.4.0.dev
 Leave empty if not applicable.

**Additional context**

**Comment by nathanlct** [comment]
@kjang96 I haven't tried the rllab example, but running `examples/rllib/stabilizing_the_ring.py` with Sumo/traci replaced by Aimsun seems to work for me (at least the RL vehicle is not driving smoothly at all).
