### ISSUE TITLE
Conflict between packages in the flow environment.yml

### ISSUE THREAD

**Issue by lucfisc** [flow-project/flow#60]
I tried to run that file : https://github.com/flow-project/flow/blob/master/environment.yml in a dockerfile and I found some conflicts packages ( see the image) 
<img width="721" alt="capture d ecran 2018-08-27 a 15 54 15" src="https://user-images.githubusercontent.com/19914496/44690988-a1c4df00-aa11-11e8-85d7-65acf27a636f.png">

Is the version of matplotlib really important ?

**Comment by berkeleyflow** [comment]
No, can you submit a PR with a valid version?

**Comment by AboudyKreidieh** [comment]
this has finally been resolved
