### ISSUE TITLE
Environment vs scenario

### ISSUE THREAD

**Issue by nathanlct** [flow-project/flow#600]
## Feature Description

Following the meeting, we may want to merge the scenarios and the environments together:

- the term environment could be understood as the physical environment (ie the scenario, whose name comes from sumo) (other suggestion is to rename the folder `envs` to `rl_envs`)
- except for some generic environments (`TestEnv`, `AccelEnv`...), most environments are written just for a specific scenario, and sometimes call specific functions that only exist in the scenario they are written for
- it could make it easier to have everything in one place and to have a tighter relation between scenario and environment by placing them into the same file (while keeping a class hierarchy in some way so that we can still inherit and not rewrite everything for every pair env, scenario)

**Comment by ashkan-software** [comment]
maybe as the first step, rename `scenarios` to `networks`
