### ISSUE TITLE
Failed to run examples/sumo/sugiyama.py

### ISSUE THREAD

**Issue by jingyanping** [flow-project/flow#601]
hi,
I followed the steps for the installation procedure (https://berkeleyflow.readthedocs.io/en/latest/flow_setup.html). However, when i tried to run the example
( in the "Testing the Installation" section) I get the following error:

sean@ubuntu:~$ source activate flow
(flow) sean@ubuntu:~$ cd flow
(flow) sean@ubuntu:~/flow$ python examples/sumo/sugiyama.py
Traceback (most recent call last):
  File "examples/sumo/sugiyama.py", line 11, in <module>
    from flow.envs.loop.loop_accel import AccelEnv, ADDITIONAL_ENV_PARAMS
  File "/home/sean/flow/flow/envs/__init__.py", line 6, in <module>
    from flow.envs.green_wave_env import TrafficLightGridEnv, \
  File "/home/sean/flow/flow/envs/green_wave_env.py", line 12, in <module>
    from gym.spaces.tuple_space import Tuple
ImportError: No module named  'gym.spaces.tuple_space'

BTW: i use ubuntu14.04, python3.6.5, sumo0.32.0
I have  installed the gym,  Any ideas ? @dimikout3 @eugenevinitsky
I have already browsed other people's questions about this, but I have not found a solution.

**Comment by jingyanping** [comment]
I have solved this problem，because in "/home/sean/flow/flow/envs/green_wave_env.py", there is a line of code that was originally ”from gym.spaces.tuple import Tuple_space” , I changed it to "from gym.spaces.tuple import Tuple" 

but i met this problem,when i write the code "~/flow$ python examples/sumo/sugiyama.py", sumo can open, but sumo report an error:
Error: tcpip::Storage::readIsSafe: want to read 4 bytes from Storage, but only 3 remaining
Quitting (on error).@dimikout3 @eugenevinitsky

**Comment by jingyanping** [comment]
(flow) sean@ubuntu:~/flow$ python --version
Python 3.5.2 :: Continuum Analytics, Inc.

**Comment by eugenevinitsky** [comment]
Hi @jingyanping, sorry abaout this issue! This suggests that your version of SUMO is out of date. Could you reinstall SUMO via the instructions and see if that helps?

**Comment by jingyanping** [comment]
I solved this problem because of the version problem. I have no problem updating to sumo1.1.0. Thank you very much。@eugenevinitsky
