### ISSUE TITLE
Error when running python examples/rllib/stabilizing_the_ring.py

### ISSUE THREAD

**Issue by nanxintin** [flow-project/flow#603]
## Bug Description
After I install Flow and SUMO, I run " python examples/rllib/stabilizing_the_ring.py", and there is an error.

Error during start: [Errno 2] No such file or directory: '/home/noahrl/sk/flow/flow/core/kernel/scenario/debug/cfg/stabilizing_the_ring_20190709-1611201562659880.1063194.net.xml'

I found that the cfg folder is empty. How can I get the "stabilizing_the_ring_20190709-1611201562659880.1063194.net.xml" file ?

## Versions

- OS: Ubuntu 16.04
- Flow version: 0.4.0.dev0

Thanks very much.

**Comment by eugenevinitsky** [comment]
Hi @nanxintin, sorry this is happening! Could you post the entirety of the error? My suspicion is that SUMO isn't properly installed.

**Comment by nanxintin** [comment]
Hi @eugenevinitsky , I have solved the error by adding SUMO to the system PATH.
Thanks for your reply.

**Comment by clemlecornec** [comment]
Hi! 

I am currently learning flow and I have a very similar issue with a scenario I designed myself. If I manually add BaseScenario.net.xml into the cfg folder, it runs without issue. The code stabilizing_the_ring.py works also perfectly and creates automatically the file .net.xml needed in the cfg folder. Any idea of my mistake?
Thanks a lot in advance!

Here is the error:

python3 runBasicScenario.py 
Loading configuration... done.
Error: File '.../flow/flow/core/kernel/scenario/debug/cfg/BaseScenario.net.xml' is not accessible (No such file or directory).
Quitting (on error).
Error during start: Traceback (most recent call last):
  File ".../flow/flow/core/kernel/simulation/traci.py", line 155, in start_simulation
    traci_connection.setOrder(0)
  File ".../env/lib/python3.6/site-packages/traci/connection.py", line 348, in setOrder
    self._sendExact()
  File ".../env/lib/python3.6/site-packages/traci/connection.py", line 99, in _sendExact
    raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO

And here is my code:
# the TestEnv environment is used to simply simulate the network
from flow.envs import TestEnv

# the Experiment class is used for running simulations
from flow.core.experiment import Experiment

# all other imports are standard
from flow.core.params import VehicleParams
from flow.core.params import NetParams
from flow.core.params import InitialConfig
from flow.core.params import EnvParams
from flow.core.params import SumoParams

##### Running a default simulation
from flow.scenarios import Scenario

net_params_usr = NetParams(template  = {"net":"BaseScenario.net.xml","vtype": "fleetDistribution.add.xml" , "rou":"routes.rou.xml"})

# Create the remaining parameters
env_params = EnvParams()
sim_params = SumoParams(render = False, sim_step = 0.5)
initial_config = InitialConfig()
vehicles_usr = VehicleParams()

# Scenario
scenario = Scenario(name = "testBasicScenario", net_params = net_params_usr, vehicles = vehicles_usr)

# Environment
env = TestEnv(env_params = env_params, sim_params = sim_params, scenario = scenario)

# Experiment
exp = Experiment(env = env)
exp.run(1, 1000)
