### ISSUE TITLE
Visualizing emission files using time_space_diagram.py

### ISSUE THREAD

**Issue by KeithAnshilo** [flow-project/flow#608]
Hi!

Can you help on how to define the "flow_params" argument? 

I tried to the path of "params.json" to the "flow_params" argument. Is this correct?

Here's the error I got:
File "/home/daremapua/flow/flow/utils/rllib.py", line 94, in get_flow_params
    for veh_params in flow_params["veh"]:
KeyError: 'veh'

**Comment by nathanlct** [comment]
Hi @KeithAnshilo,

What is the `flow_params` argument?

The usage of the file is as follows: 

```
python time_space_diagram.py </path/to/emission>.csv </path/to/params>.json
```

**Comment by KeithAnshilo** [comment]
I followed that syntax, yet this is the error that I get;

Traceback (most recent call last):
  File "flow/visualize/time_space_diagram.py", line 422, in <module>
    flow_params = get_flow_params(args.flow_params)
  File "/home/daremapua/flow/flow/utils/rllib.py", line 94, in get_flow_params
    for veh_params in flow_params["veh"]:
KeyError: 'veh'

**Comment by kjang96** [comment]
Hi @KeithAnshilo sorry for the late response. The parameters of flow_params are passed  flow/utils/registry.py. If you look in that file, you'll see see many references to params with different keys such as params['exp_tag'], params['env_name']. Now, the parameters of flow_params need to match the key names you see in this file. Is this still an issue for you? If it is, can you give me the Flow version number. and I'll gladly look into it.
