### ISSUE TITLE
Error when running python examples/rllib/stabilizing_the_ring.py

### ISSUE THREAD

**Issue by jingyanping** [flow-project/flow#609]
hi, i am sorry to trouble you again.
when i run the python examples/rllib/stabilizing_the_ring.py, i met the problem ``DeprecationWarning: The redirect_output argument is deprecated.``

```
(flow) sean@ubuntu:~/flow$ python examples/rllib/stabilizing_the_ring.py
Traceback (most recent call last):
  File "examples/rllib/stabilizing_the_ring.py", line 128, in <module>
    ray.init(num_cpus=N_CPUS + 1, redirect_output=False)
  File "/home/sean/Downloads/enter/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 1387, in init
    _internal_config=_internal_config,
  File "/home/sean/Downloads/enter/envs/flow/lib/python3.5/site-packages/ray/parameter.py", line 147, in __init__
    self._check_usage()
  File "/home/sean/Downloads/enter/envs/flow/lib/python3.5/site-packages/ray/parameter.py", line 197, in _check_usage
    "The redirect_output argument is deprecated.")
DeprecationWarning: The redirect_output argument is deprecated.
```
@eugenevinitsky

**Comment by nathanlct** [comment]
If the argument is deprecated, then remove it.

`ray.init(num_cpus=N_CPUS + 1)`

It means that you have installed a version of `ray` more recent that the one Flow uses (i.e. `0.6.1` as mentioned in `requirements.txt`).

**Comment by jingyanping** [comment]
@nathanlct thank you very much,
When I run this program, the following is the content displayed by the terminal, but it is constantly refreshed, there is no sumo animation effect like " examples/sumo/sugiyama.py", I want to know if this is correct?

(pid=8866) 2019-07-10 18:49:50,725	INFO rollout_worker.py:428 -- Generating sample batch of size 200
(pid=8866) 
(pid=8866) -----------------------
(pid=8866) ring length: 240
(pid=8866) v_max: 4.189299083856172
(pid=8866) -----------------------
(pid=9088) 
(pid=9088) -----------------------
(pid=9088) ring length: 252
(pid=9088) v_max: 4.759762049824181
(pid=9088) -----------------------
(pid=8866) Loading configuration... done.
(pid=9088) Loading configuration... done.
(pid=8866) Success.
(pid=9088) Success.
(pid=8866) Loading configuration... done.
(pid=9088) Loading configuration... done.
(pid=8866) 2019-07-10 18:50:02,364	
......
......
(pid=8866) Success.
(pid=9088) Success.
(pid=8866) Loading configuration... 
(pid=9088) Loading configuration... 
(pid=8866) done.
(pid=9088) done.
(pid=8866) 
(pid=8866) -----------------------
(pid=8866) ring length: 251
(pid=8866) v_max: 4.71224180704279
(pid=8866) -----------------------
(pid=8866) Loading configuration... done.
(pid=8866) Success.
(pid=8866) Loading configuration... 
(pid=8866) done.
(pid=9088) 
(pid=9088) -----------------------
(pid=9088) ring length: 229
(pid=9088) v_max: 3.666034803266416
(pid=9088) -----------------------
(pid=9088) Loading configuration... done.
(pid=9088) Success.
(pid=9088) Loading configuration... done.

**Comment by nathanlct** [comment]
@jingyanping You are training a policy, there is nothing to see. If you look in the parameters, you will see `render=False`, that is why no GUI opens. This significantly speeds up the simulation during the training. If you want to see how your training is doing, please refer to tutorial 5 about visualization.

If you have other questions, please post them on StackOverflow using the tag `flow-project`, we will help you from there!

**Comment by jingyanping** [comment]
@nathanlct hi,
Thank you very much for your reply, i will follow what you said.  i still have a question ask you，when i run“python examples/rllab/stabilizing_the_ring.py”，i met the problem with “TypeError: unorderable types: tuple() <= int()”

/home/sean/Downloads/enter/envs/flow/lib/python3.5/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
python /home/sean/rllab-multiagent/scripts/run_experiment_lite.py  --use_cloudpickle 'True'  --variant_data 'gAN9cQBYCAAAAGV4cF9uYW1lcQFYLQAAAHN0YWJpbGl6aW5nLXRoZS1yaW5nXzIwMTlfMDdfMTBfMTlfNTBfNTlfMDAwMXECcy4='  --log_dir '/home/sean/rllab-multiagent/data/local/stabilizing-the-ring/stabilizing-the-ring_2019_07_10_19_50_59_0001'  --snapshot_mode 'all'  --args_data 'gASVrQkAAAAAAACMF2Nsb3VkcGlja2xlLmNsb3VkcGlja2xllIwOX2ZpbGxfZnVuY3Rpb26Uk5QoaACMD19tYWtlX3NrZWxfZnVuY5STlGgAjA1fYnVpbHRpbl90eXBllJOUjAhDb2RlVHlwZZSFlFKUKEsASwBLEEsPS0dC4gEAAHQAAGQBAGQCAGQDAGQEAGQFAGQGAIMAA30BAHQBAIMAAH0CAHwCAGoCAGQHAGQIAGQJAHQDAGkAAGYCAGQKAHQEAGkAAGYCAGQLAGQMAIMABAF8AgBqAgBkBwBkDQBkCQB0BQBpAABmAgBkCgB0BABpAABmAgBkCwBkDgCDAAQBZA8AZBAAZBEAZwIAZBIAZAwAZBMAZAwAaQMAfQMAdAYAZBQAdAcAZBUAfAMAZBYAZBcAZBgAZAQAgwAEfQQAZBkAZBoAZBsAZAwAZBwAZB0AZB4AZB8AaQQAfQUAdAgAZBUAfAUAgwABfQYAdAkAZCAAZCEAZCIAZCMAgwACfQcAdAoAZCQAdAsAgwIAAXQMAHQLAHwCAHwGAGQlAHwHAIMDAX0IAGQmAH0JAHwJAHwBAHwCAHwEAHwGAHwHAHwIAGYHAH0KAHQNAHwJAGQnAGQEAGQoAHwKAIMBAn0LAHwLAGoOAH0MAHQPAHwLAIMBAH0LAHQQAGQpAHwLAGoRAGQqAGQ3AIMAAn0NAHQSAGQpAHwLAGoRAIMAAX0OAHQTAGQsAHwLAGQtAHwNAGQuAHwOAGQvAGQwAGQxAHwMAGQyAGQzAGQ0AGQ1AIMAB30PAHwPAGoUAIMAAGYBAAFkNgBTlCiMQ0ltcGxlbWVudCB0aGUgcnVuX3Rhc2sgbWV0aG9kIG5lZWRlZCB0byBydW4gZXhwZXJpbWVudHMgd2l0aCBybGxhYi6UjAhzaW1fc3RlcJRHP7mZmZmZmZqMBnJlbmRlcpSJjARzZWVklEsAjAZ2ZWhfaWSUjAJybJSMF2FjY2VsZXJhdGlvbl9jb250cm9sbGVylIwScm91dGluZ19jb250cm9sbGVylIwMbnVtX3ZlaGljbGVzlEsBjANpZG2USxWMC3JpbmdfbGVuZ3RolEvcTQ4BjAltYXhfYWNjZWyUjAltYXhfZGVjZWyUjAdob3Jpem9ulIwRYWRkaXRpb25hbF9wYXJhbXOUjAx3YXJtdXBfc3RlcHOUTe4CjAxjbGlwX2FjdGlvbnOUjAZsZW5ndGiUTQQBjAVsYW5lc5SMC3NwZWVkX2xpbWl0lEsejApyZXNvbHV0aW9ulEsojAdzcGFjaW5nlIwHdW5pZm9ybZSMCGJ1bmNoaW5nlEsyjAhYWFggbmFtZZSMDmluaXRpYWxfY29uZmlnlIwUV2F2ZUF0dGVudWF0aW9uUE9FbnaUjAxyZWNvcmRfdmlkZW+UjA9yZWdpc3Rlcl9wYXJhbXOUjAhlbnZfc3BlY5SMDGhpZGRlbl9zaXplc5RLBYwDZW52lIwGcG9saWN5lIwIYmFzZWxpbmWUjApiYXRjaF9zaXpllE1g6owPbWF4X3BhdGhfbGVuZ3RolIwFbl9pdHKUTfQBjAhkaXNjb3VudJRHP+/3ztkWhytOSwWFlHSUKIwKU3Vtb1BhcmFtc5SMDVZlaGljbGVQYXJhbXOUjANhZGSUjAxSTENvbnRyb2xsZXKUjBBDb250aW51b3VzUm91dGVylIwNSURNQ29udHJvbGxlcpSMCUVudlBhcmFtc5SMB0hPUklaT06UjAlOZXRQYXJhbXOUjA1Jbml0aWFsQ29uZmlnlIwFcHJpbnSUjAdleHBfdGFnlIwMTG9vcFNjZW5hcmlvlIwGR3ltRW52lGgYjAlub3JtYWxpemWUjBFHYXVzc2lhbkdSVVBvbGljeZSMBHNwZWOUjBVMaW5lYXJGZWF0dXJlQmFzZWxpbmWUjARUUlBPlIwFdHJhaW6UdJQojAFflIwKc2ltX3BhcmFtc5SMCHZlaGljbGVzlIwVYWRkaXRpb25hbF9lbnZfcGFyYW1zlIwKZW52X3BhcmFtc5SMFWFkZGl0aW9uYWxfbmV0X3BhcmFtc5SMCm5ldF9wYXJhbXOUaCSMCHNjZW5hcmlvlIwIZW52X25hbWWUjAtwYXNzX3BhcmFtc5RoKmgYaCtoLIwEYWxnb5R0lIwmZXhhbXBsZXMvcmxsYWIvc3RhYmlsaXppbmdfdGhlX3JpbmcucHmUjAhydW5fdGFza5RLEkNmAAIbAgkBCQEGAQwBDAEHAQkBBgEMAQwBBwMMAQYBDAIGAQYBBgEGAQkEBgEGAQYBDAIPAhUCDQEDAQMBAwEGAQkCBgEPAQwCGAEJAQwCBgEJAQkDEgIGAQYBBgEGAQYBBgEGAgkDlCkpdJRSlEr/////fZQojAhfX2ZpbGVfX5SMJmV4YW1wbGVzL3JsbGFiL3N0YWJpbGl6aW5nX3RoZV9yaW5nLnB5lIwIX19uYW1lX1+UjAhfX21haW5fX5SMC19fcGFja2FnZV9flE51h5RSlH2UKIwEZGljdJR9lIwEbmFtZZRoVYwKa3dkZWZhdWx0c5ROjAhkZWZhdWx0c5ROjBdfY2xvdWRwaWNrbGVfc3VibW9kdWxlc5RdlIwHZ2xvYmFsc5R9lChoN4wkZmxvdy5jb250cm9sbGVycy5yb3V0aW5nX2NvbnRyb2xsZXJzlGg3k5RoPIwQZmxvdy5jb3JlLnBhcmFtc5RoPJOUaEKMInJsbGFiLnBvbGljaWVzLmdhdXNzaWFuX2dydV9wb2xpY3mUaEKTlGg4jCVmbG93LmNvbnRyb2xsZXJzLmNhcl9mb2xsb3dpbmdfbW9kZWxzlGg4k5RoM2htaDOTlGg7aG1oO5OUaEWMEHJsbGFiLmFsZ29zLnRycG+UaEWTlGg/jBNmbG93LnNjZW5hcmlvcy5sb29wlGg/k5RoQYwZcmxsYWIuZW52cy5ub3JtYWxpemVkX2VudpSMDU5vcm1hbGl6ZWRFbnaUk5RoOk24C2g0aG1oNJOUaDaMHWZsb3cuY29udHJvbGxlcnMucmxjb250cm9sbGVylGg2k5RoRIwncmxsYWIuYmFzZWxpbmVzLmxpbmVhcl9mZWF0dXJlX2Jhc2VsaW5llGhEk5RoQIwScmxsYWIuZW52cy5neW1fZW52lGhAk5RoOWhtaDmTlGg+jBRzdGFiaWxpemluZy10aGUtcmluZ5R1jAthbm5vdGF0aW9uc5R9lIwOY2xvc3VyZV92YWx1ZXOUTowDZG9jlGgLjAZtb2R1bGWUaF2MCHF1YWxuYW1llGhVdXRSLg=='  --exp_name 'stabilizing-the-ring_2019_07_10_19_50_59_0001'  --seed '5'  --n_parallel '1'
/home/sean/Downloads/enter/envs/flow/lib/python3.5/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
using seed 5
2019-07-10 19:51:03.188182 PDT | Setting seed to 5
using seed 5
XXX name stabilizing-the-ring
Loading configuration... done.
Success.
Loading configuration... done.
2019-07-10 19:51:06.435119 PDT | [stabilizing-the-ring_2019_07_10_19_50_59_0001] observation space: Box(3,)
2019-07-10 19:51:06.435715 PDT | [stabilizing-the-ring_2019_07_10_19_50_59_0001] action space: Box(1,)
Traceback (most recent call last):
  File "/home/sean/rllab-multiagent/scripts/run_experiment_lite.py", line 137, in <module>
    run_experiment(sys.argv)
  File "/home/sean/rllab-multiagent/scripts/run_experiment_lite.py", line 121, in run_experiment
    method_call(variant_data)
  File "examples/rllab/stabilizing_the_ring.py", line 73, in run_task
    hidden_sizes=(5, ),
  File "/home/sean/rllab-multiagent/rllab/policies/gaussian_gru_policy.py", line 50, in __init__
    output_nonlinearity=output_nonlinearity,
  File "/home/sean/rllab-multiagent/rllab/core/network.py", line 228, in __init__
    b=l_output_flat.b,
  File "/home/sean/Downloads/enter/envs/flow/lib/python3.5/site-packages/lasagne/layers/dense.py", line 64, in __init__
    super(DenseLayer, self).__init__(incoming, **kwargs)
  File "/home/sean/Downloads/enter/envs/flow/lib/python3.5/site-packages/lasagne/layers/base.py", line 44, in __init__
    if any(d is not None and d <= 0 for d in self.input_shape):
  File "/home/sean/Downloads/enter/envs/flow/lib/python3.5/site-packages/lasagne/layers/base.py", line 44, in <genexpr>
    if any(d is not None and d <= 0 for d in self.input_shape):
TypeError: unorderable types: tuple() <= int() @nathanlct

**Comment by nathanlct** [comment]
As I said, please post your other questions on StackOverflow using the tag `flow-project`, one question per post, I and the other contributors will be happy to help you there.

As a side note, please wrap your logs into triple backquotes like this, here and on Stackoverflow:

```
` ` `
logs here (remove the spaces between the backquotes)
` ` `
```

It will make it much easier for us to read them.
