### ISSUE TITLE
How to define various Traffic Scenarios ?

### ISSUE THREAD

**Issue by nanxintin** [flow-project/flow#614]
Hi,

Could you give me some suggestions on how to define various traffic scenarios ? Especially those for multi-agent learning. 

Thanks.

**Comment by eugenevinitsky** [comment]
Hi @nanxintin,

Could you explain slightly more what you want? There are two different things it sounds like:
(1) Traffic scenarios: the actual road construction, which edges vehicles start from, what the vehicle flows look like, etc.
(2) How to define an RL environment, which specifies the rewards, actions, and states of the system.

Which one are you referring to?

**Comment by nanxintin** [comment]
Hi @eugenevinitsky ,

Thanks for your reply.
I have just looked through the tutorials, which includes the two things you mentioned above.
I want to train multiple autonomous vehicles with RL in the flow, while the multi-agent scenarios and examples are not clear enough at present. The multiagent_figure_eight example has one autonomous vehicle and an adversary vehicle.  This is different from classical multi-agent control, such as StarCraft. If I want to train all the agents in the flow scenarios, such as figure_eight or merge, is this available ?  If so, could you tell me what should I do ?
Thanks.

**Comment by eugenevinitsky** [comment]
So, it sort of depends on the exact scenario you want. The two example scripts in the multi-agent folder show to to create the policy graph that is assigned to the agents. Then, in your step function you need to return a dictionary of observations for each agent that you are training, and in your apply_rl_action method you need to use the action for each agent that was in the dictionary of observations. The rllib multi-agent guide may be helpful: 
https://ray.readthedocs.io/en/latest/rllib-env.html

If you have more specifics on what you're trying to do, I can try to be more specific. I'll also be writing up a multi-agent tutorial over the next few days.

**Comment by nanxintin** [comment]
Hi @eugenevinitsky, the controller in the grid0.py baseline is used to control the traffic lights.
How can I control multiple vehicles in the grid scenario? Is there any  open intersection scenario used for multi-agent negotiation in Flow?
Thanks.

**Comment by eugenevinitsky** [comment]
Oh my, I'm so sorry I missed this! You would have to do two things:
(1) In the run script you would have to add a policy graph for the vehicles similar to how it is done for the lights
(2) You would have to extend the _apply_rl_actions method in the environment to take the actions from the vehicles and actually apply them. For an example of that, look at any environment beside the grid environment.

**Comment by nanxintin** [comment]
@eugenevinitsky  Thanks for your reply. I will working on this with your suggestions.
