### ISSUE TITLE
Aimsun training not working when loading a template via load.py

### ISSUE THREAD

**Issue by nathanlct** [flow-project/flow#621]
## Bug Description

In `core/kernel/vehicle/aimsun.py`, in `_add_departed`:

- RL vehicles generated by Aimsun (via arbitrary type name "rl" for instance) are not associated to an RLController class in Flow, thus they are not really RL vehicles

- all vehicles are added in `self.__human_ids`, which is not true for RL vehicles

It is the same if we want some human vehicles to be controlled by Flow - we need to define an arbitrary type name to Flow controller mapping in order to assign the right controllers.

**Comment by AboudyKreidieh** [comment]
this is pretty outdated and likely resolved (a lot of work has gone into load.py since)
