### ISSUE TITLE
Testing order in travis builds

### ISSUE THREAD

**Issue by cathywu** [flow-project/flow#633]
## Feature Description

We current check for flake8 and pydocstyle issues before actually running the unit tests. Can we consider running them afterwards? Folks may spend a lot of time re-formatting and stylizing code before realizing that the implementation was broken in the first place.

I suggest moving the following lines:
https://github.com/flow-project/flow/blob/0cee1b9cf427a409ec2fc5287626c6e28982d46d/.travis.yml#L51-L54

To:
https://github.com/flow-project/flow/blob/0cee1b9cf427a409ec2fc5287626c6e28982d46d/.travis.yml#L60-L61

**Comment by cathywu** [comment]
I realized that one downside is that it takes a lot longer to get the formatting / style errors, if one needs to wait for all the unit tests to run through. Alternatively, can we have a separate travis build that just does the style / format checks?

**Comment by cathywu** [comment]
Or, can we have the travis build continue to the unit tests even if the linting fails?

**Comment by nathanlct** [comment]
Good idea! Maybe it would even be possible to run flake8 and pydoc before installing the whole environment (ie in before_install), with just the packages we need (flake8, pydocstyle, maybe some other things) since they should run quite fast while building everything takes ~5 minutes each time.

**Comment by cathywu** [comment]
+++ yes, that would be fantastic!

**Comment by AboudyKreidieh** [comment]
resolved by #634
