### ISSUE TITLE
Deprecate RLlab

### ISSUE THREAD

**Issue by eugenevinitsky** [flow-project/flow#637]
It's time to kill RLlab. We're not using it anymore nor testing it and it's causing errors for users that we can reproduce. Thoughts? @AboudyKreidieh @fywu85 @cathywu and anyone else?

**Comment by AboudyKreidieh** [comment]
based on discussions we've had during group meetings, the plan is to deprecate rllab in flow 0.5.0

**Comment by eugenevinitsky** [comment]
Nice. Okay.

**Comment by cathywu** [comment]
FYI it looks like a project called garage as succeeded rllab: https://github.com/rlworkgroup/garage. Maybe worth checking out.
