### ISSUE TITLE
Example scripts for openAI Baselines integration/Dopamine

### ISSUE THREAD

**Issue by eugenevinitsky** [flow-project/flow#638]
https://github.com/openai/baselines is a pretty common starting point for RL training. It'd be neat to integrate it. Alternately, we could also integrate Google's Dopamine: https://github.com/google/dopamine

The process would be:
(1) Add an example script that successfully uses one of these frameworks. 
(2) Add a link to how to use it to the setup instructions.

**Comment by cathywu** [comment]
Relatedly, we can integrate with https://github.com/hill-a/stable-baselines.

**Comment by cathywu** [comment]
I do really like the idea of supporting a library with lightweight implementations of RL methods.

**Comment by cathywu** [comment]
Another library to consider is garage (https://github.com/rlworkgroup/garage) based on rllab. See also #637 .

**Comment by eugenevinitsky** [comment]
Yeah, since we've already built all this support for rllib garage makes sense!
