### ISSUE TITLE
flow environment vs flow-rllab environment

### ISSUE THREAD

**Issue by lucfisc** [flow-project/flow#64]
In https://github.com/flow-project/flow/blob/master/docs/source/flow_setup.rst
we are installing two environment, one is from (https://github.com/cathywu/rllab-multiagent.git) and the other one from flow (https://github.com/flow-project/flow.git).

I installed both those environement and both seems to make rllab work.
 Is there any difference between those two ? 

Thanks

**Comment by eugenevinitsky** [comment]
Good catch; this is a mistake. We meant to remove the instruction about the rllab environment.yml

**Comment by eugenevinitsky** [comment]
Resolved, thanks for pointing this out!
