### ISSUE TITLE
Different outputs in different version of Ubuntu

### ISSUE THREAD

**Issue by cspatharis** [flow-project/flow#672]
Hello,

I'm facing a problem in the past few days. I am running the same experiment in 4 different PCs (2 with Ubuntu 16.04 and 2 with Ubuntu 18.04) and while the 2 Ubuntu 16.04 PCs manage to solve the problem perfectly, the Ubuntu 18.04 PCs behave differently.

Specifically, I'm running a multi-agent RL experiment where I have removed all the safety measures and collision are allowed. The goal is for every agent to learn its policy in order to resolve all the collisions. 

The problem arises when I'm running the experiments on the Ubuntu 18.04 machines where my algorithm converges to 20+ collisions, while on the other hand the Ubuntu 16.04 PCs manage to result to 0 collisions. Of course, I've run the same experiment to all the PCs and I've tried it a lot of times. I've also checked and copy-pasted the code to be exactly the same to all PCs.

Is this a known bug between the two versions?

Thanks in advance :)

**Comment by eugenevinitsky** [comment]
Hello, this is extremely strange! Is there any way you could give us access to the scripts you are running so that we can test it? 
At the moment the only possible error I can imagine is that the SUMO version between the machines is different.

**Comment by cspatharis** [comment]
I've mad a mistake to my algorithm, but it is still weird how the one managed to solve my problem. Anyway, sorry for the false alarm. :)
