### ISSUE TITLE
Decentralized multiagent_figure8 

### ISSUE THREAD

**Issue by nanxintin** [flow-project/flow#673]
Hi, 
I am working on decentralized multi-agent training process.

In the examples/rllib/multiagent_exps, the multiagent_figure_eight.py has one autonomous vehicle and an adversary, which is different from the cooperative multi-agent setting.
I want to train multiple vehicles with decentralized PPO method, where agents can share the learning policy. 
I refer to the "https://flow.readthedocs.io/en/latest/multiagent.html", and change the apply_rl_actions, compute_reward and get_state function according to it.
In the multiagent_figure_eight.py, I refer to examples/rllib/multiagent_exps/multiagent_stabilizing_the_ring.py, and change the policy_graphs, policy_mapping_fn, and policies_to_train in config.update( ) .
While there is an error saying "ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all() " when executing the "self.k.vehicle.apply_acceleration(rl_ids, rl_action_list)".

I would appreciate it very much if anyone could help me.
Thanks a lot.

**Comment by eugenevinitsky** [comment]
Hi @nanxintin, 

Happy to help. It looks like you're extremely close, this is a minor bug. Could you give us the entire error? It's very hard to debug without it. I'd also recommend just setting a breakpoint break that line and checking that the values in rl_action_list are what you'd expect them to be.

**Comment by eugenevinitsky** [comment]
Finally, if you open a PR I can actually step through your code and see what is going on.

**Comment by nanxintin** [comment]
Hi @eugenevinitsky, I check the values in rl_action_list, and change the action_space function to solve the bug. Thanks again.

**Comment by KidTrunks** [comment]
Hi, I am also getting your problem except I am running /multiagent_stabilizing_the_ring.py

![ValueError](https://user-images.githubusercontent.com/45654203/64058192-f41f7980-cbea-11e9-9297-85e27dfd0e8d.PNG)

Could you please clarify what exactly you changed that solved this problem?

I would greatly appreciate your help. Thanks!

**Comment by eugenevinitsky** [comment]
In your envs _apply_rl_action method, look at the values you are returning for the vehicle ids and for the accelerations.

**Comment by nanxintin** [comment]
Hi @KidTrunks, you can  refer to the new example of multiagent_highway and flow/multiagent_envs/highway.py.

**Comment by KidTrunks** [comment]
Turns out I had 2 AVs in the ring road when the environment MultiWaveAttenuationPOEnv only supports 1 AV on each ring. Thanks for the help @nanxintin  and @eugenevinitsky . The problem is now solved :)

One more unrelated question @eugenevinitsky . Is there a way to train multiple AVs on a single ring road? If so, is there an example script? Which environment do i use? 

I am trying to stabilize a single ring road with humans and multiple trained AVs similiar to the "Platooning" sample videos here: https://sites.google.com/view/ieee-tro-flow/home

Thanks again for your help!
