### ISSUE TITLE
Upgrade Ray to 0.7.3

### ISSUE THREAD

**Issue by kjang96** [flow-project/flow#687]

**Comment by kjang96** [comment]
Some things I've found:

State spaces max and min values are strictly enforced now, so they need to be clipped. Something like if ```isinstance(self.action_space, Box):
                rl_actions = np.clip(
                    rl_actions,
                    a_min=self.action_space.low,
                    a_max=self.action_space.high)``` works. 

The `redirect_output` arg from ray.init is deprecated, and we should remove this.

**Comment by AboudyKreidieh** [comment]
resolved
