### ISSUE TITLE
Rllib "Stabilizing the Ring" experiment AV not working as intended 

### ISSUE THREAD

**Issue by KidTrunks** [flow-project/flow#701]
**This is a:** Question

**OS:** Ubuntu 18.04

**SUMO Version:** b'v0_31_0-812-g1d4338ab80'

**Describe the Issue:**
Hi I am trying to recreate the "Stabilizing the Ring" experiment almost identical to these videos you guys have provided: 
https://sites.google.com/view/ieee-tro-flow/home

**However**, the AVs in my simulation do not show any signs of stabilizing the ring road. 

I have used the following **settings** in my simulation:
No. of Human Drivers: 19
No. of Automated Vehicles: 1
Ring length: 240
Horizon: 3600
Noise: 0.2 
Perturbations: 0
Vmax: 30
Total No. of Iterations: 500

Using the "**Plotting Reward Function**" it can be seen that the reward_mean has converged at around 440 iterations. 
![Capture](https://user-images.githubusercontent.com/45654203/63631676-4eaa5a00-c66e-11e9-98ba-610b19680b1f.PNG)

Using the "**Replaying a Trained Policy Function**," I have attached 3 videos for the simulations at 200, 440 and 500 iterations respectively. Videos can be found below. 

https://www.youtube.com/watch?v=0oq0_6-Hdoo
https://www.youtube.com/watch?v=liXu7lcbSek
https://www.youtube.com/watch?v=IP2eyYTY5zk

The AV can be seen to be "stuttering" and "stopping" constantly, leading to congestion. 

What could be the problem in this case? Is it something wrong with my code or am I not running enough iterations? Any help or suggestions would be greatly appreciated.

Thanks.

**Comment by eugenevinitsky** [comment]
Hi @KidTrunks, thanks for the thorough details on this issue. I'm going to set up a test this week that should help us debug why this is happening, but in the meantime, @AboudyKreidieh, do you have any ideas? I'm guessing you're the person who trained this model most recently.

**Comment by eugenevinitsky** [comment]
@KidTrunks, what does the policy look like at the point at which the episode reward mean was maximized?

**Comment by KidTrunks** [comment]
Hi @eugenevinitsky  are you asking about the values for the policy_loss graph? If so it is: **smoothed:** 0.01944 **Value:** 0.0217 **Step:** 25.92M

**Comment by eugenevinitsky** [comment]
Ah, no, I mean if you visualize the performance of the policy in a video at that point, how does it look? Should be at a pretty early iteration.

**Comment by KidTrunks** [comment]
Hi @eugenevinitsky the point at which the reward_mean has maximized is around 40 iterations. 

I have posted the video here please have a look: 
https://www.youtube.com/watch?v=u9FApsudySU

It looks better than before however, the gap between AV and human still seems a bit wide? 
Also, I thought AVs perform better given more iterations but it seems like it is not the case; but rather optimizes after only a 30-40 iterations?

**Comment by KidTrunks** [comment]
Hi, the issue was solved after updating FLOW to 0.4.0 and reinstalling SUMO. AV performing as intended. The issue may be related to #702 .
Thank you for the help!
