### ISSUE TITLE
visualizer_rllib incompatible with multiagent for newest version of ray

### ISSUE THREAD

**Issue by kjang96** [flow-project/flow#710]
## Bug Description

In line 66 of visualizer_rllib.py, the code checks if a policy is multiagent by looking at whether or not `config.get('multiagent', {}).get('policy_graphs', {})` exists. The second key, 'policy_graphs', no longer exists. Instead, put 'policies.'

## Bug Reproduce

Full error output log:

```
error log
```

## Screenshots

Screenshots:

![picture name](https://link/to/screenshot)

**Comment by AboudyKreidieh** [comment]
This is resolved in the latest version of flow.
