### ISSUE TITLE
Tutorial page has wrong link

### ISSUE THREAD

**Issue by ugurkanates** [flow-project/flow#716]
## Bug Description

6th tutorial about how to create custom enviroments is replaced on repository with Networks from OpenStreetMap(7th repo) which led all liks in tutorial page to be broken pages.

https://flow-project.github.io/tutorial.html

**Comment by ashkan-software** [comment]
Thank you @ugurkanates  for bringing this up. We will fix this. I believe this is due to a recent PR that updated the tutorials. 
@kjang96 could you look into this?  A PR to fix the website can be sumitted to the "website Github", to replace the links with the correct ones.
