### ISSUE TITLE
Passing a Env instance to flow_params when using rllib

### ISSUE THREAD

**Issue by temetski** [flow-project/flow#718]
Currently, flow only accepts strings when passing Env names to register in `gym`. A consequence of this is that anyone wishing to add new classes would have to modify the `__init__.py` files of `flow.envs`, and add new modules directly in the flow namespace. If instead we can pass class objects directly to `flow_params`, users can gain much more flexibility in extending the functionality of flow without tinkering with flow's source code. (see #192)

One possible way to attack this problem would be by modifying `make_create_env` directly. Any class has a `__module__` and `__name__` attribute, which can then be combined as 
```
entry_point = Class.__module__ + ':' + Class.__name__
```
This string can then be passed safely to `gym.envs.registration.register`.

**Comment by eugenevinitsky** [comment]
Yes this is really good! Especially if we want users to be able to pip install flow this makes sense.

**Comment by temetski** [comment]
I'll get a pull request ready. I'll start by overloading the `env_name` key first, so that we maintain compatibility with how Env names are currently passed, and see how you guys want to branch out from there.

**Comment by eugenevinitsky** [comment]
Thanks! This is super helpful.

**Comment by temetski** [comment]
Closed by #719
