### ISSUE TITLE
Error in flow/flow/core/kernel/vehicle/traci.py line 908 - Why are we passing 1e-3 for the duration?

### ISSUE THREAD

**Issue by mtgibson2014** [flow-project/flow#723]
I'm trying to simply run "python examples/sumo/sugiyama.py" and I'm getting an issue with something related to a function in the kernel. It seems like in "apply_acceleration" we are passing in a decimal -- 1e-3 , when the traci code is expecting an integer. Was I suppose to install/update something within the last months or is this an error in Flow?

**Code Snippet**
-------------------
`def apply_acceleration(self, veh_ids, acc):
        """See parent class."""
        # to hand the case of a single vehicle
        if type(veh_ids) == str:
            veh_ids = [veh_ids]
            acc = [acc]

        for i, vid in enumerate(veh_ids):
            if acc[i] is not None and vid in self.get_ids():
                this_vel = self.get_speed(vid)
                next_vel = max([this_vel + acc[i] * self.sim_step, 0])
                self.kernel_api.vehicle.slowDown(vid, next_vel, 1e-3)`
--------------------

The last line: 
`self.kernel_api.vehicle.slowDown(vid, next_vel, 1e-3)` 

is giving me an error because 1e-3 is not an integer. 

-----------
The traci code for this function has: 
`def slowDown(self, vehID, speed, duration):
        """slowDown(string, double, int) -> None

        Changes the speed smoothly to the given value over the given amount
        of time in ms (can also be used to increase speed).
        """
        self._connection._beginMessage(
            tc.CMD_SET_VEHICLE_VARIABLE, tc.CMD_SLOWDOWN, vehID, 1 + 4 + 1 + 8 + 1 + 4)
        ####### DEBUGGING #######
        import ipdb; ipdb.set_trace()
        #########################
        self._connection._string += struct.pack(
            "!BiBdBi", tc.TYPE_COMPOUND, 2, tc.TYPE_DOUBLE, speed, tc.TYPE_INTEGER, duration)
        self._connection._sendExact()`
---------------

And I'm assuming that for: 
`self._connection._string += struct.pack(
            "!BiBdBi", tc.TYPE_COMPOUND, 2, tc.TYPE_DOUBLE, speed, tc.TYPE_INTEGER, duration)`

it expects that duration is an integer. 

**Output log:**
<img width="772" alt="Screen Shot 2019-09-17 at 5 57 41 PM" src="https://user-images.githubusercontent.com/7775864/65095120-b9e90280-d974-11e9-9a87-51764f052a54.png">

**Comment by AboudyKreidieh** [comment]
Sumo changed the third input of `slowDown` in version 1.0.0 to required as input seconds instead of milliseconds, and since then we have replaced the 1 values with a 1e-3. You are probably still using sumo-0.31. I recommend you remove any sumo binaries you have on your laptop and reinstall them following our setup instructions

**Comment by mtgibson2014** [comment]
Thank you! It's fixed now.
