### ISSUE TITLE
Need to fix/relocated intersection.py in "flow/flow/scenarios/intersection.py" since the scenarios folder has been deprecated..

### ISSUE THREAD

**Issue by mtgibson2014** [flow-project/flow#724]
In the file "flow/flow/scenarios/intersection.py" we subclass Scenario from "flow.scenarios.base_scenario". However, because the folder has been deprecated, we need to fix the file, and then relocate our file to the new "Network" file.

**Comment by mtgibson2014** [comment]
Alben and I will work on this - this is for Toyota.

**Comment by eugenevinitsky** [comment]
Is this an active bug in the master branch?

**Comment by mtgibson2014** [comment]
This is no longer a bug. Thanks!
