### ISSUE TITLE
Plotting non-learning data in TensorBoard

### ISSUE THREAD

**Issue by Antonio-Dominguez** [flow-project/flow#736]
Thanks to TensorBoard, I am able to visualize some learning parameters such as the mean reward, entropy, etc. I was wondering if there's a way to plot custom data as the number of standstill vehicles in a given intersection, the global delay, mean travel time and other non-learning sets of data (more related with the simulation itself and not with the learning process).

- Is it possible? If yes, where should I place the piece of code? I've thought that I might send the data every time step to the "progress.csv" since these parameters should be computed continuously, so maybe  `green_wave_env.py`?
- Do I have to do it via Ray or via TensorFlow?
- Where's defined the list of dataset plotted in TensorBoard? Is it a list set by default or can I customize it?

I know that I can produce the file `emissions.xml` but it is not the kind of data that I am looking for.

Thank you in advance!

**Comment by eugenevinitsky** [comment]
Yes! We don't have it yet but we would LOVE this feature. Here's a guide to how you can do it:
(1) Store the relevant info in the info dict that is returned in base_envs step function
(2) Log it to tensorboard like so: https://ray.readthedocs.io/en/latest/rllib-training.html?highlight=callback#python-api

**Comment by Antonio-Dominguez** [comment]
Alright! I'm gonna work on that and I will let you know. Thank you!

**Comment by eugenevinitsky** [comment]
@Antonio-Dominguez, we've started up a Flow Users slack channel that we think should be an easier way to interact with us. If you want to join, link is here! https://join.slack.com/t/flow-users/shared_invite/enQtNzk5NzE1OTkyNTE0LTU0YmE5ZTVkZmJmNDg1Nzg2YThjOThmY2ZlYWE2ZjQ0NTE1NjE3Y2YwMTljY2U5M2Y3MDhmMWUzZDM3YWViNmE

**Comment by Antonio-Dominguez** [comment]
See #825
