### ISSUE TITLE
Add python2 compatibility back-support

### ISSUE THREAD

**Issue by fywu85** [flow-project/flow#74]
This could improve the accessibility of the software. Sometimes users do not have python3 installed or unconsciously installed everything with python2, e,g., when `sudo python setup.py develop` where the default `sudo python` is python2. This compatibility support would make the software still runnable even when users deviate from the recommended installation procedure.

**Comment by AboudyKreidieh** [comment]
since python2 is dying soon, I highly recommend we don't waste time on this

**Comment by eugenevinitsky** [comment]
+1, lets close this.
