### ISSUE TITLE
Update setup_aimsun.sh script

### ISSUE THREAD

**Issue by Yasharzf** [flow-project/flow#743]
## Bug Description

Conda has removed python 2.7.4 from its existing channels. As a result, when we run setup_aimsun.sh, we get an error.

## Bug Reproduce

File in which the bug occurred: `setup_aimsun.sh`

The exact command that you did run that caused the bug:
`setup_aimsun.sh`

## Output Log
Full error output log:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - python=2.7.4```

**Comment by AboudyKreidieh** [comment]
hi @Yasharzf I've picked up this issue with @albenbagabaldo and told him how to fix it / asked him to PR the solution. Essentially though, you need to run this:

```
conda config --append channels https://repo.anaconda.com/pkgs/free
conda config --append channels https://repo.anaconda.com/pkgs/pro
```

**Comment by temetski** [comment]
Is there any particular reason to pin it to 2.7.4? I actually noticed this when setting up aimsun, and just forced python to use 2.7.16 and i was able to run the example scripts.

**Comment by Yasharzf** [comment]
In the older versions of Aimsun we had to install python 2.7.4, but it is not an issue anymore. I am using 2.7.13 and it works fine. We don't need to append the channel to Conda. We can just replace 2.7.4 with another version like 2.7.13.

**Comment by eugenevinitsky** [comment]
Does aimsun not support python 3? This will be a problem in the near future.

**Comment by Yasharzf** [comment]
As far as I know they are working on it.
