### ISSUE TITLE
[Tutorial07] File directory for LuSTScenario is incorrect

### ISSUE THREAD

**Issue by NickL77** [flow-project/flow#747]
In Tutorial07, the path to fetch LuSTScenario's xml files are incorrect. They currently point to `/network/`, but as the [repo](https://github.com/lcodeca/LuSTScenario) shows, it should repo be replaced with `/scenario/`.

Also, as a minor note, the current version of the ipynb includes code blocks that have already been run. Those can be cleaned up.

**Comment by AboudyKreidieh** [comment]
The PR associated with this issue has been merged. Thank you again for bringing this to light.
