### ISSUE TITLE
Calculation of inflow_rate and outflow_rate

### ISSUE THREAD

**Issue by buechelmartin** [flow-project/flow#749]
## Bug Description
Seems to me that there is something the wrong way round in the following code within tracy.py

` def get_inflow_rate(self, time_span):
        """See parent class."""
        if len(self._num_departed) == 0:
            return 0
        num_inflow = self._num_departed[-int(time_span / self.sim_step):]
        return 3600 * sum(num_inflow) / (len(num_inflow) * self.sim_step)`

`def get_outflow_rate(self, time_span):
        """See parent class."""
        if len(self._num_arrived) == 0:
            return 0
        num_outflow = self._num_arrived[-int(time_span / self.sim_step):]
        return 3600 * sum(num_outflow) / (len(num_outflow) * self.sim_step)
`
    

Outflow rate should be from departed vehicles and inflow from arrived.

**Comment by eugenevinitsky** [comment]
Yeah, sorry for the confusion. So, the way SUMO names things is kind of odd. Arrived vehicles are vehicles that have left the system, departed vehicles are vehicles that have just entered the system. Hope that clears things up.

**Comment by buechelmartin** [comment]
Oh thanks I just realized by having a closer look to the rest of the code. Sorry for that!

**Comment by buechelmartin** [comment]
Still trying to find the explanation for some weird finding I made.

Now I stepped over the following 

`            # updated the list of departed and arrived vehicles
            self._num_departed.append(
                len(sim_obs[tc.VAR_DEPARTED_VEHICLES_IDS]))
            self._num_arrived.append(len(sim_obs[tc.VAR_ARRIVED_VEHICLES_IDS]))
            self._departed_ids.append(sim_obs[tc.VAR_ARRIVED_VEHICLES_IDS])
            self._arrived_ids.append(sim_obs[tc.VAR_ARRIVED_VEHICLES_IDS])`

But here it should be self._departed_ids. ... VAR_DEPARTED_VEHICLES_IDS, no? Sorry if I am just overworked ;-)

**Comment by buechelmartin** [comment]
This would not explain my finding. Therefore my next question:
Does 
sim_obs[tc.VAR_ARRIVED_VEHICLES_IDS]
contain the RL vehicles too? The outflow rate on examples with just human vehicles is much bigger in my experiments, although the average velocity is a lot smaller.

**Comment by eugenevinitsky** [comment]
Hi, I think you may be slightly behind master. That's a bug that was fixed a month or so ago. The codebase now reads:

            self._num_departed.append len(sim_obs[tc.VAR_DEPARTED_VEHICLES_IDS]))
            self._num_arrived.append(len(sim_obs[tc.VAR_ARRIVED_VEHICLES_IDS]))
            self._departed_ids.append(sim_obs[tc.VAR_DEPARTED_VEHICLES_IDS])
            self._arrived_ids.append(sim_obs[tc.VAR_ARRIVED_VEHICLES_IDS])

**Comment by eugenevinitsky** [comment]
Also, yes, it will contain both the RL and the human vehicles.

**Comment by ctc199625** [comment]
I open terminal and activate the flow,when I start to input python examples/rllib/figure-eight,the surface show the mistake about     Couldn't import `requests` library. Be sure to install it on the client side. 
Maybe I need some help.I just started last week.Thank you!!

**Comment by eugenevinitsky** [comment]
Uh, which file is importing the requests module?

**Comment by eugenevinitsky** [comment]
@ctc199625 could you open a separate issue? This seems unrelated to the previous issue.
