### ISSUE TITLE
[Aimsun] Flow cannot be run outside flow directory when running Aimsun

### ISSUE THREAD

**Issue by temetski** [flow-project/flow#752]
## Bug Description

Because Aimsun uses python2.7, flow is not visible as a module. When flow is run outside the flow directory, and a call to `flow/utils/aimsun/load.py` is made, it is unable to find `flow.utils.aimsun.scripting_api` and `flow.config` as flow is not installed as a python 2.7 module.

This would easily be fixed if Aimsun uses python 3.

## Bug Reproduce

File in which the bug occurred: `flow/utils/aimsun/load.py`

The exact command that you did run that caused the bug:
`python flow/examples/aimsun/grid.py`
(or any aimsun related script)

## Screenshots

Screenshots:
![image](https://user-images.githubusercontent.com/6328105/66418483-0db89b80-e9b7-11e9-8ac8-7f00c23eb5c0.png)

## Versions

- OS: macOS Mojave
- Flow version: 0.5.0.dev
- Flow commit number: 375fac9b

**Comment by Yasharzf** [comment]
We need to switch to External Agent Interface of Aimsun which can help us avoid dealing with python 2.7 issues. But for now, you can export the path to PYTHONPATH (`export PYTHONPATH="/path/to/flow:$PYTHONPATH"`). We need to add to this to the installation docs.

**Comment by temetski** [comment]
I'll work on a PR for this.

**Comment by Yasharzf** [comment]
Great! Thanks!

**Comment by temetski** [comment]
Addressed by #753.
