### ISSUE TITLE
Keeping agents in osm map during episode

### ISSUE THREAD

**Issue by nicofirst1** [flow-project/flow#755]
## Feature Description

I'm currently using flow to train a MAS system with _MADDPG_ algorithm ([here](https://gitlab.com/nicofirst1/mas_traffic)). During the sampling I get [this](https://github.com/ray-project/ray/issues/5913) error which is due to the RL agents being removed during the episode. 
Since I'm using an imported OSM map neither the _MinicityRouter_ nor the [\_reroute_if_final_edge](https://github.com/flow-project/flow/blob/master/flow/envs/traffic_light_grid.py#L443) are working to prevent the Agents to be deleted from the map.

It would be nice to have a method for doing this  on OSM maps too.

**Comment by eugenevinitsky** [comment]
Hi @nicofirst1, in terms of a quick fix, would it work to have an inflow of vehicles in your system or do you need there to be a fixed number of vehicles in your system at all times? If the latter, we can push a fix to add such an option to OSM maps.

**Comment by nicofirst1** [comment]
Unfortunately I need to have a fixed number of RL vehicles during the episode.

**Comment by eugenevinitsky** [comment]
I see. Would it be sufficient to just check if the edge is the final edge in your list of routes and return it to the first element in the route?

**Comment by nicofirst1** [comment]
Yes, as long as I have a constant number of agents during the episode.

**Comment by nicofirst1** [comment]
Any update on this?

**Comment by eugenevinitsky** [comment]
Yep! It'll take a bit longer to get it merged in (need to write unit tests for it) but I've opened a PR #759 that gives an example of how you might do this. Hope that helps!

**Comment by eugenevinitsky** [comment]
Hi, I'm closing this for now. Hoping your project got finished up alright!
