### ISSUE TITLE
How to use my personal deep reinforcement algorithm to control RL cars?

### ISSUE THREAD

**Issue by ZJP1993** [flow-project/flow#764]
In tutorial 3, PPO is the default algorithm to control RL cars. I want to use a new kind of deep reinforcement algorithm to improve performance of RL cars. I already have some ideas about modifying algorithm, but I dont know how to modify code to apply my ideas.
Thanks ^_^

**Comment by eugenevinitsky** [comment]
HI @ZJP1993, the easiest way to do it is to write a custom algorithm in RLlib/stable baselines or modify one of their algorithms. Both libraries have a bunch of documentation on writing custom algorithms.

**Comment by eugenevinitsky** [comment]
Once you have that custom algorithm, each of our run scripts has an alg_run parameter that you can replace with the name of your algorithm.

**Comment by ZJP1993** [comment]
@eugenevinitsky  thank you very much
