### ISSUE TITLE
Create a user slack channel

### ISSUE THREAD

**Issue by eugenevinitsky** [flow-project/flow#768]
We need to 
- [x] Create the slack channel
- [ ] Create a form for applying to join it (or make it open)
- [ ] Add a link to the github and the website.

**Comment by eugenevinitsky** [comment]
Link here: https://join.slack.com/t/flow-users/shared_invite/enQtNzk5NzE1OTkyNTE0LTU0YmE5ZTVkZmJmNDg1Nzg2YThjOThmY2ZlYWE2ZjQ0NTE1NjE3Y2YwMTljY2U5M2Y3MDhmMWUzZDM3YWViNmE

**Comment by eugenevinitsky** [comment]
Resolved.

**Comment by HenryJia** [comment]
Apparently the link is no longer active?
