### ISSUE TITLE
I cannot find the reward function

### ISSUE THREAD

**Issue by ZJP1993** [flow-project/flow#771]
Recently I tried to modify flow examples which are based on RLlib. But I cannot find where the reward function is. I tried to find the reward function in which .py file but failed...
Thanks ^_^

**Comment by ZJP1993** [comment]
I got it...   When I search "reward" in this repository, I find the formula of reward function.

**Comment by eugenevinitsky** [comment]
The reward functions are defined in each of the env files. So the function you are looking for is compute_reward. For example, look at compute_reward here: https://github.com/flow-project/flow/blob/master/flow/envs/bay_bridge.py

**Comment by ZJP1993** [comment]
@eugenevinitsky  Thank you for your guidance ^_^
