### ISSUE TITLE
Import bug in tutorial 8.

### ISSUE THREAD

**Issue by gmarceaucaron** [flow-project/flow#782]
## Bug Description

There is an import bug in tutorial 8: environments. In cell 10, we import `LoopNetwork` while it should be `RingNetwork`.

## Bug Reproduce
The bug occurs in `tutorial08_environments.ipynb` when I run the following command
`from flow.networks.ring import LoopNetwork, ADDITIONAL_NET_PARAMS`

## Output Log
```
ImportError: cannot import name 'LoopNetwork'
```

## Versions
- OS: Ubuntu 19.10
- Flow version: 0.5.0.dev
- Flow commit number: #775

**Comment by eugenevinitsky** [comment]
Thanks for catching this! This is fixed in #786
