### ISSUE TITLE
replace sumo_binary with render

### ISSUE THREAD

**Issue by AboudyKreidieh** [flow-project/flow#81]
render is the most common phrase in similar software architectures when specifying whether to use the gui. @eugenevinitsky any thoughts on this? I have something sort of setup, but am hesitant to create a PR if the new change will lead to confusion

**Comment by eugenevinitsky** [comment]
So it'd be render = False or True? Makes a lot of sense to me.

**Comment by AboudyKreidieh** [comment]
awesome, will create a PR then

**Comment by eugenevinitsky** [comment]
Done, thanks!
