### ISSUE TITLE
No module named 'exp_configs'

### ISSUE THREAD

**Issue by SHITIANYU-hue** [flow-project/flow#828]
I want to test the trained mulitagent model in the simulation environment, so I run this command:

python visualizer_rllib.py ~/ray_results/lord_of_numrings1/PPO_MultiWaveAttenuationPOEnv-v1_0_2020-02-05_19-41-05rh63g1m4 200 --horizon 2000

But I got this wrong:
Traceback (most recent call last):
  File "visualizer_rllib.py", line 382, in <module>
    visualizer_rllib(args)
  File "visualizer_rllib.py", line 62, in visualizer_rllib
    pkl = get_rllib_pkl(result_dir)
  File "/home/tianyushi/code/flow/flow/utils/rllib.py", line 218, in get_rllib_pkl
    config = cloudpickle.load(f)
ModuleNotFoundError: No module named 'exp_configs'

But when I run single agent policy, it can run. I am wondering is there something wrong with multiagent environment?

**Comment by 2855239858** [comment]
Hi, did you solve this bug yet? I encounter this error too.

**Comment by eugenevinitsky** [comment]
Good catch! Will push a fix for this tomorrow.

**Comment by 2855239858** [comment]
I fix this error successfully by following https://github.com/flow-project/flow/pull/841 .

**Comment by eugenevinitsky** [comment]
This is now resolved on master. Please reopen if it persists.
