### ISSUE TITLE
Accelerate the training 

### ISSUE THREAD

**Issue by zpymyyn** [flow-project/flow#844]
Hi, is there a way to accelerate the training, 
e.g., `python train.py multiagent_traffic_light_grid` ?

PS. I've already increased `num_cpus` to 8  and decreased `rollout_size` to 100.
PPS. I changed every `vf_clip_param` in _ray_ folder, yet the _param.json_ in _ray_results_ still show its value  as 10.0.

Thank you.

**Comment by eugenevinitsky** [comment]
No, there really isn't a way to increase the training without additional work. See issue #616

**Comment by eugenevinitsky** [comment]
There probably are a lot of internal optimizations we don't do though.

**Comment by zpymyyn** [comment]
> There probably are a lot of internal optimizations we don't do though. If you want to identify where we're slow and point them out, we can look into it.

Thanks, I'll look into the linked issue you provided and try to provide helps in general if I can.
