### ISSUE TITLE
New installation of Ray 0.5.0

### ISSUE THREAD

**Issue by lucfisc** [flow-project/flow#86]
Hi, 

I saw that Ray was just updated. In my docker, I tried to pull the you repo but i encountered 
```Automatic Merge failed : fix conflicts and then commit the result ` ` ` 

I then tried to build it again from scratch, I have ray installed but the module ray.rllib.ppo isn't found when I run 'python examples/rllib/figure_eight.py' 
Any change in the installation process ? 

Thanks

**Comment by eugenevinitsky** [comment]
Yes, you need to pull in the master of Flow to resolve this.

**Comment by AboudyKreidieh** [comment]
@lucfisc is this resolved?
