### ISSUE TITLE
Any function to change parameters like max-gap during running?

### ISSUE THREAD

**Issue by zpymyyn** [flow-project/flow#882]
Hi, sorry that the question may be more a SUMO ques than Flow. However I find max-gap harder than others to change during running, or if I missed sth., but failed to find a place even to write new functions that can link to its value once started running.

Thank you ;)

**Comment by eugenevinitsky** [comment]
Yep! Take a look in SumoCarFollowingParams. We write all those sumo car following params to the XML so you can change those

**Comment by zpymyyn** [comment]
> Yep! Take a look in SumoCarFollowingParams. We write all those sumo car following params to the XML so you can change those

Thanks, I may spot some issues after a deeper look. The multiagent_traffic_light_grid example, if I understand correctly, should make the lights as type "actuated" and based on which further control them.  
However the lights are with type "static" in the *.net.xml.
To double check, I also let it print from kernel/network/traci.py and core/params.py, all showing that the lights are "static". 
In fact, as kernel/network/traci.py shows, only when "baseline" is enabled would the lights be actuated.

**Comment by zpymyyn** [comment]
> Yep! Take a look in SumoCarFollowingParams. We write all those sumo car following params to the XML so you can change those

Thanks, I think I may misunderstood sth, thus will close this issue.
