### ISSUE TITLE
Steering and acceleration control for RL agent

### ISSUE THREAD

**Issue by Achin17** [flow-project/flow#885]
Hi there!
As per the current implementation for SUMO, a vehicle can only be controlled using acceleration (continuous) and lane change (discrete) command. Is there a way or a potential plan in future to control the vehicle using steering angle values as well?

**Comment by eugenevinitsky** [comment]
I think this is a feature you could pretty straightforwardly implement! Internally we use a method called slowDown (you can grep this method to find it) to actually set the speed of our vehicles. However, SUMO also has a method called moveToXY which you could use to convert an x, y speed into a new X Y position. We're not going to build this out any time soon but you could definitely do it!

**Comment by Achin17** [comment]
Wasn't aware of the moveToXY method. Should be straightforward then. Thanks!
