### ISSUE TITLE
Sublane model for realistic lane changing

### ISSUE THREAD

**Issue by eugenevinitsky** [flow-project/flow#9]
We can use the sublane model of SUMO to let lane changing be a multi-step process rather than an instantaneous one. 
Link describing it: 
http://sumo.dlr.de/wiki/Simulation/SublaneModel

**Comment by eugenevinitsky** [comment]
Thank you! We will examine this; I don't think incorporating the full SL2015 model is on our timeline yet but making it look better would be a huge boon.

**Comment by AboudyKreidieh** [comment]
It turns out we currently have this functionality (something one of the student from the 290O course figured out). Would be happy to discuss this with anyone that's interested.

**Comment by eugenevinitsky** [comment]
@AboudyKreidieh can we document it then rather than closing this?

**Comment by AboudyKreidieh** [comment]
oh, ya sure! i'll add:
- [ ] a test verifying it's still working
- [ ] some documentation
- [ ] an example controller using this

**Comment by eugenevinitsky** [comment]
Thank you!

**Comment by snageshr** [comment]
Hi when I try to run any scenario using SL2015 as lane change model I get an error as 

Error: value '0' must be greater than or equal to minExclusive facet value '0'
 In file 'X/flow/flow/core/kernel/scenario/debug/cfg/highway_example_20190725-1726581564100818.2933977.add.xml'
 At line/column 4/430. I have enabled the sub-lane using 'lateral_resolution', also attached the .xml file. Can you provide your working solution please.
Thank you.

[highway_example_20190725-1726581564100818.2933977.add.txt](https://github.com/flow-project/flow/files/3433799/highway_example_20190725-1726581564100818.2933977.add.txt)

**Comment by waterhorse1** [comment]
Same Question as above. Can you provide your working solution please.
Thank you.@AboudyKreidieh

**Comment by eugenevinitsky** [comment]
@AboudyKreidieh , do you have sufficient bandwidth for this or should we move this task to someone else?

**Comment by KarlRong** [comment]
> 嗨，当我尝试使用SL2015作为车道变更模型运行任何方案时，都会收到错误消息
> 
> 错误：“0”值必须大于或等于minExclusive方面值“0”
> 在文件“X /流量/流/核心/核心/场景/调试/ cfg中/ highway_example_20190725-1726581564100818.2933977.add.xml”
> 在行/列4/430。我已使用“ lateral_resolution”启用了子车道，并附加了.xml文件。您能提供您的工作解决方案吗？
> 谢谢。
> 
> [Highway_example_20190725-1726581564100818.2933977.add.txt](https://github.com/flow-project/flow/files/3433799/highway_example_20190725-1726581564100818.2933977.add.txt)

I encounte the same problem and resolve it by modity the value of "lc_impatience" from "0" to "0.1". Besides the value of "lc_time_to_impatience" also cannot be "inf", I choose "1" to avoid error. 
I believe this problem is relevant to XML scheme. But it's too complex to me and I still dont know the reason. Please notify me if you get any clue on this problem.
Hope flow can have better support for lanechange model in the future. Only acceleration is really not enough for autonomousdriving.

**Comment by eugenevinitsky** [comment]
Yeah, this is a low priority for us but I expect this feature to show up over the next month. Thanks for the sugestions!
