### ISSUE TITLE
[website] Move website to https://flow-project.github.io/

### ISSUE THREAD

**Issue by cathywu** [flow-project/flow#92]
Move website from https://berkeleyflow.github.io/ to https://flow-project.github.io/ and add a re-direct to https://berkeleyflow.github.io/.

**Comment by nskh** [comment]
[flow-project.github.io](flow-project.github.io) is now live. unclear about how to redirect so that's not done yet.

**Comment by cathywu** [comment]
Wonderful, thanks Nish! Yes, we should re-direct so that we don't need to
maintain 2 websites.

For the re-direct, you can try this:
https://stackoverflow.com/questions/5411538/redirect-from-an-html-page#5411567

**Comment by eugenevinitsky** [comment]
It's not perfect, but doing 
<script language="javascript">
    window.location.href = "https://flow-project.github.io/"
</script>
  <meta http-equiv="refresh" content="0; url=https://flow-project.github.io/" />

appears to have done the trick.

**Comment by cathywu** [comment]
Woohoo!!
