### ISSUE TITLE
Compatibility with the latest SUMO (v1.6.0) 

### ISSUE THREAD

**Issue by jerrychen017** [flow-project/flow#947]
## Compatibility with the latest SUMO (v1.6.0) 

Dear all, 
I wonder if the flow project plan to adopt the latest SUMO (v1.6.0). 
The flow documentation says it isn't compatible with the latest SUMO. Are there any known incompatibilities? 

Thanks!

**Comment by eugenevinitsky** [comment]
There are not known incompatibilities, we're just slow to upgrade because a lot of our benchmark experiments change and we look to keep things stable. I suspect that if you just upgrade you will not have an issue.

**Comment by jerrychen017** [comment]
> There are not known incompatibilities, we're just slow to upgrade because a lot of our benchmark experiments change and we look to keep things stable. I suspect that if you just upgrade you will not have an issue.

Thanks for your quick response! 
In the project I'm working on, I compared results from SUMO v1.1.0 and SUMO v1.6.0. It looks like training with the latest SUMO can produce much better results compared to SUMO v1.1.0. I think one possible reason can be that vehicles acceleration and deceleration are different between the two versions.
