### ISSUE TITLE
Can't preview tutorials on github

### ISSUE THREAD

**Issue by cathywu** [flow-project/flow#98]
I cannot preview several of the tutorials on github (screenshots of error below) -- anyone else have this problem?

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/329117/45116956-26e27f00-b109-11e8-8865-00cfa8c638a4.png">

<img width="990" alt="image" src="https://user-images.githubusercontent.com/329117/45116998-44174d80-b109-11e8-8a92-af4625cb11ba.png">

Links for convenience:
https://github.com/flow-project/flow/blob/master/tutorials/tutorial02_rllib.ipynb
https://github.com/flow-project/flow/blob/master/tutorials/tutorial03_rllab.ipynb

**Comment by AboudyKreidieh** [comment]
this looks like a stochastic thing. there might be an issue on the server sides

**Comment by cathywu** [comment]
Ah cool, I'll call this resolved then! Thanks for looking into this!
